// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "add_watermark.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic add_watermark::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic add_watermark::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<13> add_watermark::ap_ST_fsm_state1 = "1";
const sc_lv<13> add_watermark::ap_ST_fsm_state2 = "10";
const sc_lv<13> add_watermark::ap_ST_fsm_state3 = "100";
const sc_lv<13> add_watermark::ap_ST_fsm_state4 = "1000";
const sc_lv<13> add_watermark::ap_ST_fsm_state5 = "10000";
const sc_lv<13> add_watermark::ap_ST_fsm_state6 = "100000";
const sc_lv<13> add_watermark::ap_ST_fsm_state7 = "1000000";
const sc_lv<13> add_watermark::ap_ST_fsm_state8 = "10000000";
const sc_lv<13> add_watermark::ap_ST_fsm_state9 = "100000000";
const sc_lv<13> add_watermark::ap_ST_fsm_state10 = "1000000000";
const sc_lv<13> add_watermark::ap_ST_fsm_state11 = "10000000000";
const sc_lv<13> add_watermark::ap_ST_fsm_state12 = "100000000000";
const sc_lv<13> add_watermark::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<32> add_watermark::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> add_watermark::ap_const_lv32_1 = "1";
const sc_lv<1> add_watermark::ap_const_lv1_0 = "0";
const sc_lv<1> add_watermark::ap_const_lv1_1 = "1";
const sc_lv<32> add_watermark::ap_const_lv32_2 = "10";
const sc_lv<32> add_watermark::ap_const_lv32_8 = "1000";
const sc_lv<32> add_watermark::ap_const_lv32_A = "1010";
const sc_lv<32> add_watermark::ap_const_lv32_B = "1011";
const sc_lv<3> add_watermark::ap_const_lv3_0 = "000";
const sc_lv<32> add_watermark::ap_const_lv32_3 = "11";
const sc_lv<32> add_watermark::ap_const_lv32_9 = "1001";
const sc_lv<32> add_watermark::ap_const_lv32_C = "1100";
const sc_lv<32> add_watermark::ap_const_lv32_7 = "111";
const sc_lv<32> add_watermark::ap_const_lv32_5 = "101";
const sc_lv<32> add_watermark::ap_const_lv32_4 = "100";
const sc_lv<32> add_watermark::ap_const_lv32_6 = "110";
const sc_lv<3> add_watermark::ap_const_lv3_4 = "100";
const sc_lv<3> add_watermark::ap_const_lv3_1 = "1";
const sc_lv<2> add_watermark::ap_const_lv2_0 = "00";
const sc_lv<8> add_watermark::ap_const_lv8_0 = "00000000";
const sc_lv<20> add_watermark::ap_const_lv20_A = "1010";
const bool add_watermark::ap_const_boolean_1 = true;

add_watermark::add_watermark(sc_module_name name) : sc_module(name), mVcdFile(0) {
    temp_U = new add_watermark_temp("temp_U");
    temp_U->clk(ap_clk);
    temp_U->reset(ap_rst);
    temp_U->address0(temp_address0);
    temp_U->ce0(temp_ce0);
    temp_U->we0(temp_we0);
    temp_U->d0(grp_dct_step_fu_191_dst_d0);
    temp_U->q0(temp_q0);
    temp_U->address1(temp_address1);
    temp_U->ce1(temp_ce1);
    temp_U->we1(temp_we1);
    temp_U->d1(grp_dct_step_fu_191_dst_d1);
    temp_U->q1(temp_q1);
    buf_2d_in_U = new add_watermark_bufeOg("buf_2d_in_U");
    buf_2d_in_U->clk(ap_clk);
    buf_2d_in_U->reset(ap_rst);
    buf_2d_in_U->address0(buf_2d_in_address0);
    buf_2d_in_U->ce0(buf_2d_in_ce0);
    buf_2d_in_U->we0(buf_2d_in_we0);
    buf_2d_in_U->d0(buf_2d_in_d0);
    buf_2d_in_U->q0(buf_2d_in_q0);
    buf_2d_in_U->address1(grp_dct_step_fu_191_src_address1);
    buf_2d_in_U->ce1(buf_2d_in_ce1);
    buf_2d_in_U->q1(buf_2d_in_q1);
    buf_temp_dct_U = new add_watermark_temp("buf_temp_dct_U");
    buf_temp_dct_U->clk(ap_clk);
    buf_temp_dct_U->reset(ap_rst);
    buf_temp_dct_U->address0(buf_temp_dct_address0);
    buf_temp_dct_U->ce0(buf_temp_dct_ce0);
    buf_temp_dct_U->we0(buf_temp_dct_we0);
    buf_temp_dct_U->d0(grp_dct_step_fu_191_dst_d0);
    buf_temp_dct_U->q0(buf_temp_dct_q0);
    buf_temp_dct_U->address1(buf_temp_dct_address1);
    buf_temp_dct_U->ce1(buf_temp_dct_ce1);
    buf_temp_dct_U->we1(buf_temp_dct_we1);
    buf_temp_dct_U->d1(grp_dct_step_fu_191_dst_d1);
    buf_temp_dct_U->q1(buf_temp_dct_q1);
    buf_2d_out_U = new add_watermark_bufg8j("buf_2d_out_U");
    buf_2d_out_U->clk(ap_clk);
    buf_2d_out_U->reset(ap_rst);
    buf_2d_out_U->address0(buf_2d_out_address0);
    buf_2d_out_U->ce0(buf_2d_out_ce0);
    buf_2d_out_U->we0(buf_2d_out_we0);
    buf_2d_out_U->d0(grp_integer_idct_fu_165_out_r_d0);
    buf_2d_out_U->q0(buf_2d_out_q0);
    buf_2d_out_U->address1(grp_integer_idct_fu_165_out_r_address1);
    buf_2d_out_U->ce1(buf_2d_out_ce1);
    buf_2d_out_U->we1(buf_2d_out_we1);
    buf_2d_out_U->d1(grp_integer_idct_fu_165_out_r_d1);
    grp_integer_idct_fu_165 = new integer_idct("grp_integer_idct_fu_165");
    grp_integer_idct_fu_165->ap_clk(ap_clk);
    grp_integer_idct_fu_165->ap_rst(ap_rst);
    grp_integer_idct_fu_165->ap_start(grp_integer_idct_fu_165_ap_start);
    grp_integer_idct_fu_165->ap_done(grp_integer_idct_fu_165_ap_done);
    grp_integer_idct_fu_165->ap_idle(grp_integer_idct_fu_165_ap_idle);
    grp_integer_idct_fu_165->ap_ready(grp_integer_idct_fu_165_ap_ready);
    grp_integer_idct_fu_165->src_0_0_V_read(buf_temp_qft_0_0_V_reg_538);
    grp_integer_idct_fu_165->src_0_1_V_read(buf_temp_qft_0_1_V_reg_543);
    grp_integer_idct_fu_165->src_0_2_V_read(buf_temp_qft_0_2_V_reg_548);
    grp_integer_idct_fu_165->src_0_3_V_read(buf_temp_qft_0_3_V_2_reg_613);
    grp_integer_idct_fu_165->src_1_0_V_read(buf_temp_qft_1_0_V_reg_553);
    grp_integer_idct_fu_165->src_1_1_V_read(buf_temp_qft_1_1_V_reg_558);
    grp_integer_idct_fu_165->src_1_2_V_read(buf_temp_qft_1_2_V_2_reg_608);
    grp_integer_idct_fu_165->src_1_3_V_read(buf_temp_qft_1_3_V_reg_563);
    grp_integer_idct_fu_165->src_2_0_V_read(buf_temp_qft_2_0_V_reg_568);
    grp_integer_idct_fu_165->src_2_1_V_read(buf_temp_qft_2_1_V_2_reg_603);
    grp_integer_idct_fu_165->src_2_2_V_read(buf_temp_qft_2_2_V_reg_573);
    grp_integer_idct_fu_165->src_2_3_V_read(buf_temp_qft_2_3_V_reg_578);
    grp_integer_idct_fu_165->src_3_0_V_read(buf_temp_qft_3_0_V_2_reg_598);
    grp_integer_idct_fu_165->src_3_1_V_read(buf_temp_qft_3_1_V_reg_583);
    grp_integer_idct_fu_165->src_3_2_V_read(buf_temp_qft_3_2_V_reg_588);
    grp_integer_idct_fu_165->src_3_3_V_read(buf_temp_qft_3_3_V_reg_593);
    grp_integer_idct_fu_165->out_r_address0(grp_integer_idct_fu_165_out_r_address0);
    grp_integer_idct_fu_165->out_r_ce0(grp_integer_idct_fu_165_out_r_ce0);
    grp_integer_idct_fu_165->out_r_we0(grp_integer_idct_fu_165_out_r_we0);
    grp_integer_idct_fu_165->out_r_d0(grp_integer_idct_fu_165_out_r_d0);
    grp_integer_idct_fu_165->out_r_address1(grp_integer_idct_fu_165_out_r_address1);
    grp_integer_idct_fu_165->out_r_ce1(grp_integer_idct_fu_165_out_r_ce1);
    grp_integer_idct_fu_165->out_r_we1(grp_integer_idct_fu_165_out_r_we1);
    grp_integer_idct_fu_165->out_r_d1(grp_integer_idct_fu_165_out_r_d1);
    grp_quantificat_fu_186 = new quantificat("grp_quantificat_fu_186");
    grp_quantificat_fu_186->ap_clk(ap_clk);
    grp_quantificat_fu_186->ap_rst(ap_rst);
    grp_quantificat_fu_186->ap_start(grp_quantificat_fu_186_ap_start);
    grp_quantificat_fu_186->ap_done(grp_quantificat_fu_186_ap_done);
    grp_quantificat_fu_186->ap_idle(grp_quantificat_fu_186_ap_idle);
    grp_quantificat_fu_186->ap_ready(grp_quantificat_fu_186_ap_ready);
    grp_quantificat_fu_186->qsrc_address0(grp_quantificat_fu_186_qsrc_address0);
    grp_quantificat_fu_186->qsrc_ce0(grp_quantificat_fu_186_qsrc_ce0);
    grp_quantificat_fu_186->qsrc_q0(buf_temp_dct_q0);
    grp_quantificat_fu_186->qsrc_address1(grp_quantificat_fu_186_qsrc_address1);
    grp_quantificat_fu_186->qsrc_ce1(grp_quantificat_fu_186_qsrc_ce1);
    grp_quantificat_fu_186->qsrc_q1(buf_temp_dct_q1);
    grp_quantificat_fu_186->ap_return_0(grp_quantificat_fu_186_ap_return_0);
    grp_quantificat_fu_186->ap_return_1(grp_quantificat_fu_186_ap_return_1);
    grp_quantificat_fu_186->ap_return_2(grp_quantificat_fu_186_ap_return_2);
    grp_quantificat_fu_186->ap_return_3(grp_quantificat_fu_186_ap_return_3);
    grp_quantificat_fu_186->ap_return_4(grp_quantificat_fu_186_ap_return_4);
    grp_quantificat_fu_186->ap_return_5(grp_quantificat_fu_186_ap_return_5);
    grp_quantificat_fu_186->ap_return_6(grp_quantificat_fu_186_ap_return_6);
    grp_quantificat_fu_186->ap_return_7(grp_quantificat_fu_186_ap_return_7);
    grp_quantificat_fu_186->ap_return_8(grp_quantificat_fu_186_ap_return_8);
    grp_quantificat_fu_186->ap_return_9(grp_quantificat_fu_186_ap_return_9);
    grp_quantificat_fu_186->ap_return_10(grp_quantificat_fu_186_ap_return_10);
    grp_quantificat_fu_186->ap_return_11(grp_quantificat_fu_186_ap_return_11);
    grp_quantificat_fu_186->ap_return_12(grp_quantificat_fu_186_ap_return_12);
    grp_quantificat_fu_186->ap_return_13(grp_quantificat_fu_186_ap_return_13);
    grp_quantificat_fu_186->ap_return_14(grp_quantificat_fu_186_ap_return_14);
    grp_quantificat_fu_186->ap_return_15(grp_quantificat_fu_186_ap_return_15);
    grp_dct_step_fu_191 = new dct_step("grp_dct_step_fu_191");
    grp_dct_step_fu_191->ap_clk(ap_clk);
    grp_dct_step_fu_191->ap_rst(ap_rst);
    grp_dct_step_fu_191->ap_start(grp_dct_step_fu_191_ap_start);
    grp_dct_step_fu_191->ap_done(grp_dct_step_fu_191_ap_done);
    grp_dct_step_fu_191->ap_idle(grp_dct_step_fu_191_ap_idle);
    grp_dct_step_fu_191->ap_ready(grp_dct_step_fu_191_ap_ready);
    grp_dct_step_fu_191->src_address0(grp_dct_step_fu_191_src_address0);
    grp_dct_step_fu_191->src_ce0(grp_dct_step_fu_191_src_ce0);
    grp_dct_step_fu_191->src_q0(grp_dct_step_fu_191_src_q0);
    grp_dct_step_fu_191->src_address1(grp_dct_step_fu_191_src_address1);
    grp_dct_step_fu_191->src_ce1(grp_dct_step_fu_191_src_ce1);
    grp_dct_step_fu_191->src_q1(grp_dct_step_fu_191_src_q1);
    grp_dct_step_fu_191->dst_address0(grp_dct_step_fu_191_dst_address0);
    grp_dct_step_fu_191->dst_ce0(grp_dct_step_fu_191_dst_ce0);
    grp_dct_step_fu_191->dst_we0(grp_dct_step_fu_191_dst_we0);
    grp_dct_step_fu_191->dst_d0(grp_dct_step_fu_191_dst_d0);
    grp_dct_step_fu_191->dst_address1(grp_dct_step_fu_191_dst_address1);
    grp_dct_step_fu_191->dst_ce1(grp_dct_step_fu_191_dst_ce1);
    grp_dct_step_fu_191->dst_we1(grp_dct_step_fu_191_dst_we1);
    grp_dct_step_fu_191->dst_d1(grp_dct_step_fu_191_dst_d1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( exitcond1_i1_fu_414_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( exitcond1_i1_fu_414_p2 );

    SC_METHOD(thread_buf_2d_in_address0);
    sensitive << ( grp_dct_step_fu_191_src_address0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_129_cast_fu_278_p1 );

    SC_METHOD(thread_buf_2d_in_ce0);
    sensitive << ( grp_dct_step_fu_191_src_ce0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_buf_2d_in_ce1);
    sensitive << ( grp_dct_step_fu_191_src_ce1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_buf_2d_in_d0);
    sensitive << ( indata_q0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buf_2d_in_we0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buf_2d_out_address0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( grp_integer_idct_fu_165_out_r_address0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_130_cast_fu_475_p1 );

    SC_METHOD(thread_buf_2d_out_ce0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( grp_integer_idct_fu_165_out_r_ce0 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_buf_2d_out_ce1);
    sensitive << ( grp_integer_idct_fu_165_out_r_ce1 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_buf_2d_out_we0);
    sensitive << ( grp_integer_idct_fu_165_out_r_we0 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_buf_2d_out_we1);
    sensitive << ( grp_integer_idct_fu_165_out_r_we1 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_buf_temp_dct_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( grp_quantificat_fu_186_qsrc_address0 );
    sensitive << ( grp_dct_step_fu_191_dst_address0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_buf_temp_dct_address1);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( grp_quantificat_fu_186_qsrc_address1 );
    sensitive << ( grp_dct_step_fu_191_dst_address1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_buf_temp_dct_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( grp_quantificat_fu_186_qsrc_ce0 );
    sensitive << ( grp_dct_step_fu_191_dst_ce0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_buf_temp_dct_ce1);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( grp_quantificat_fu_186_qsrc_ce1 );
    sensitive << ( grp_dct_step_fu_191_dst_ce1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_buf_temp_dct_we0);
    sensitive << ( grp_dct_step_fu_191_dst_we0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_buf_temp_dct_we1);
    sensitive << ( grp_dct_step_fu_191_dst_we1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_buf_temp_qft_0_3_V_1_fu_376_p2);
    sensitive << ( grp_quantificat_fu_186_ap_return_3 );

    SC_METHOD(thread_buf_temp_qft_0_3_V_2_fu_406_p3);
    sensitive << ( tmp_reg_512 );
    sensitive << ( grp_quantificat_fu_186_ap_return_3 );
    sensitive << ( buf_temp_qft_0_3_V_1_fu_376_p2 );

    SC_METHOD(thread_buf_temp_qft_1_2_V_1_fu_364_p2);
    sensitive << ( grp_quantificat_fu_186_ap_return_6 );

    SC_METHOD(thread_buf_temp_qft_1_2_V_2_fu_398_p3);
    sensitive << ( tmp_reg_512 );
    sensitive << ( grp_quantificat_fu_186_ap_return_6 );
    sensitive << ( buf_temp_qft_1_2_V_1_fu_364_p2 );

    SC_METHOD(thread_buf_temp_qft_2_1_V_1_fu_370_p2);
    sensitive << ( grp_quantificat_fu_186_ap_return_9 );

    SC_METHOD(thread_buf_temp_qft_2_1_V_2_fu_390_p3);
    sensitive << ( tmp_reg_512 );
    sensitive << ( grp_quantificat_fu_186_ap_return_9 );
    sensitive << ( buf_temp_qft_2_1_V_1_fu_370_p2 );

    SC_METHOD(thread_buf_temp_qft_3_0_V_1_fu_358_p2);
    sensitive << ( grp_quantificat_fu_186_ap_return_12 );

    SC_METHOD(thread_buf_temp_qft_3_0_V_2_fu_382_p3);
    sensitive << ( tmp_reg_512 );
    sensitive << ( grp_quantificat_fu_186_ap_return_12 );
    sensitive << ( buf_temp_qft_3_0_V_1_fu_358_p2 );

    SC_METHOD(thread_c_1_fu_460_p2);
    sensitive << ( c_i1_reg_154 );

    SC_METHOD(thread_c_fu_248_p2);
    sensitive << ( c_i_reg_132 );

    SC_METHOD(thread_c_i1_cast_fu_450_p1);
    sensitive << ( c_i1_reg_154 );

    SC_METHOD(thread_c_i_cast_fu_238_p1);
    sensitive << ( c_i_reg_132 );

    SC_METHOD(thread_exitcond1_i1_fu_414_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( r_i1_reg_143 );

    SC_METHOD(thread_exitcond1_i_fu_197_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( r_i_reg_121 );

    SC_METHOD(thread_exitcond_i1_fu_454_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( c_i1_reg_154 );

    SC_METHOD(thread_exitcond_i_fu_242_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( c_i_reg_132 );

    SC_METHOD(thread_grp_dct_step_fu_191_ap_start);
    sensitive << ( ap_reg_grp_dct_step_fu_191_ap_start );

    SC_METHOD(thread_grp_dct_step_fu_191_src_q0);
    sensitive << ( temp_q0 );
    sensitive << ( buf_2d_in_q0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_grp_dct_step_fu_191_src_q1);
    sensitive << ( temp_q1 );
    sensitive << ( buf_2d_in_q1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_grp_integer_idct_fu_165_ap_start);
    sensitive << ( ap_reg_grp_integer_idct_fu_165_ap_start );

    SC_METHOD(thread_grp_quantificat_fu_186_ap_start);
    sensitive << ( ap_reg_grp_quantificat_fu_186_ap_start );

    SC_METHOD(thread_indata_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_i_9_fu_259_p1 );

    SC_METHOD(thread_indata_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_outdata_address0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( tmp_5_i_fu_485_p1 );

    SC_METHOD(thread_outdata_ce0);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_outdata_d0);
    sensitive << ( buf_2d_out_q0 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_outdata_we0);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_r_2_fu_420_p2);
    sensitive << ( r_i1_reg_143 );

    SC_METHOD(thread_r_fu_203_p2);
    sensitive << ( r_i_reg_121 );

    SC_METHOD(thread_temp_address0);
    sensitive << ( grp_dct_step_fu_191_src_address0 );
    sensitive << ( grp_dct_step_fu_191_dst_address0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_temp_address1);
    sensitive << ( grp_dct_step_fu_191_src_address1 );
    sensitive << ( grp_dct_step_fu_191_dst_address1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_temp_ce0);
    sensitive << ( grp_dct_step_fu_191_src_ce0 );
    sensitive << ( grp_dct_step_fu_191_dst_ce0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_temp_ce1);
    sensitive << ( grp_dct_step_fu_191_src_ce1 );
    sensitive << ( grp_dct_step_fu_191_dst_ce1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_temp_we0);
    sensitive << ( grp_dct_step_fu_191_dst_we0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_temp_we1);
    sensitive << ( grp_dct_step_fu_191_dst_we1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_tmp_115_fu_209_p1);
    sensitive << ( r_i_reg_121 );

    SC_METHOD(thread_tmp_116_fu_438_p1);
    sensitive << ( r_i1_reg_143 );

    SC_METHOD(thread_tmp_125_cast_fu_229_p1);
    sensitive << ( tmp_s_fu_221_p3 );

    SC_METHOD(thread_tmp_127_cast_fu_434_p1);
    sensitive << ( tmp_96_fu_426_p3 );

    SC_METHOD(thread_tmp_129_cast_fu_278_p1);
    sensitive << ( tmp_97_reg_533 );

    SC_METHOD(thread_tmp_130_cast_fu_475_p1);
    sensitive << ( tmp_98_fu_470_p2 );

    SC_METHOD(thread_tmp_1_i1_fu_442_p3);
    sensitive << ( tmp_116_fu_438_p1 );

    SC_METHOD(thread_tmp_2_i_cast_fu_264_p1);
    sensitive << ( c_i_reg_132 );

    SC_METHOD(thread_tmp_3_i1_cast_fu_466_p1);
    sensitive << ( c_i1_reg_154 );

    SC_METHOD(thread_tmp_4_i_fu_480_p2);
    sensitive << ( tmp_1_i1_reg_631 );
    sensitive << ( c_i1_cast_fu_450_p1 );

    SC_METHOD(thread_tmp_5_i_fu_485_p1);
    sensitive << ( tmp_4_i_reg_649 );

    SC_METHOD(thread_tmp_96_fu_426_p3);
    sensitive << ( r_i1_reg_143 );

    SC_METHOD(thread_tmp_97_fu_268_p2);
    sensitive << ( tmp_125_cast_reg_507 );
    sensitive << ( tmp_2_i_cast_fu_264_p1 );

    SC_METHOD(thread_tmp_98_fu_470_p2);
    sensitive << ( tmp_127_cast_reg_626 );
    sensitive << ( tmp_3_i1_cast_fu_466_p1 );

    SC_METHOD(thread_tmp_9_i_fu_254_p2);
    sensitive << ( tmp_i_reg_502 );
    sensitive << ( c_i_cast_fu_238_p1 );

    SC_METHOD(thread_tmp_fu_233_p2);
    sensitive << ( mark );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_i_fu_197_p2 );

    SC_METHOD(thread_tmp_i_9_fu_259_p1);
    sensitive << ( tmp_9_i_fu_254_p2 );

    SC_METHOD(thread_tmp_i_fu_213_p3);
    sensitive << ( tmp_115_fu_209_p1 );

    SC_METHOD(thread_tmp_s_fu_221_p3);
    sensitive << ( r_i_reg_121 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_i_fu_197_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_i_fu_242_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( grp_quantificat_fu_186_ap_done );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( exitcond1_i1_fu_414_p2 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( exitcond_i1_fu_454_p2 );
    sensitive << ( grp_integer_idct_fu_165_ap_done );
    sensitive << ( grp_dct_step_fu_191_ap_done );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );

    ap_CS_fsm = "0000000000001";
    ap_reg_grp_integer_idct_fu_165_ap_start = SC_LOGIC_0;
    ap_reg_grp_quantificat_fu_186_ap_start = SC_LOGIC_0;
    ap_reg_grp_dct_step_fu_191_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "add_watermark_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, indata_address0, "(port)indata_address0");
    sc_trace(mVcdFile, indata_ce0, "(port)indata_ce0");
    sc_trace(mVcdFile, indata_q0, "(port)indata_q0");
    sc_trace(mVcdFile, mark, "(port)mark");
    sc_trace(mVcdFile, outdata_address0, "(port)outdata_address0");
    sc_trace(mVcdFile, outdata_ce0, "(port)outdata_ce0");
    sc_trace(mVcdFile, outdata_we0, "(port)outdata_we0");
    sc_trace(mVcdFile, outdata_d0, "(port)outdata_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, r_fu_203_p2, "r_fu_203_p2");
    sc_trace(mVcdFile, r_reg_497, "r_reg_497");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_i_fu_213_p3, "tmp_i_fu_213_p3");
    sc_trace(mVcdFile, tmp_i_reg_502, "tmp_i_reg_502");
    sc_trace(mVcdFile, exitcond1_i_fu_197_p2, "exitcond1_i_fu_197_p2");
    sc_trace(mVcdFile, tmp_125_cast_fu_229_p1, "tmp_125_cast_fu_229_p1");
    sc_trace(mVcdFile, tmp_125_cast_reg_507, "tmp_125_cast_reg_507");
    sc_trace(mVcdFile, tmp_fu_233_p2, "tmp_fu_233_p2");
    sc_trace(mVcdFile, tmp_reg_512, "tmp_reg_512");
    sc_trace(mVcdFile, c_fu_248_p2, "c_fu_248_p2");
    sc_trace(mVcdFile, c_reg_523, "c_reg_523");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, exitcond_i_fu_242_p2, "exitcond_i_fu_242_p2");
    sc_trace(mVcdFile, tmp_97_fu_268_p2, "tmp_97_fu_268_p2");
    sc_trace(mVcdFile, tmp_97_reg_533, "tmp_97_reg_533");
    sc_trace(mVcdFile, buf_temp_qft_0_0_V_reg_538, "buf_temp_qft_0_0_V_reg_538");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_done, "grp_quantificat_fu_186_ap_done");
    sc_trace(mVcdFile, buf_temp_qft_0_1_V_reg_543, "buf_temp_qft_0_1_V_reg_543");
    sc_trace(mVcdFile, buf_temp_qft_0_2_V_reg_548, "buf_temp_qft_0_2_V_reg_548");
    sc_trace(mVcdFile, buf_temp_qft_1_0_V_reg_553, "buf_temp_qft_1_0_V_reg_553");
    sc_trace(mVcdFile, buf_temp_qft_1_1_V_reg_558, "buf_temp_qft_1_1_V_reg_558");
    sc_trace(mVcdFile, buf_temp_qft_1_3_V_reg_563, "buf_temp_qft_1_3_V_reg_563");
    sc_trace(mVcdFile, buf_temp_qft_2_0_V_reg_568, "buf_temp_qft_2_0_V_reg_568");
    sc_trace(mVcdFile, buf_temp_qft_2_2_V_reg_573, "buf_temp_qft_2_2_V_reg_573");
    sc_trace(mVcdFile, buf_temp_qft_2_3_V_reg_578, "buf_temp_qft_2_3_V_reg_578");
    sc_trace(mVcdFile, buf_temp_qft_3_1_V_reg_583, "buf_temp_qft_3_1_V_reg_583");
    sc_trace(mVcdFile, buf_temp_qft_3_2_V_reg_588, "buf_temp_qft_3_2_V_reg_588");
    sc_trace(mVcdFile, buf_temp_qft_3_3_V_reg_593, "buf_temp_qft_3_3_V_reg_593");
    sc_trace(mVcdFile, buf_temp_qft_3_0_V_2_fu_382_p3, "buf_temp_qft_3_0_V_2_fu_382_p3");
    sc_trace(mVcdFile, buf_temp_qft_3_0_V_2_reg_598, "buf_temp_qft_3_0_V_2_reg_598");
    sc_trace(mVcdFile, buf_temp_qft_2_1_V_2_fu_390_p3, "buf_temp_qft_2_1_V_2_fu_390_p3");
    sc_trace(mVcdFile, buf_temp_qft_2_1_V_2_reg_603, "buf_temp_qft_2_1_V_2_reg_603");
    sc_trace(mVcdFile, buf_temp_qft_1_2_V_2_fu_398_p3, "buf_temp_qft_1_2_V_2_fu_398_p3");
    sc_trace(mVcdFile, buf_temp_qft_1_2_V_2_reg_608, "buf_temp_qft_1_2_V_2_reg_608");
    sc_trace(mVcdFile, buf_temp_qft_0_3_V_2_fu_406_p3, "buf_temp_qft_0_3_V_2_fu_406_p3");
    sc_trace(mVcdFile, buf_temp_qft_0_3_V_2_reg_613, "buf_temp_qft_0_3_V_2_reg_613");
    sc_trace(mVcdFile, r_2_fu_420_p2, "r_2_fu_420_p2");
    sc_trace(mVcdFile, r_2_reg_621, "r_2_reg_621");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, tmp_127_cast_fu_434_p1, "tmp_127_cast_fu_434_p1");
    sc_trace(mVcdFile, tmp_127_cast_reg_626, "tmp_127_cast_reg_626");
    sc_trace(mVcdFile, exitcond1_i1_fu_414_p2, "exitcond1_i1_fu_414_p2");
    sc_trace(mVcdFile, tmp_1_i1_fu_442_p3, "tmp_1_i1_fu_442_p3");
    sc_trace(mVcdFile, tmp_1_i1_reg_631, "tmp_1_i1_reg_631");
    sc_trace(mVcdFile, c_1_fu_460_p2, "c_1_fu_460_p2");
    sc_trace(mVcdFile, c_1_reg_639, "c_1_reg_639");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, exitcond_i1_fu_454_p2, "exitcond_i1_fu_454_p2");
    sc_trace(mVcdFile, tmp_4_i_fu_480_p2, "tmp_4_i_fu_480_p2");
    sc_trace(mVcdFile, tmp_4_i_reg_649, "tmp_4_i_reg_649");
    sc_trace(mVcdFile, temp_address0, "temp_address0");
    sc_trace(mVcdFile, temp_ce0, "temp_ce0");
    sc_trace(mVcdFile, temp_we0, "temp_we0");
    sc_trace(mVcdFile, temp_q0, "temp_q0");
    sc_trace(mVcdFile, temp_address1, "temp_address1");
    sc_trace(mVcdFile, temp_ce1, "temp_ce1");
    sc_trace(mVcdFile, temp_we1, "temp_we1");
    sc_trace(mVcdFile, temp_q1, "temp_q1");
    sc_trace(mVcdFile, buf_2d_in_address0, "buf_2d_in_address0");
    sc_trace(mVcdFile, buf_2d_in_ce0, "buf_2d_in_ce0");
    sc_trace(mVcdFile, buf_2d_in_we0, "buf_2d_in_we0");
    sc_trace(mVcdFile, buf_2d_in_d0, "buf_2d_in_d0");
    sc_trace(mVcdFile, buf_2d_in_q0, "buf_2d_in_q0");
    sc_trace(mVcdFile, buf_2d_in_ce1, "buf_2d_in_ce1");
    sc_trace(mVcdFile, buf_2d_in_q1, "buf_2d_in_q1");
    sc_trace(mVcdFile, buf_temp_dct_address0, "buf_temp_dct_address0");
    sc_trace(mVcdFile, buf_temp_dct_ce0, "buf_temp_dct_ce0");
    sc_trace(mVcdFile, buf_temp_dct_we0, "buf_temp_dct_we0");
    sc_trace(mVcdFile, buf_temp_dct_q0, "buf_temp_dct_q0");
    sc_trace(mVcdFile, buf_temp_dct_address1, "buf_temp_dct_address1");
    sc_trace(mVcdFile, buf_temp_dct_ce1, "buf_temp_dct_ce1");
    sc_trace(mVcdFile, buf_temp_dct_we1, "buf_temp_dct_we1");
    sc_trace(mVcdFile, buf_temp_dct_q1, "buf_temp_dct_q1");
    sc_trace(mVcdFile, buf_2d_out_address0, "buf_2d_out_address0");
    sc_trace(mVcdFile, buf_2d_out_ce0, "buf_2d_out_ce0");
    sc_trace(mVcdFile, buf_2d_out_we0, "buf_2d_out_we0");
    sc_trace(mVcdFile, buf_2d_out_q0, "buf_2d_out_q0");
    sc_trace(mVcdFile, buf_2d_out_ce1, "buf_2d_out_ce1");
    sc_trace(mVcdFile, buf_2d_out_we1, "buf_2d_out_we1");
    sc_trace(mVcdFile, grp_integer_idct_fu_165_ap_start, "grp_integer_idct_fu_165_ap_start");
    sc_trace(mVcdFile, grp_integer_idct_fu_165_ap_done, "grp_integer_idct_fu_165_ap_done");
    sc_trace(mVcdFile, grp_integer_idct_fu_165_ap_idle, "grp_integer_idct_fu_165_ap_idle");
    sc_trace(mVcdFile, grp_integer_idct_fu_165_ap_ready, "grp_integer_idct_fu_165_ap_ready");
    sc_trace(mVcdFile, grp_integer_idct_fu_165_out_r_address0, "grp_integer_idct_fu_165_out_r_address0");
    sc_trace(mVcdFile, grp_integer_idct_fu_165_out_r_ce0, "grp_integer_idct_fu_165_out_r_ce0");
    sc_trace(mVcdFile, grp_integer_idct_fu_165_out_r_we0, "grp_integer_idct_fu_165_out_r_we0");
    sc_trace(mVcdFile, grp_integer_idct_fu_165_out_r_d0, "grp_integer_idct_fu_165_out_r_d0");
    sc_trace(mVcdFile, grp_integer_idct_fu_165_out_r_address1, "grp_integer_idct_fu_165_out_r_address1");
    sc_trace(mVcdFile, grp_integer_idct_fu_165_out_r_ce1, "grp_integer_idct_fu_165_out_r_ce1");
    sc_trace(mVcdFile, grp_integer_idct_fu_165_out_r_we1, "grp_integer_idct_fu_165_out_r_we1");
    sc_trace(mVcdFile, grp_integer_idct_fu_165_out_r_d1, "grp_integer_idct_fu_165_out_r_d1");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_start, "grp_quantificat_fu_186_ap_start");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_idle, "grp_quantificat_fu_186_ap_idle");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_ready, "grp_quantificat_fu_186_ap_ready");
    sc_trace(mVcdFile, grp_quantificat_fu_186_qsrc_address0, "grp_quantificat_fu_186_qsrc_address0");
    sc_trace(mVcdFile, grp_quantificat_fu_186_qsrc_ce0, "grp_quantificat_fu_186_qsrc_ce0");
    sc_trace(mVcdFile, grp_quantificat_fu_186_qsrc_address1, "grp_quantificat_fu_186_qsrc_address1");
    sc_trace(mVcdFile, grp_quantificat_fu_186_qsrc_ce1, "grp_quantificat_fu_186_qsrc_ce1");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_return_0, "grp_quantificat_fu_186_ap_return_0");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_return_1, "grp_quantificat_fu_186_ap_return_1");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_return_2, "grp_quantificat_fu_186_ap_return_2");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_return_3, "grp_quantificat_fu_186_ap_return_3");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_return_4, "grp_quantificat_fu_186_ap_return_4");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_return_5, "grp_quantificat_fu_186_ap_return_5");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_return_6, "grp_quantificat_fu_186_ap_return_6");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_return_7, "grp_quantificat_fu_186_ap_return_7");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_return_8, "grp_quantificat_fu_186_ap_return_8");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_return_9, "grp_quantificat_fu_186_ap_return_9");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_return_10, "grp_quantificat_fu_186_ap_return_10");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_return_11, "grp_quantificat_fu_186_ap_return_11");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_return_12, "grp_quantificat_fu_186_ap_return_12");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_return_13, "grp_quantificat_fu_186_ap_return_13");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_return_14, "grp_quantificat_fu_186_ap_return_14");
    sc_trace(mVcdFile, grp_quantificat_fu_186_ap_return_15, "grp_quantificat_fu_186_ap_return_15");
    sc_trace(mVcdFile, grp_dct_step_fu_191_ap_start, "grp_dct_step_fu_191_ap_start");
    sc_trace(mVcdFile, grp_dct_step_fu_191_ap_done, "grp_dct_step_fu_191_ap_done");
    sc_trace(mVcdFile, grp_dct_step_fu_191_ap_idle, "grp_dct_step_fu_191_ap_idle");
    sc_trace(mVcdFile, grp_dct_step_fu_191_ap_ready, "grp_dct_step_fu_191_ap_ready");
    sc_trace(mVcdFile, grp_dct_step_fu_191_src_address0, "grp_dct_step_fu_191_src_address0");
    sc_trace(mVcdFile, grp_dct_step_fu_191_src_ce0, "grp_dct_step_fu_191_src_ce0");
    sc_trace(mVcdFile, grp_dct_step_fu_191_src_q0, "grp_dct_step_fu_191_src_q0");
    sc_trace(mVcdFile, grp_dct_step_fu_191_src_address1, "grp_dct_step_fu_191_src_address1");
    sc_trace(mVcdFile, grp_dct_step_fu_191_src_ce1, "grp_dct_step_fu_191_src_ce1");
    sc_trace(mVcdFile, grp_dct_step_fu_191_src_q1, "grp_dct_step_fu_191_src_q1");
    sc_trace(mVcdFile, grp_dct_step_fu_191_dst_address0, "grp_dct_step_fu_191_dst_address0");
    sc_trace(mVcdFile, grp_dct_step_fu_191_dst_ce0, "grp_dct_step_fu_191_dst_ce0");
    sc_trace(mVcdFile, grp_dct_step_fu_191_dst_we0, "grp_dct_step_fu_191_dst_we0");
    sc_trace(mVcdFile, grp_dct_step_fu_191_dst_d0, "grp_dct_step_fu_191_dst_d0");
    sc_trace(mVcdFile, grp_dct_step_fu_191_dst_address1, "grp_dct_step_fu_191_dst_address1");
    sc_trace(mVcdFile, grp_dct_step_fu_191_dst_ce1, "grp_dct_step_fu_191_dst_ce1");
    sc_trace(mVcdFile, grp_dct_step_fu_191_dst_we1, "grp_dct_step_fu_191_dst_we1");
    sc_trace(mVcdFile, grp_dct_step_fu_191_dst_d1, "grp_dct_step_fu_191_dst_d1");
    sc_trace(mVcdFile, r_i_reg_121, "r_i_reg_121");
    sc_trace(mVcdFile, c_i_reg_132, "c_i_reg_132");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, r_i1_reg_143, "r_i1_reg_143");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, c_i1_reg_154, "c_i1_reg_154");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_reg_grp_integer_idct_fu_165_ap_start, "ap_reg_grp_integer_idct_fu_165_ap_start");
    sc_trace(mVcdFile, ap_reg_grp_quantificat_fu_186_ap_start, "ap_reg_grp_quantificat_fu_186_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_reg_grp_dct_step_fu_191_ap_start, "ap_reg_grp_dct_step_fu_191_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_i_9_fu_259_p1, "tmp_i_9_fu_259_p1");
    sc_trace(mVcdFile, tmp_129_cast_fu_278_p1, "tmp_129_cast_fu_278_p1");
    sc_trace(mVcdFile, tmp_130_cast_fu_475_p1, "tmp_130_cast_fu_475_p1");
    sc_trace(mVcdFile, tmp_5_i_fu_485_p1, "tmp_5_i_fu_485_p1");
    sc_trace(mVcdFile, tmp_115_fu_209_p1, "tmp_115_fu_209_p1");
    sc_trace(mVcdFile, tmp_s_fu_221_p3, "tmp_s_fu_221_p3");
    sc_trace(mVcdFile, c_i_cast_fu_238_p1, "c_i_cast_fu_238_p1");
    sc_trace(mVcdFile, tmp_9_i_fu_254_p2, "tmp_9_i_fu_254_p2");
    sc_trace(mVcdFile, tmp_2_i_cast_fu_264_p1, "tmp_2_i_cast_fu_264_p1");
    sc_trace(mVcdFile, buf_temp_qft_3_0_V_1_fu_358_p2, "buf_temp_qft_3_0_V_1_fu_358_p2");
    sc_trace(mVcdFile, buf_temp_qft_2_1_V_1_fu_370_p2, "buf_temp_qft_2_1_V_1_fu_370_p2");
    sc_trace(mVcdFile, buf_temp_qft_1_2_V_1_fu_364_p2, "buf_temp_qft_1_2_V_1_fu_364_p2");
    sc_trace(mVcdFile, buf_temp_qft_0_3_V_1_fu_376_p2, "buf_temp_qft_0_3_V_1_fu_376_p2");
    sc_trace(mVcdFile, tmp_96_fu_426_p3, "tmp_96_fu_426_p3");
    sc_trace(mVcdFile, tmp_116_fu_438_p1, "tmp_116_fu_438_p1");
    sc_trace(mVcdFile, tmp_3_i1_cast_fu_466_p1, "tmp_3_i1_cast_fu_466_p1");
    sc_trace(mVcdFile, tmp_98_fu_470_p2, "tmp_98_fu_470_p2");
    sc_trace(mVcdFile, c_i1_cast_fu_450_p1, "c_i1_cast_fu_450_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

add_watermark::~add_watermark() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete temp_U;
    delete buf_2d_in_U;
    delete buf_temp_dct_U;
    delete buf_2d_out_U;
    delete grp_integer_idct_fu_165;
    delete grp_quantificat_fu_186;
    delete grp_dct_step_fu_191;
}

void add_watermark::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_dct_step_fu_191_ap_start = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
              esl_seteq<1,1,1>(exitcond1_i_fu_197_p2.read(), ap_const_lv1_1)) || 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
            ap_reg_grp_dct_step_fu_191_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_dct_step_fu_191_ap_ready.read())) {
            ap_reg_grp_dct_step_fu_191_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_integer_idct_fu_165_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
             esl_seteq<1,1,1>(grp_quantificat_fu_186_ap_done.read(), ap_const_logic_1))) {
            ap_reg_grp_integer_idct_fu_165_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_integer_idct_fu_165_ap_ready.read())) {
            ap_reg_grp_integer_idct_fu_165_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_quantificat_fu_186_ap_start = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
            ap_reg_grp_quantificat_fu_186_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_quantificat_fu_186_ap_ready.read())) {
            ap_reg_grp_quantificat_fu_186_ap_start = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        c_i1_reg_154 = c_1_reg_639.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i1_fu_414_p2.read()))) {
        c_i1_reg_154 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        c_i_reg_132 = c_reg_523.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond1_i_fu_197_p2.read(), ap_const_lv1_0))) {
        c_i_reg_132 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i1_fu_454_p2.read()))) {
        r_i1_reg_143 = r_2_reg_621.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(grp_integer_idct_fu_165_ap_done.read(), ap_const_logic_1))) {
        r_i1_reg_143 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_242_p2.read()))) {
        r_i_reg_121 = r_reg_497.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        r_i_reg_121 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(grp_quantificat_fu_186_ap_done.read(), ap_const_logic_1))) {
        buf_temp_qft_0_0_V_reg_538 = grp_quantificat_fu_186_ap_return_0.read();
        buf_temp_qft_0_1_V_reg_543 = grp_quantificat_fu_186_ap_return_1.read();
        buf_temp_qft_0_2_V_reg_548 = grp_quantificat_fu_186_ap_return_2.read();
        buf_temp_qft_0_3_V_2_reg_613 = buf_temp_qft_0_3_V_2_fu_406_p3.read();
        buf_temp_qft_1_0_V_reg_553 = grp_quantificat_fu_186_ap_return_4.read();
        buf_temp_qft_1_1_V_reg_558 = grp_quantificat_fu_186_ap_return_5.read();
        buf_temp_qft_1_2_V_2_reg_608 = buf_temp_qft_1_2_V_2_fu_398_p3.read();
        buf_temp_qft_1_3_V_reg_563 = grp_quantificat_fu_186_ap_return_7.read();
        buf_temp_qft_2_0_V_reg_568 = grp_quantificat_fu_186_ap_return_8.read();
        buf_temp_qft_2_1_V_2_reg_603 = buf_temp_qft_2_1_V_2_fu_390_p3.read();
        buf_temp_qft_2_2_V_reg_573 = grp_quantificat_fu_186_ap_return_10.read();
        buf_temp_qft_2_3_V_reg_578 = grp_quantificat_fu_186_ap_return_11.read();
        buf_temp_qft_3_0_V_2_reg_598 = buf_temp_qft_3_0_V_2_fu_382_p3.read();
        buf_temp_qft_3_1_V_reg_583 = grp_quantificat_fu_186_ap_return_13.read();
        buf_temp_qft_3_2_V_reg_588 = grp_quantificat_fu_186_ap_return_14.read();
        buf_temp_qft_3_3_V_reg_593 = grp_quantificat_fu_186_ap_return_15.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        c_1_reg_639 = c_1_fu_460_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        c_reg_523 = c_fu_248_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        r_2_reg_621 = r_2_fu_420_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        r_reg_497 = r_fu_203_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_i_fu_197_p2.read(), ap_const_lv1_0))) {
        tmp_125_cast_reg_507 = tmp_125_cast_fu_229_p1.read();
        tmp_i_reg_502 = tmp_i_fu_213_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i1_fu_414_p2.read()))) {
        tmp_127_cast_reg_626 = tmp_127_cast_fu_434_p1.read();
        tmp_1_i1_reg_631 = tmp_1_i1_fu_442_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i1_fu_454_p2.read()))) {
        tmp_4_i_reg_649 = tmp_4_i_fu_480_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_242_p2.read()))) {
        tmp_97_reg_533 = tmp_97_fu_268_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_i_fu_197_p2.read(), ap_const_lv1_1))) {
        tmp_reg_512 = tmp_fu_233_p2.read();
    }
}

void add_watermark::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void add_watermark::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void add_watermark::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void add_watermark::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void add_watermark::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void add_watermark::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void add_watermark::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void add_watermark::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void add_watermark::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void add_watermark::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void add_watermark::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void add_watermark::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void add_watermark::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void add_watermark::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_i1_fu_414_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void add_watermark::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void add_watermark::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_i1_fu_414_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void add_watermark::thread_buf_2d_in_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buf_2d_in_address0 =  (sc_lv<4>) (tmp_129_cast_fu_278_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        buf_2d_in_address0 = grp_dct_step_fu_191_src_address0.read();
    } else {
        buf_2d_in_address0 = "XXXX";
    }
}

void add_watermark::thread_buf_2d_in_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buf_2d_in_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        buf_2d_in_ce0 = grp_dct_step_fu_191_src_ce0.read();
    } else {
        buf_2d_in_ce0 = ap_const_logic_0;
    }
}

void add_watermark::thread_buf_2d_in_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        buf_2d_in_ce1 = grp_dct_step_fu_191_src_ce1.read();
    } else {
        buf_2d_in_ce1 = ap_const_logic_0;
    }
}

void add_watermark::thread_buf_2d_in_d0() {
    buf_2d_in_d0 = esl_zext<16,8>(indata_q0.read());
}

void add_watermark::thread_buf_2d_in_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buf_2d_in_we0 = ap_const_logic_1;
    } else {
        buf_2d_in_we0 = ap_const_logic_0;
    }
}

void add_watermark::thread_buf_2d_out_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        buf_2d_out_address0 =  (sc_lv<4>) (tmp_130_cast_fu_475_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        buf_2d_out_address0 = grp_integer_idct_fu_165_out_r_address0.read();
    } else {
        buf_2d_out_address0 = "XXXX";
    }
}

void add_watermark::thread_buf_2d_out_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        buf_2d_out_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        buf_2d_out_ce0 = grp_integer_idct_fu_165_out_r_ce0.read();
    } else {
        buf_2d_out_ce0 = ap_const_logic_0;
    }
}

void add_watermark::thread_buf_2d_out_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        buf_2d_out_ce1 = grp_integer_idct_fu_165_out_r_ce1.read();
    } else {
        buf_2d_out_ce1 = ap_const_logic_0;
    }
}

void add_watermark::thread_buf_2d_out_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        buf_2d_out_we0 = grp_integer_idct_fu_165_out_r_we0.read();
    } else {
        buf_2d_out_we0 = ap_const_logic_0;
    }
}

void add_watermark::thread_buf_2d_out_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        buf_2d_out_we1 = grp_integer_idct_fu_165_out_r_we1.read();
    } else {
        buf_2d_out_we1 = ap_const_logic_0;
    }
}

void add_watermark::thread_buf_temp_dct_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        buf_temp_dct_address0 = grp_dct_step_fu_191_dst_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        buf_temp_dct_address0 = grp_quantificat_fu_186_qsrc_address0.read();
    } else {
        buf_temp_dct_address0 = "XXXX";
    }
}

void add_watermark::thread_buf_temp_dct_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        buf_temp_dct_address1 = grp_dct_step_fu_191_dst_address1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        buf_temp_dct_address1 = grp_quantificat_fu_186_qsrc_address1.read();
    } else {
        buf_temp_dct_address1 = "XXXX";
    }
}

void add_watermark::thread_buf_temp_dct_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        buf_temp_dct_ce0 = grp_dct_step_fu_191_dst_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        buf_temp_dct_ce0 = grp_quantificat_fu_186_qsrc_ce0.read();
    } else {
        buf_temp_dct_ce0 = ap_const_logic_0;
    }
}

void add_watermark::thread_buf_temp_dct_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        buf_temp_dct_ce1 = grp_dct_step_fu_191_dst_ce1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        buf_temp_dct_ce1 = grp_quantificat_fu_186_qsrc_ce1.read();
    } else {
        buf_temp_dct_ce1 = ap_const_logic_0;
    }
}

void add_watermark::thread_buf_temp_dct_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        buf_temp_dct_we0 = grp_dct_step_fu_191_dst_we0.read();
    } else {
        buf_temp_dct_we0 = ap_const_logic_0;
    }
}

void add_watermark::thread_buf_temp_dct_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        buf_temp_dct_we1 = grp_dct_step_fu_191_dst_we1.read();
    } else {
        buf_temp_dct_we1 = ap_const_logic_0;
    }
}

void add_watermark::thread_buf_temp_qft_0_3_V_1_fu_376_p2() {
    buf_temp_qft_0_3_V_1_fu_376_p2 = (!grp_quantificat_fu_186_ap_return_3.read().is_01() || !ap_const_lv20_A.is_01())? sc_lv<20>(): (sc_biguint<20>(grp_quantificat_fu_186_ap_return_3.read()) + sc_biguint<20>(ap_const_lv20_A));
}

void add_watermark::thread_buf_temp_qft_0_3_V_2_fu_406_p3() {
    buf_temp_qft_0_3_V_2_fu_406_p3 = (!tmp_reg_512.read()[0].is_01())? sc_lv<20>(): ((tmp_reg_512.read()[0].to_bool())? grp_quantificat_fu_186_ap_return_3.read(): buf_temp_qft_0_3_V_1_fu_376_p2.read());
}

void add_watermark::thread_buf_temp_qft_1_2_V_1_fu_364_p2() {
    buf_temp_qft_1_2_V_1_fu_364_p2 = (!grp_quantificat_fu_186_ap_return_6.read().is_01() || !ap_const_lv20_A.is_01())? sc_lv<20>(): (sc_biguint<20>(grp_quantificat_fu_186_ap_return_6.read()) + sc_biguint<20>(ap_const_lv20_A));
}

void add_watermark::thread_buf_temp_qft_1_2_V_2_fu_398_p3() {
    buf_temp_qft_1_2_V_2_fu_398_p3 = (!tmp_reg_512.read()[0].is_01())? sc_lv<20>(): ((tmp_reg_512.read()[0].to_bool())? buf_temp_qft_1_2_V_1_fu_364_p2.read(): grp_quantificat_fu_186_ap_return_6.read());
}

void add_watermark::thread_buf_temp_qft_2_1_V_1_fu_370_p2() {
    buf_temp_qft_2_1_V_1_fu_370_p2 = (!grp_quantificat_fu_186_ap_return_9.read().is_01() || !ap_const_lv20_A.is_01())? sc_lv<20>(): (sc_biguint<20>(grp_quantificat_fu_186_ap_return_9.read()) + sc_biguint<20>(ap_const_lv20_A));
}

void add_watermark::thread_buf_temp_qft_2_1_V_2_fu_390_p3() {
    buf_temp_qft_2_1_V_2_fu_390_p3 = (!tmp_reg_512.read()[0].is_01())? sc_lv<20>(): ((tmp_reg_512.read()[0].to_bool())? grp_quantificat_fu_186_ap_return_9.read(): buf_temp_qft_2_1_V_1_fu_370_p2.read());
}

void add_watermark::thread_buf_temp_qft_3_0_V_1_fu_358_p2() {
    buf_temp_qft_3_0_V_1_fu_358_p2 = (!grp_quantificat_fu_186_ap_return_12.read().is_01() || !ap_const_lv20_A.is_01())? sc_lv<20>(): (sc_biguint<20>(grp_quantificat_fu_186_ap_return_12.read()) + sc_biguint<20>(ap_const_lv20_A));
}

void add_watermark::thread_buf_temp_qft_3_0_V_2_fu_382_p3() {
    buf_temp_qft_3_0_V_2_fu_382_p3 = (!tmp_reg_512.read()[0].is_01())? sc_lv<20>(): ((tmp_reg_512.read()[0].to_bool())? buf_temp_qft_3_0_V_1_fu_358_p2.read(): grp_quantificat_fu_186_ap_return_12.read());
}

void add_watermark::thread_c_1_fu_460_p2() {
    c_1_fu_460_p2 = (!c_i1_reg_154.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(c_i1_reg_154.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void add_watermark::thread_c_fu_248_p2() {
    c_fu_248_p2 = (!c_i_reg_132.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(c_i_reg_132.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void add_watermark::thread_c_i1_cast_fu_450_p1() {
    c_i1_cast_fu_450_p1 = esl_zext<4,3>(c_i1_reg_154.read());
}

void add_watermark::thread_c_i_cast_fu_238_p1() {
    c_i_cast_fu_238_p1 = esl_zext<4,3>(c_i_reg_132.read());
}

void add_watermark::thread_exitcond1_i1_fu_414_p2() {
    exitcond1_i1_fu_414_p2 = (!r_i1_reg_143.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(r_i1_reg_143.read() == ap_const_lv3_4);
}

void add_watermark::thread_exitcond1_i_fu_197_p2() {
    exitcond1_i_fu_197_p2 = (!r_i_reg_121.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(r_i_reg_121.read() == ap_const_lv3_4);
}

void add_watermark::thread_exitcond_i1_fu_454_p2() {
    exitcond_i1_fu_454_p2 = (!c_i1_reg_154.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(c_i1_reg_154.read() == ap_const_lv3_4);
}

void add_watermark::thread_exitcond_i_fu_242_p2() {
    exitcond_i_fu_242_p2 = (!c_i_reg_132.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(c_i_reg_132.read() == ap_const_lv3_4);
}

void add_watermark::thread_grp_dct_step_fu_191_ap_start() {
    grp_dct_step_fu_191_ap_start = ap_reg_grp_dct_step_fu_191_ap_start.read();
}

void add_watermark::thread_grp_dct_step_fu_191_src_q0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        grp_dct_step_fu_191_src_q0 = temp_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        grp_dct_step_fu_191_src_q0 = buf_2d_in_q0.read();
    } else {
        grp_dct_step_fu_191_src_q0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void add_watermark::thread_grp_dct_step_fu_191_src_q1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        grp_dct_step_fu_191_src_q1 = temp_q1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        grp_dct_step_fu_191_src_q1 = buf_2d_in_q1.read();
    } else {
        grp_dct_step_fu_191_src_q1 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void add_watermark::thread_grp_integer_idct_fu_165_ap_start() {
    grp_integer_idct_fu_165_ap_start = ap_reg_grp_integer_idct_fu_165_ap_start.read();
}

void add_watermark::thread_grp_quantificat_fu_186_ap_start() {
    grp_quantificat_fu_186_ap_start = ap_reg_grp_quantificat_fu_186_ap_start.read();
}

void add_watermark::thread_indata_address0() {
    indata_address0 =  (sc_lv<4>) (tmp_i_9_fu_259_p1.read());
}

void add_watermark::thread_indata_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        indata_ce0 = ap_const_logic_1;
    } else {
        indata_ce0 = ap_const_logic_0;
    }
}

void add_watermark::thread_outdata_address0() {
    outdata_address0 =  (sc_lv<4>) (tmp_5_i_fu_485_p1.read());
}

void add_watermark::thread_outdata_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        outdata_ce0 = ap_const_logic_1;
    } else {
        outdata_ce0 = ap_const_logic_0;
    }
}

void add_watermark::thread_outdata_d0() {
    outdata_d0 = buf_2d_out_q0.read();
}

void add_watermark::thread_outdata_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        outdata_we0 = ap_const_logic_1;
    } else {
        outdata_we0 = ap_const_logic_0;
    }
}

void add_watermark::thread_r_2_fu_420_p2() {
    r_2_fu_420_p2 = (!r_i1_reg_143.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(r_i1_reg_143.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void add_watermark::thread_r_fu_203_p2() {
    r_fu_203_p2 = (!r_i_reg_121.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(r_i_reg_121.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void add_watermark::thread_temp_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        temp_address0 = grp_dct_step_fu_191_dst_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        temp_address0 = grp_dct_step_fu_191_src_address0.read();
    } else {
        temp_address0 = "XXXX";
    }
}

void add_watermark::thread_temp_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        temp_address1 = grp_dct_step_fu_191_dst_address1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        temp_address1 = grp_dct_step_fu_191_src_address1.read();
    } else {
        temp_address1 = "XXXX";
    }
}

void add_watermark::thread_temp_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        temp_ce0 = grp_dct_step_fu_191_dst_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        temp_ce0 = grp_dct_step_fu_191_src_ce0.read();
    } else {
        temp_ce0 = ap_const_logic_0;
    }
}

void add_watermark::thread_temp_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        temp_ce1 = grp_dct_step_fu_191_dst_ce1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        temp_ce1 = grp_dct_step_fu_191_src_ce1.read();
    } else {
        temp_ce1 = ap_const_logic_0;
    }
}

void add_watermark::thread_temp_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        temp_we0 = grp_dct_step_fu_191_dst_we0.read();
    } else {
        temp_we0 = ap_const_logic_0;
    }
}

void add_watermark::thread_temp_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        temp_we1 = grp_dct_step_fu_191_dst_we1.read();
    } else {
        temp_we1 = ap_const_logic_0;
    }
}

void add_watermark::thread_tmp_115_fu_209_p1() {
    tmp_115_fu_209_p1 = r_i_reg_121.read().range(2-1, 0);
}

void add_watermark::thread_tmp_116_fu_438_p1() {
    tmp_116_fu_438_p1 = r_i1_reg_143.read().range(2-1, 0);
}

void add_watermark::thread_tmp_125_cast_fu_229_p1() {
    tmp_125_cast_fu_229_p1 = esl_zext<6,5>(tmp_s_fu_221_p3.read());
}

void add_watermark::thread_tmp_127_cast_fu_434_p1() {
    tmp_127_cast_fu_434_p1 = esl_zext<6,5>(tmp_96_fu_426_p3.read());
}

void add_watermark::thread_tmp_129_cast_fu_278_p1() {
    tmp_129_cast_fu_278_p1 = esl_zext<64,6>(tmp_97_reg_533.read());
}

void add_watermark::thread_tmp_130_cast_fu_475_p1() {
    tmp_130_cast_fu_475_p1 = esl_zext<64,6>(tmp_98_fu_470_p2.read());
}

void add_watermark::thread_tmp_1_i1_fu_442_p3() {
    tmp_1_i1_fu_442_p3 = esl_concat<2,2>(tmp_116_fu_438_p1.read(), ap_const_lv2_0);
}

void add_watermark::thread_tmp_2_i_cast_fu_264_p1() {
    tmp_2_i_cast_fu_264_p1 = esl_zext<6,3>(c_i_reg_132.read());
}

void add_watermark::thread_tmp_3_i1_cast_fu_466_p1() {
    tmp_3_i1_cast_fu_466_p1 = esl_zext<6,3>(c_i1_reg_154.read());
}

void add_watermark::thread_tmp_4_i_fu_480_p2() {
    tmp_4_i_fu_480_p2 = (!c_i1_cast_fu_450_p1.read().is_01() || !tmp_1_i1_reg_631.read().is_01())? sc_lv<4>(): (sc_biguint<4>(c_i1_cast_fu_450_p1.read()) + sc_biguint<4>(tmp_1_i1_reg_631.read()));
}

void add_watermark::thread_tmp_5_i_fu_485_p1() {
    tmp_5_i_fu_485_p1 = esl_zext<64,4>(tmp_4_i_reg_649.read());
}

void add_watermark::thread_tmp_96_fu_426_p3() {
    tmp_96_fu_426_p3 = esl_concat<3,2>(r_i1_reg_143.read(), ap_const_lv2_0);
}

void add_watermark::thread_tmp_97_fu_268_p2() {
    tmp_97_fu_268_p2 = (!tmp_125_cast_reg_507.read().is_01() || !tmp_2_i_cast_fu_264_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_125_cast_reg_507.read()) + sc_biguint<6>(tmp_2_i_cast_fu_264_p1.read()));
}

void add_watermark::thread_tmp_98_fu_470_p2() {
    tmp_98_fu_470_p2 = (!tmp_127_cast_reg_626.read().is_01() || !tmp_3_i1_cast_fu_466_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_127_cast_reg_626.read()) + sc_biguint<6>(tmp_3_i1_cast_fu_466_p1.read()));
}

void add_watermark::thread_tmp_9_i_fu_254_p2() {
    tmp_9_i_fu_254_p2 = (!c_i_cast_fu_238_p1.read().is_01() || !tmp_i_reg_502.read().is_01())? sc_lv<4>(): (sc_biguint<4>(c_i_cast_fu_238_p1.read()) + sc_biguint<4>(tmp_i_reg_502.read()));
}

void add_watermark::thread_tmp_fu_233_p2() {
    tmp_fu_233_p2 = (!mark.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(mark.read() == ap_const_lv8_0);
}

void add_watermark::thread_tmp_i_9_fu_259_p1() {
    tmp_i_9_fu_259_p1 = esl_zext<64,4>(tmp_9_i_fu_254_p2.read());
}

void add_watermark::thread_tmp_i_fu_213_p3() {
    tmp_i_fu_213_p3 = esl_concat<2,2>(tmp_115_fu_209_p1.read(), ap_const_lv2_0);
}

void add_watermark::thread_tmp_s_fu_221_p3() {
    tmp_s_fu_221_p3 = esl_concat<3,2>(r_i_reg_121.read(), ap_const_lv2_0);
}

void add_watermark::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_i_fu_197_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_242_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(grp_dct_step_fu_191_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(grp_dct_step_fu_191_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(grp_quantificat_fu_186_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(grp_integer_idct_fu_165_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_i1_fu_414_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i1_fu_454_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<13>) ("XXXXXXXXXXXXX");
            break;
    }
}

}

