// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "img_proc.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic img_proc::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic img_proc::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<21> img_proc::ap_ST_fsm_state1 = "1";
const sc_lv<21> img_proc::ap_ST_fsm_state2 = "10";
const sc_lv<21> img_proc::ap_ST_fsm_state3 = "100";
const sc_lv<21> img_proc::ap_ST_fsm_state4 = "1000";
const sc_lv<21> img_proc::ap_ST_fsm_state5 = "10000";
const sc_lv<21> img_proc::ap_ST_fsm_state6 = "100000";
const sc_lv<21> img_proc::ap_ST_fsm_state7 = "1000000";
const sc_lv<21> img_proc::ap_ST_fsm_state8 = "10000000";
const sc_lv<21> img_proc::ap_ST_fsm_state9 = "100000000";
const sc_lv<21> img_proc::ap_ST_fsm_state10 = "1000000000";
const sc_lv<21> img_proc::ap_ST_fsm_state11 = "10000000000";
const sc_lv<21> img_proc::ap_ST_fsm_state12 = "100000000000";
const sc_lv<21> img_proc::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<21> img_proc::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<21> img_proc::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<21> img_proc::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<21> img_proc::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<21> img_proc::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<21> img_proc::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<21> img_proc::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<21> img_proc::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<32> img_proc::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> img_proc::ap_const_lv32_1 = "1";
const sc_lv<1> img_proc::ap_const_lv1_0 = "0";
const sc_lv<32> img_proc::ap_const_lv32_2 = "10";
const sc_lv<32> img_proc::ap_const_lv32_3 = "11";
const sc_lv<32> img_proc::ap_const_lv32_4 = "100";
const sc_lv<32> img_proc::ap_const_lv32_5 = "101";
const sc_lv<32> img_proc::ap_const_lv32_6 = "110";
const sc_lv<32> img_proc::ap_const_lv32_7 = "111";
const sc_lv<32> img_proc::ap_const_lv32_8 = "1000";
const sc_lv<16> img_proc::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> img_proc::ap_const_lv32_14 = "10100";
const sc_lv<32> img_proc::ap_const_lv32_A = "1010";
const sc_lv<32> img_proc::ap_const_lv32_B = "1011";
const sc_lv<64> img_proc::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> img_proc::ap_const_lv64_1 = "1";
const sc_lv<64> img_proc::ap_const_lv64_2 = "10";
const sc_lv<64> img_proc::ap_const_lv64_3 = "11";
const sc_lv<64> img_proc::ap_const_lv64_4 = "100";
const sc_lv<64> img_proc::ap_const_lv64_5 = "101";
const sc_lv<64> img_proc::ap_const_lv64_6 = "110";
const sc_lv<64> img_proc::ap_const_lv64_7 = "111";
const sc_lv<64> img_proc::ap_const_lv64_8 = "1000";
const sc_lv<64> img_proc::ap_const_lv64_9 = "1001";
const sc_lv<64> img_proc::ap_const_lv64_A = "1010";
const sc_lv<64> img_proc::ap_const_lv64_B = "1011";
const sc_lv<64> img_proc::ap_const_lv64_C = "1100";
const sc_lv<64> img_proc::ap_const_lv64_D = "1101";
const sc_lv<64> img_proc::ap_const_lv64_E = "1110";
const sc_lv<64> img_proc::ap_const_lv64_F = "1111";
const sc_lv<32> img_proc::ap_const_lv32_D = "1101";
const sc_lv<32> img_proc::ap_const_lv32_E = "1110";
const sc_lv<32> img_proc::ap_const_lv32_F = "1111";
const sc_lv<32> img_proc::ap_const_lv32_10 = "10000";
const sc_lv<32> img_proc::ap_const_lv32_11 = "10001";
const sc_lv<32> img_proc::ap_const_lv32_12 = "10010";
const sc_lv<32> img_proc::ap_const_lv32_13 = "10011";
const sc_lv<32> img_proc::ap_const_lv32_9 = "1001";
const sc_lv<32> img_proc::ap_const_lv32_C = "1100";
const sc_lv<16> img_proc::ap_const_lv16_9C40 = "1001110001000000";
const sc_lv<16> img_proc::ap_const_lv16_1 = "1";
const sc_lv<16> img_proc::ap_const_lv16_C8 = "11001000";
const sc_lv<4> img_proc::ap_const_lv4_0 = "0000";
const sc_lv<2> img_proc::ap_const_lv2_0 = "00";
const sc_lv<22> img_proc::ap_const_lv22_2 = "10";
const sc_lv<22> img_proc::ap_const_lv22_3 = "11";
const sc_lv<22> img_proc::ap_const_lv22_320 = "1100100000";
const sc_lv<22> img_proc::ap_const_lv22_321 = "1100100001";
const sc_lv<22> img_proc::ap_const_lv22_322 = "1100100010";
const sc_lv<22> img_proc::ap_const_lv22_323 = "1100100011";
const sc_lv<22> img_proc::ap_const_lv22_640 = "11001000000";
const sc_lv<22> img_proc::ap_const_lv22_641 = "11001000001";
const sc_lv<22> img_proc::ap_const_lv22_642 = "11001000010";
const sc_lv<22> img_proc::ap_const_lv22_643 = "11001000011";
const sc_lv<22> img_proc::ap_const_lv22_960 = "100101100000";
const sc_lv<22> img_proc::ap_const_lv22_961 = "100101100001";
const sc_lv<22> img_proc::ap_const_lv22_962 = "100101100010";
const sc_lv<22> img_proc::ap_const_lv22_963 = "100101100011";
const sc_lv<1> img_proc::ap_const_lv1_1 = "1";
const bool img_proc::ap_const_boolean_1 = true;

img_proc::img_proc(sc_module_name name) : sc_module(name), mVcdFile(0) {
    indata_U = new add_watermark_bufg8j("indata_U");
    indata_U->clk(ap_clk);
    indata_U->reset(ap_rst);
    indata_U->address0(indata_address0);
    indata_U->ce0(indata_ce0);
    indata_U->we0(indata_we0);
    indata_U->d0(img_q0);
    indata_U->q0(indata_q0);
    indata_U->address1(indata_address1);
    indata_U->ce1(indata_ce1);
    indata_U->we1(indata_we1);
    indata_U->d1(img_q1);
    outdata_U = new img_proc_outdata("outdata_U");
    outdata_U->clk(ap_clk);
    outdata_U->reset(ap_rst);
    outdata_U->address0(outdata_address0);
    outdata_U->ce0(outdata_ce0);
    outdata_U->we0(outdata_we0);
    outdata_U->d0(grp_add_watermark_fu_682_outdata_d0);
    outdata_U->q0(outdata_q0);
    outdata_U->address1(outdata_address1);
    outdata_U->ce1(outdata_ce1);
    outdata_U->q1(outdata_q1);
    grp_add_watermark_fu_682 = new add_watermark("grp_add_watermark_fu_682");
    grp_add_watermark_fu_682->ap_clk(ap_clk);
    grp_add_watermark_fu_682->ap_rst(ap_rst);
    grp_add_watermark_fu_682->ap_start(grp_add_watermark_fu_682_ap_start);
    grp_add_watermark_fu_682->ap_done(grp_add_watermark_fu_682_ap_done);
    grp_add_watermark_fu_682->ap_idle(grp_add_watermark_fu_682_ap_idle);
    grp_add_watermark_fu_682->ap_ready(grp_add_watermark_fu_682_ap_ready);
    grp_add_watermark_fu_682->indata_address0(grp_add_watermark_fu_682_indata_address0);
    grp_add_watermark_fu_682->indata_ce0(grp_add_watermark_fu_682_indata_ce0);
    grp_add_watermark_fu_682->indata_q0(indata_q0);
    grp_add_watermark_fu_682->mark(mark_load_reg_1226);
    grp_add_watermark_fu_682->outdata_address0(grp_add_watermark_fu_682_outdata_address0);
    grp_add_watermark_fu_682->outdata_ce0(grp_add_watermark_fu_682_outdata_ce0);
    grp_add_watermark_fu_682->outdata_we0(grp_add_watermark_fu_682_outdata_we0);
    grp_add_watermark_fu_682->outdata_d0(grp_add_watermark_fu_682_outdata_d0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_693_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_693_p2 );

    SC_METHOD(thread_base_idx_cast_fu_769_p1);
    sensitive << ( base_idx_fu_763_p2 );

    SC_METHOD(thread_base_idx_fu_763_p2);
    sensitive << ( tmp_5_cast_cast_fu_759_p1 );
    sensitive << ( tmp_4_cast_fu_743_p1 );

    SC_METHOD(thread_grp_add_watermark_fu_682_ap_start);
    sensitive << ( ap_reg_grp_add_watermark_fu_682_ap_start );

    SC_METHOD(thread_idx_urem_fu_717_p3);
    sensitive << ( next_urem_fu_705_p2 );
    sensitive << ( tmp_49_fu_711_p2 );

    SC_METHOD(thread_img_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_6_fu_773_p1 );
    sensitive << ( tmp_10_fu_803_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_14_fu_831_p1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_18_fu_859_p1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_22_fu_887_p1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_26_fu_915_p1 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_30_fu_943_p1 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_34_fu_971_p1 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_img_address1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_8_fu_784_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_12_fu_817_p1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_16_fu_845_p1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_20_fu_873_p1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_24_fu_901_p1 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_28_fu_929_p1 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_32_fu_957_p1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_36_fu_985_p1 );

    SC_METHOD(thread_img_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_img_ce1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_indata_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( grp_add_watermark_fu_682_indata_address0 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_indata_address1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_indata_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( grp_add_watermark_fu_682_indata_ce0 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_indata_ce1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_indata_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_indata_we1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_mark_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_37_fu_789_p1 );

    SC_METHOD(thread_mark_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_mark_idx_1_fu_699_p2);
    sensitive << ( mark_idx_reg_660 );

    SC_METHOD(thread_mark_idx_cast_fu_689_p1);
    sensitive << ( mark_idx_reg_660 );

    SC_METHOD(thread_next_urem_fu_705_p2);
    sensitive << ( tmp_50_reg_671 );

    SC_METHOD(thread_out_r_address0);
    sensitive << ( tmp_6_reg_1181 );
    sensitive << ( tmp_10_reg_1206 );
    sensitive << ( tmp_14_reg_1231 );
    sensitive << ( tmp_18_reg_1251 );
    sensitive << ( tmp_22_reg_1271 );
    sensitive << ( tmp_26_reg_1291 );
    sensitive << ( tmp_30_reg_1311 );
    sensitive << ( tmp_34_reg_1331 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_out_r_address1);
    sensitive << ( tmp_8_reg_1191 );
    sensitive << ( tmp_12_reg_1216 );
    sensitive << ( tmp_16_reg_1241 );
    sensitive << ( tmp_20_reg_1261 );
    sensitive << ( tmp_24_reg_1281 );
    sensitive << ( tmp_28_reg_1301 );
    sensitive << ( tmp_32_reg_1321 );
    sensitive << ( tmp_36_reg_1341 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_out_r_ce0);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_out_r_ce1);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_out_r_d0);
    sensitive << ( outdata_q0 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_out_r_d1);
    sensitive << ( outdata_q1 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_out_r_we0);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_out_r_we1);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_outdata_address0);
    sensitive << ( grp_add_watermark_fu_682_outdata_address0 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_outdata_address1);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_outdata_ce0);
    sensitive << ( grp_add_watermark_fu_682_outdata_ce0 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_outdata_ce1);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_outdata_we0);
    sensitive << ( grp_add_watermark_fu_682_outdata_we0 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_tmp_10_fu_803_p1);
    sensitive << ( tmp_9_cast_fu_799_p1 );

    SC_METHOD(thread_tmp_11_cast_fu_813_p1);
    sensitive << ( tmp_11_fu_808_p2 );

    SC_METHOD(thread_tmp_11_fu_808_p2);
    sensitive << ( base_idx_reg_1163 );

    SC_METHOD(thread_tmp_12_fu_817_p1);
    sensitive << ( tmp_11_cast_fu_813_p1 );

    SC_METHOD(thread_tmp_13_cast_fu_827_p1);
    sensitive << ( tmp_13_fu_822_p2 );

    SC_METHOD(thread_tmp_13_fu_822_p2);
    sensitive << ( base_idx_reg_1163 );

    SC_METHOD(thread_tmp_14_fu_831_p1);
    sensitive << ( tmp_13_cast_fu_827_p1 );

    SC_METHOD(thread_tmp_15_cast_fu_841_p1);
    sensitive << ( tmp_15_fu_836_p2 );

    SC_METHOD(thread_tmp_15_fu_836_p2);
    sensitive << ( base_idx_reg_1163 );

    SC_METHOD(thread_tmp_16_fu_845_p1);
    sensitive << ( tmp_15_cast_fu_841_p1 );

    SC_METHOD(thread_tmp_17_cast_fu_855_p1);
    sensitive << ( tmp_17_fu_850_p2 );

    SC_METHOD(thread_tmp_17_fu_850_p2);
    sensitive << ( base_idx_reg_1163 );

    SC_METHOD(thread_tmp_18_fu_859_p1);
    sensitive << ( tmp_17_cast_fu_855_p1 );

    SC_METHOD(thread_tmp_19_cast_fu_869_p1);
    sensitive << ( tmp_19_fu_864_p2 );

    SC_METHOD(thread_tmp_19_fu_864_p2);
    sensitive << ( base_idx_reg_1163 );

    SC_METHOD(thread_tmp_20_fu_873_p1);
    sensitive << ( tmp_19_cast_fu_869_p1 );

    SC_METHOD(thread_tmp_21_cast_fu_883_p1);
    sensitive << ( tmp_21_fu_878_p2 );

    SC_METHOD(thread_tmp_21_fu_878_p2);
    sensitive << ( base_idx_reg_1163 );

    SC_METHOD(thread_tmp_22_fu_887_p1);
    sensitive << ( tmp_21_cast_fu_883_p1 );

    SC_METHOD(thread_tmp_23_cast_fu_897_p1);
    sensitive << ( tmp_23_fu_892_p2 );

    SC_METHOD(thread_tmp_23_fu_892_p2);
    sensitive << ( base_idx_reg_1163 );

    SC_METHOD(thread_tmp_24_fu_901_p1);
    sensitive << ( tmp_23_cast_fu_897_p1 );

    SC_METHOD(thread_tmp_25_cast_fu_911_p1);
    sensitive << ( tmp_25_fu_906_p2 );

    SC_METHOD(thread_tmp_25_fu_906_p2);
    sensitive << ( base_idx_reg_1163 );

    SC_METHOD(thread_tmp_26_fu_915_p1);
    sensitive << ( tmp_25_cast_fu_911_p1 );

    SC_METHOD(thread_tmp_27_cast_fu_925_p1);
    sensitive << ( tmp_27_fu_920_p2 );

    SC_METHOD(thread_tmp_27_fu_920_p2);
    sensitive << ( base_idx_reg_1163 );

    SC_METHOD(thread_tmp_28_fu_929_p1);
    sensitive << ( tmp_27_cast_fu_925_p1 );

    SC_METHOD(thread_tmp_29_cast_fu_939_p1);
    sensitive << ( tmp_29_fu_934_p2 );

    SC_METHOD(thread_tmp_29_fu_934_p2);
    sensitive << ( base_idx_reg_1163 );

    SC_METHOD(thread_tmp_2_cast_fu_725_p1);
    sensitive << ( tmp_50_reg_671 );

    SC_METHOD(thread_tmp_30_fu_943_p1);
    sensitive << ( tmp_29_cast_fu_939_p1 );

    SC_METHOD(thread_tmp_31_cast_fu_953_p1);
    sensitive << ( tmp_31_fu_948_p2 );

    SC_METHOD(thread_tmp_31_fu_948_p2);
    sensitive << ( base_idx_reg_1163 );

    SC_METHOD(thread_tmp_32_fu_957_p1);
    sensitive << ( tmp_31_cast_fu_953_p1 );

    SC_METHOD(thread_tmp_33_cast_fu_967_p1);
    sensitive << ( tmp_33_fu_962_p2 );

    SC_METHOD(thread_tmp_33_fu_962_p2);
    sensitive << ( base_idx_reg_1163 );

    SC_METHOD(thread_tmp_34_fu_971_p1);
    sensitive << ( tmp_33_cast_fu_967_p1 );

    SC_METHOD(thread_tmp_35_cast_fu_981_p1);
    sensitive << ( tmp_35_fu_976_p2 );

    SC_METHOD(thread_tmp_35_fu_976_p2);
    sensitive << ( base_idx_reg_1163 );

    SC_METHOD(thread_tmp_36_fu_985_p1);
    sensitive << ( tmp_35_cast_fu_981_p1 );

    SC_METHOD(thread_tmp_37_fu_789_p1);
    sensitive << ( mark_idx_reg_660 );

    SC_METHOD(thread_tmp_38_fu_735_p3);
    sensitive << ( tmp_s_fu_729_p2 );

    SC_METHOD(thread_tmp_49_fu_711_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_693_p2 );
    sensitive << ( next_urem_fu_705_p2 );

    SC_METHOD(thread_tmp_4_cast_fu_743_p1);
    sensitive << ( tmp_38_fu_735_p3 );

    SC_METHOD(thread_tmp_51_fu_747_p1);
    sensitive << ( tmp_50_reg_671 );

    SC_METHOD(thread_tmp_5_cast_cast_fu_759_p1);
    sensitive << ( tmp_5_fu_751_p3 );

    SC_METHOD(thread_tmp_5_fu_751_p3);
    sensitive << ( tmp_51_fu_747_p1 );

    SC_METHOD(thread_tmp_6_fu_773_p1);
    sensitive << ( base_idx_cast_fu_769_p1 );

    SC_METHOD(thread_tmp_7_fu_778_p2);
    sensitive << ( base_idx_cast_fu_769_p1 );

    SC_METHOD(thread_tmp_8_fu_784_p1);
    sensitive << ( tmp_7_fu_778_p2 );

    SC_METHOD(thread_tmp_9_cast_fu_799_p1);
    sensitive << ( tmp_9_fu_794_p2 );

    SC_METHOD(thread_tmp_9_fu_794_p2);
    sensitive << ( base_idx_reg_1163 );

    SC_METHOD(thread_tmp_fu_693_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( mark_idx_reg_660 );

    SC_METHOD(thread_tmp_s_fu_729_p2);
    sensitive << ( mark_idx_cast_fu_689_p1 );
    sensitive << ( tmp_2_cast_fu_725_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_693_p2 );
    sensitive << ( grp_add_watermark_fu_682_ap_done );
    sensitive << ( ap_CS_fsm_state12 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000000000000000000001";
    ap_reg_grp_add_watermark_fu_682_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "img_proc_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, img_address0, "(port)img_address0");
    sc_trace(mVcdFile, img_ce0, "(port)img_ce0");
    sc_trace(mVcdFile, img_q0, "(port)img_q0");
    sc_trace(mVcdFile, img_address1, "(port)img_address1");
    sc_trace(mVcdFile, img_ce1, "(port)img_ce1");
    sc_trace(mVcdFile, img_q1, "(port)img_q1");
    sc_trace(mVcdFile, mark_address0, "(port)mark_address0");
    sc_trace(mVcdFile, mark_ce0, "(port)mark_ce0");
    sc_trace(mVcdFile, mark_q0, "(port)mark_q0");
    sc_trace(mVcdFile, out_r_address0, "(port)out_r_address0");
    sc_trace(mVcdFile, out_r_ce0, "(port)out_r_ce0");
    sc_trace(mVcdFile, out_r_we0, "(port)out_r_we0");
    sc_trace(mVcdFile, out_r_d0, "(port)out_r_d0");
    sc_trace(mVcdFile, out_r_address1, "(port)out_r_address1");
    sc_trace(mVcdFile, out_r_ce1, "(port)out_r_ce1");
    sc_trace(mVcdFile, out_r_we1, "(port)out_r_we1");
    sc_trace(mVcdFile, out_r_d1, "(port)out_r_d1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, mark_idx_1_fu_699_p2, "mark_idx_1_fu_699_p2");
    sc_trace(mVcdFile, mark_idx_1_reg_1153, "mark_idx_1_reg_1153");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, idx_urem_fu_717_p3, "idx_urem_fu_717_p3");
    sc_trace(mVcdFile, idx_urem_reg_1158, "idx_urem_reg_1158");
    sc_trace(mVcdFile, tmp_fu_693_p2, "tmp_fu_693_p2");
    sc_trace(mVcdFile, base_idx_fu_763_p2, "base_idx_fu_763_p2");
    sc_trace(mVcdFile, base_idx_reg_1163, "base_idx_reg_1163");
    sc_trace(mVcdFile, tmp_6_fu_773_p1, "tmp_6_fu_773_p1");
    sc_trace(mVcdFile, tmp_6_reg_1181, "tmp_6_reg_1181");
    sc_trace(mVcdFile, tmp_8_fu_784_p1, "tmp_8_fu_784_p1");
    sc_trace(mVcdFile, tmp_8_reg_1191, "tmp_8_reg_1191");
    sc_trace(mVcdFile, tmp_10_fu_803_p1, "tmp_10_fu_803_p1");
    sc_trace(mVcdFile, tmp_10_reg_1206, "tmp_10_reg_1206");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_12_fu_817_p1, "tmp_12_fu_817_p1");
    sc_trace(mVcdFile, tmp_12_reg_1216, "tmp_12_reg_1216");
    sc_trace(mVcdFile, mark_load_reg_1226, "mark_load_reg_1226");
    sc_trace(mVcdFile, tmp_14_fu_831_p1, "tmp_14_fu_831_p1");
    sc_trace(mVcdFile, tmp_14_reg_1231, "tmp_14_reg_1231");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_16_fu_845_p1, "tmp_16_fu_845_p1");
    sc_trace(mVcdFile, tmp_16_reg_1241, "tmp_16_reg_1241");
    sc_trace(mVcdFile, tmp_18_fu_859_p1, "tmp_18_fu_859_p1");
    sc_trace(mVcdFile, tmp_18_reg_1251, "tmp_18_reg_1251");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_20_fu_873_p1, "tmp_20_fu_873_p1");
    sc_trace(mVcdFile, tmp_20_reg_1261, "tmp_20_reg_1261");
    sc_trace(mVcdFile, tmp_22_fu_887_p1, "tmp_22_fu_887_p1");
    sc_trace(mVcdFile, tmp_22_reg_1271, "tmp_22_reg_1271");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_24_fu_901_p1, "tmp_24_fu_901_p1");
    sc_trace(mVcdFile, tmp_24_reg_1281, "tmp_24_reg_1281");
    sc_trace(mVcdFile, tmp_26_fu_915_p1, "tmp_26_fu_915_p1");
    sc_trace(mVcdFile, tmp_26_reg_1291, "tmp_26_reg_1291");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_28_fu_929_p1, "tmp_28_fu_929_p1");
    sc_trace(mVcdFile, tmp_28_reg_1301, "tmp_28_reg_1301");
    sc_trace(mVcdFile, tmp_30_fu_943_p1, "tmp_30_fu_943_p1");
    sc_trace(mVcdFile, tmp_30_reg_1311, "tmp_30_reg_1311");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, tmp_32_fu_957_p1, "tmp_32_fu_957_p1");
    sc_trace(mVcdFile, tmp_32_reg_1321, "tmp_32_reg_1321");
    sc_trace(mVcdFile, tmp_34_fu_971_p1, "tmp_34_fu_971_p1");
    sc_trace(mVcdFile, tmp_34_reg_1331, "tmp_34_reg_1331");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tmp_36_fu_985_p1, "tmp_36_fu_985_p1");
    sc_trace(mVcdFile, tmp_36_reg_1341, "tmp_36_reg_1341");
    sc_trace(mVcdFile, indata_address0, "indata_address0");
    sc_trace(mVcdFile, indata_ce0, "indata_ce0");
    sc_trace(mVcdFile, indata_we0, "indata_we0");
    sc_trace(mVcdFile, indata_q0, "indata_q0");
    sc_trace(mVcdFile, indata_address1, "indata_address1");
    sc_trace(mVcdFile, indata_ce1, "indata_ce1");
    sc_trace(mVcdFile, indata_we1, "indata_we1");
    sc_trace(mVcdFile, outdata_address0, "outdata_address0");
    sc_trace(mVcdFile, outdata_ce0, "outdata_ce0");
    sc_trace(mVcdFile, outdata_we0, "outdata_we0");
    sc_trace(mVcdFile, outdata_q0, "outdata_q0");
    sc_trace(mVcdFile, outdata_address1, "outdata_address1");
    sc_trace(mVcdFile, outdata_ce1, "outdata_ce1");
    sc_trace(mVcdFile, outdata_q1, "outdata_q1");
    sc_trace(mVcdFile, grp_add_watermark_fu_682_ap_start, "grp_add_watermark_fu_682_ap_start");
    sc_trace(mVcdFile, grp_add_watermark_fu_682_ap_done, "grp_add_watermark_fu_682_ap_done");
    sc_trace(mVcdFile, grp_add_watermark_fu_682_ap_idle, "grp_add_watermark_fu_682_ap_idle");
    sc_trace(mVcdFile, grp_add_watermark_fu_682_ap_ready, "grp_add_watermark_fu_682_ap_ready");
    sc_trace(mVcdFile, grp_add_watermark_fu_682_indata_address0, "grp_add_watermark_fu_682_indata_address0");
    sc_trace(mVcdFile, grp_add_watermark_fu_682_indata_ce0, "grp_add_watermark_fu_682_indata_ce0");
    sc_trace(mVcdFile, grp_add_watermark_fu_682_outdata_address0, "grp_add_watermark_fu_682_outdata_address0");
    sc_trace(mVcdFile, grp_add_watermark_fu_682_outdata_ce0, "grp_add_watermark_fu_682_outdata_ce0");
    sc_trace(mVcdFile, grp_add_watermark_fu_682_outdata_we0, "grp_add_watermark_fu_682_outdata_we0");
    sc_trace(mVcdFile, grp_add_watermark_fu_682_outdata_d0, "grp_add_watermark_fu_682_outdata_d0");
    sc_trace(mVcdFile, mark_idx_reg_660, "mark_idx_reg_660");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, tmp_50_reg_671, "tmp_50_reg_671");
    sc_trace(mVcdFile, ap_reg_grp_add_watermark_fu_682_ap_start, "ap_reg_grp_add_watermark_fu_682_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, tmp_37_fu_789_p1, "tmp_37_fu_789_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, next_urem_fu_705_p2, "next_urem_fu_705_p2");
    sc_trace(mVcdFile, tmp_49_fu_711_p2, "tmp_49_fu_711_p2");
    sc_trace(mVcdFile, mark_idx_cast_fu_689_p1, "mark_idx_cast_fu_689_p1");
    sc_trace(mVcdFile, tmp_2_cast_fu_725_p1, "tmp_2_cast_fu_725_p1");
    sc_trace(mVcdFile, tmp_s_fu_729_p2, "tmp_s_fu_729_p2");
    sc_trace(mVcdFile, tmp_38_fu_735_p3, "tmp_38_fu_735_p3");
    sc_trace(mVcdFile, tmp_51_fu_747_p1, "tmp_51_fu_747_p1");
    sc_trace(mVcdFile, tmp_5_fu_751_p3, "tmp_5_fu_751_p3");
    sc_trace(mVcdFile, tmp_5_cast_cast_fu_759_p1, "tmp_5_cast_cast_fu_759_p1");
    sc_trace(mVcdFile, tmp_4_cast_fu_743_p1, "tmp_4_cast_fu_743_p1");
    sc_trace(mVcdFile, base_idx_cast_fu_769_p1, "base_idx_cast_fu_769_p1");
    sc_trace(mVcdFile, tmp_7_fu_778_p2, "tmp_7_fu_778_p2");
    sc_trace(mVcdFile, tmp_9_fu_794_p2, "tmp_9_fu_794_p2");
    sc_trace(mVcdFile, tmp_9_cast_fu_799_p1, "tmp_9_cast_fu_799_p1");
    sc_trace(mVcdFile, tmp_11_fu_808_p2, "tmp_11_fu_808_p2");
    sc_trace(mVcdFile, tmp_11_cast_fu_813_p1, "tmp_11_cast_fu_813_p1");
    sc_trace(mVcdFile, tmp_13_fu_822_p2, "tmp_13_fu_822_p2");
    sc_trace(mVcdFile, tmp_13_cast_fu_827_p1, "tmp_13_cast_fu_827_p1");
    sc_trace(mVcdFile, tmp_15_fu_836_p2, "tmp_15_fu_836_p2");
    sc_trace(mVcdFile, tmp_15_cast_fu_841_p1, "tmp_15_cast_fu_841_p1");
    sc_trace(mVcdFile, tmp_17_fu_850_p2, "tmp_17_fu_850_p2");
    sc_trace(mVcdFile, tmp_17_cast_fu_855_p1, "tmp_17_cast_fu_855_p1");
    sc_trace(mVcdFile, tmp_19_fu_864_p2, "tmp_19_fu_864_p2");
    sc_trace(mVcdFile, tmp_19_cast_fu_869_p1, "tmp_19_cast_fu_869_p1");
    sc_trace(mVcdFile, tmp_21_fu_878_p2, "tmp_21_fu_878_p2");
    sc_trace(mVcdFile, tmp_21_cast_fu_883_p1, "tmp_21_cast_fu_883_p1");
    sc_trace(mVcdFile, tmp_23_fu_892_p2, "tmp_23_fu_892_p2");
    sc_trace(mVcdFile, tmp_23_cast_fu_897_p1, "tmp_23_cast_fu_897_p1");
    sc_trace(mVcdFile, tmp_25_fu_906_p2, "tmp_25_fu_906_p2");
    sc_trace(mVcdFile, tmp_25_cast_fu_911_p1, "tmp_25_cast_fu_911_p1");
    sc_trace(mVcdFile, tmp_27_fu_920_p2, "tmp_27_fu_920_p2");
    sc_trace(mVcdFile, tmp_27_cast_fu_925_p1, "tmp_27_cast_fu_925_p1");
    sc_trace(mVcdFile, tmp_29_fu_934_p2, "tmp_29_fu_934_p2");
    sc_trace(mVcdFile, tmp_29_cast_fu_939_p1, "tmp_29_cast_fu_939_p1");
    sc_trace(mVcdFile, tmp_31_fu_948_p2, "tmp_31_fu_948_p2");
    sc_trace(mVcdFile, tmp_31_cast_fu_953_p1, "tmp_31_cast_fu_953_p1");
    sc_trace(mVcdFile, tmp_33_fu_962_p2, "tmp_33_fu_962_p2");
    sc_trace(mVcdFile, tmp_33_cast_fu_967_p1, "tmp_33_cast_fu_967_p1");
    sc_trace(mVcdFile, tmp_35_fu_976_p2, "tmp_35_fu_976_p2");
    sc_trace(mVcdFile, tmp_35_cast_fu_981_p1, "tmp_35_cast_fu_981_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("img_proc.hdltvin.dat");
    mHdltvoutHandle.open("img_proc.hdltvout.dat");
}

img_proc::~img_proc() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete indata_U;
    delete outdata_U;
    delete grp_add_watermark_fu_682;
}

void img_proc::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_add_watermark_fu_682_ap_start = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
            ap_reg_grp_add_watermark_fu_682_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_add_watermark_fu_682_ap_ready.read())) {
            ap_reg_grp_add_watermark_fu_682_ap_start = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        mark_idx_reg_660 = mark_idx_1_reg_1153.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        mark_idx_reg_660 = ap_const_lv16_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        tmp_50_reg_671 = idx_urem_reg_1158.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        tmp_50_reg_671 = ap_const_lv16_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_fu_693_p2.read(), ap_const_lv1_0))) {
        base_idx_reg_1163 = base_idx_fu_763_p2.read();
        idx_urem_reg_1158 = idx_urem_fu_717_p3.read();
        tmp_6_reg_1181 = tmp_6_fu_773_p1.read();
        tmp_8_reg_1191 = tmp_8_fu_784_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mark_idx_1_reg_1153 = mark_idx_1_fu_699_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mark_load_reg_1226 = mark_q0.read();
        tmp_10_reg_1206 = tmp_10_fu_803_p1.read();
        tmp_12_reg_1216 = tmp_12_fu_817_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        tmp_14_reg_1231 = tmp_14_fu_831_p1.read();
        tmp_16_reg_1241 = tmp_16_fu_845_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        tmp_18_reg_1251 = tmp_18_fu_859_p1.read();
        tmp_20_reg_1261 = tmp_20_fu_873_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        tmp_22_reg_1271 = tmp_22_fu_887_p1.read();
        tmp_24_reg_1281 = tmp_24_fu_901_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp_26_reg_1291 = tmp_26_fu_915_p1.read();
        tmp_28_reg_1301 = tmp_28_fu_929_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        tmp_30_reg_1311 = tmp_30_fu_943_p1.read();
        tmp_32_reg_1321 = tmp_32_fu_957_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        tmp_34_reg_1331 = tmp_34_fu_971_p1.read();
        tmp_36_reg_1341 = tmp_36_fu_985_p1.read();
    }
}

void img_proc::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void img_proc::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void img_proc::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void img_proc::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void img_proc::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void img_proc::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void img_proc::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void img_proc::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void img_proc::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void img_proc::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void img_proc::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void img_proc::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void img_proc::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void img_proc::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void img_proc::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void img_proc::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void img_proc::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void img_proc::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void img_proc::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void img_proc::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void img_proc::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void img_proc::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_fu_693_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void img_proc::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void img_proc::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_fu_693_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void img_proc::thread_base_idx_cast_fu_769_p1() {
    base_idx_cast_fu_769_p1 = esl_sext<32,22>(base_idx_fu_763_p2.read());
}

void img_proc::thread_base_idx_fu_763_p2() {
    base_idx_fu_763_p2 = (!tmp_5_cast_cast_fu_759_p1.read().is_01() || !tmp_4_cast_fu_743_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(tmp_5_cast_cast_fu_759_p1.read()) + sc_bigint<22>(tmp_4_cast_fu_743_p1.read()));
}

void img_proc::thread_grp_add_watermark_fu_682_ap_start() {
    grp_add_watermark_fu_682_ap_start = ap_reg_grp_add_watermark_fu_682_ap_start.read();
}

void img_proc::thread_idx_urem_fu_717_p3() {
    idx_urem_fu_717_p3 = (!tmp_49_fu_711_p2.read()[0].is_01())? sc_lv<16>(): ((tmp_49_fu_711_p2.read()[0].to_bool())? next_urem_fu_705_p2.read(): ap_const_lv16_0);
}

void img_proc::thread_img_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        img_address0 =  (sc_lv<20>) (tmp_34_fu_971_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        img_address0 =  (sc_lv<20>) (tmp_30_fu_943_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        img_address0 =  (sc_lv<20>) (tmp_26_fu_915_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        img_address0 =  (sc_lv<20>) (tmp_22_fu_887_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        img_address0 =  (sc_lv<20>) (tmp_18_fu_859_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        img_address0 =  (sc_lv<20>) (tmp_14_fu_831_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        img_address0 =  (sc_lv<20>) (tmp_10_fu_803_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        img_address0 =  (sc_lv<20>) (tmp_6_fu_773_p1.read());
    } else {
        img_address0 = "XXXXXXXXXXXXXXXXXXXX";
    }
}

void img_proc::thread_img_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        img_address1 =  (sc_lv<20>) (tmp_36_fu_985_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        img_address1 =  (sc_lv<20>) (tmp_32_fu_957_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        img_address1 =  (sc_lv<20>) (tmp_28_fu_929_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        img_address1 =  (sc_lv<20>) (tmp_24_fu_901_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        img_address1 =  (sc_lv<20>) (tmp_20_fu_873_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        img_address1 =  (sc_lv<20>) (tmp_16_fu_845_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        img_address1 =  (sc_lv<20>) (tmp_12_fu_817_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        img_address1 =  (sc_lv<20>) (tmp_8_fu_784_p1.read());
    } else {
        img_address1 = "XXXXXXXXXXXXXXXXXXXX";
    }
}

void img_proc::thread_img_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        img_ce0 = ap_const_logic_1;
    } else {
        img_ce0 = ap_const_logic_0;
    }
}

void img_proc::thread_img_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        img_ce1 = ap_const_logic_1;
    } else {
        img_ce1 = ap_const_logic_0;
    }
}

void img_proc::thread_indata_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        indata_address0 =  (sc_lv<4>) (ap_const_lv64_E);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        indata_address0 =  (sc_lv<4>) (ap_const_lv64_C);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        indata_address0 =  (sc_lv<4>) (ap_const_lv64_A);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        indata_address0 =  (sc_lv<4>) (ap_const_lv64_8);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        indata_address0 =  (sc_lv<4>) (ap_const_lv64_6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        indata_address0 =  (sc_lv<4>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        indata_address0 =  (sc_lv<4>) (ap_const_lv64_2);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        indata_address0 =  (sc_lv<4>) (ap_const_lv64_0);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        indata_address0 = grp_add_watermark_fu_682_indata_address0.read();
    } else {
        indata_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void img_proc::thread_indata_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        indata_address1 =  (sc_lv<4>) (ap_const_lv64_F);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        indata_address1 =  (sc_lv<4>) (ap_const_lv64_D);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        indata_address1 =  (sc_lv<4>) (ap_const_lv64_B);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        indata_address1 =  (sc_lv<4>) (ap_const_lv64_9);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        indata_address1 =  (sc_lv<4>) (ap_const_lv64_7);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        indata_address1 =  (sc_lv<4>) (ap_const_lv64_5);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        indata_address1 =  (sc_lv<4>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        indata_address1 =  (sc_lv<4>) (ap_const_lv64_1);
    } else {
        indata_address1 =  (sc_lv<4>) ("XXXX");
    }
}

void img_proc::thread_indata_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        indata_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        indata_ce0 = grp_add_watermark_fu_682_indata_ce0.read();
    } else {
        indata_ce0 = ap_const_logic_0;
    }
}

void img_proc::thread_indata_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        indata_ce1 = ap_const_logic_1;
    } else {
        indata_ce1 = ap_const_logic_0;
    }
}

void img_proc::thread_indata_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        indata_we0 = ap_const_logic_1;
    } else {
        indata_we0 = ap_const_logic_0;
    }
}

void img_proc::thread_indata_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        indata_we1 = ap_const_logic_1;
    } else {
        indata_we1 = ap_const_logic_0;
    }
}

void img_proc::thread_mark_address0() {
    mark_address0 =  (sc_lv<16>) (tmp_37_fu_789_p1.read());
}

void img_proc::thread_mark_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mark_ce0 = ap_const_logic_1;
    } else {
        mark_ce0 = ap_const_logic_0;
    }
}

void img_proc::thread_mark_idx_1_fu_699_p2() {
    mark_idx_1_fu_699_p2 = (!mark_idx_reg_660.read().is_01() || !ap_const_lv16_1.is_01())? sc_lv<16>(): (sc_biguint<16>(mark_idx_reg_660.read()) + sc_biguint<16>(ap_const_lv16_1));
}

void img_proc::thread_mark_idx_cast_fu_689_p1() {
    mark_idx_cast_fu_689_p1 = esl_zext<17,16>(mark_idx_reg_660.read());
}

void img_proc::thread_next_urem_fu_705_p2() {
    next_urem_fu_705_p2 = (!ap_const_lv16_1.is_01() || !tmp_50_reg_671.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_1) + sc_biguint<16>(tmp_50_reg_671.read()));
}

void img_proc::thread_out_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        out_r_address0 =  (sc_lv<20>) (tmp_34_reg_1331.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        out_r_address0 =  (sc_lv<20>) (tmp_30_reg_1311.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        out_r_address0 =  (sc_lv<20>) (tmp_26_reg_1291.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        out_r_address0 =  (sc_lv<20>) (tmp_22_reg_1271.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        out_r_address0 =  (sc_lv<20>) (tmp_18_reg_1251.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        out_r_address0 =  (sc_lv<20>) (tmp_14_reg_1231.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        out_r_address0 =  (sc_lv<20>) (tmp_10_reg_1206.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        out_r_address0 =  (sc_lv<20>) (tmp_6_reg_1181.read());
    } else {
        out_r_address0 = "XXXXXXXXXXXXXXXXXXXX";
    }
}

void img_proc::thread_out_r_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        out_r_address1 =  (sc_lv<20>) (tmp_36_reg_1341.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        out_r_address1 =  (sc_lv<20>) (tmp_32_reg_1321.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        out_r_address1 =  (sc_lv<20>) (tmp_28_reg_1301.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        out_r_address1 =  (sc_lv<20>) (tmp_24_reg_1281.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        out_r_address1 =  (sc_lv<20>) (tmp_20_reg_1261.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        out_r_address1 =  (sc_lv<20>) (tmp_16_reg_1241.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        out_r_address1 =  (sc_lv<20>) (tmp_12_reg_1216.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        out_r_address1 =  (sc_lv<20>) (tmp_8_reg_1191.read());
    } else {
        out_r_address1 = "XXXXXXXXXXXXXXXXXXXX";
    }
}

void img_proc::thread_out_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        out_r_ce0 = ap_const_logic_1;
    } else {
        out_r_ce0 = ap_const_logic_0;
    }
}

void img_proc::thread_out_r_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        out_r_ce1 = ap_const_logic_1;
    } else {
        out_r_ce1 = ap_const_logic_0;
    }
}

void img_proc::thread_out_r_d0() {
    out_r_d0 = outdata_q0.read();
}

void img_proc::thread_out_r_d1() {
    out_r_d1 = outdata_q1.read();
}

void img_proc::thread_out_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        out_r_we0 = ap_const_logic_1;
    } else {
        out_r_we0 = ap_const_logic_0;
    }
}

void img_proc::thread_out_r_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        out_r_we1 = ap_const_logic_1;
    } else {
        out_r_we1 = ap_const_logic_0;
    }
}

void img_proc::thread_outdata_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        outdata_address0 =  (sc_lv<4>) (ap_const_lv64_E);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        outdata_address0 =  (sc_lv<4>) (ap_const_lv64_C);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        outdata_address0 =  (sc_lv<4>) (ap_const_lv64_A);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        outdata_address0 =  (sc_lv<4>) (ap_const_lv64_8);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        outdata_address0 =  (sc_lv<4>) (ap_const_lv64_6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        outdata_address0 =  (sc_lv<4>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        outdata_address0 =  (sc_lv<4>) (ap_const_lv64_2);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        outdata_address0 =  (sc_lv<4>) (ap_const_lv64_0);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        outdata_address0 = grp_add_watermark_fu_682_outdata_address0.read();
    } else {
        outdata_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void img_proc::thread_outdata_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        outdata_address1 =  (sc_lv<4>) (ap_const_lv64_F);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        outdata_address1 =  (sc_lv<4>) (ap_const_lv64_D);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        outdata_address1 =  (sc_lv<4>) (ap_const_lv64_B);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        outdata_address1 =  (sc_lv<4>) (ap_const_lv64_9);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        outdata_address1 =  (sc_lv<4>) (ap_const_lv64_7);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        outdata_address1 =  (sc_lv<4>) (ap_const_lv64_5);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        outdata_address1 =  (sc_lv<4>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        outdata_address1 =  (sc_lv<4>) (ap_const_lv64_1);
    } else {
        outdata_address1 =  (sc_lv<4>) ("XXXX");
    }
}

void img_proc::thread_outdata_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        outdata_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        outdata_ce0 = grp_add_watermark_fu_682_outdata_ce0.read();
    } else {
        outdata_ce0 = ap_const_logic_0;
    }
}

void img_proc::thread_outdata_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        outdata_ce1 = ap_const_logic_1;
    } else {
        outdata_ce1 = ap_const_logic_0;
    }
}

void img_proc::thread_outdata_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        outdata_we0 = grp_add_watermark_fu_682_outdata_we0.read();
    } else {
        outdata_we0 = ap_const_logic_0;
    }
}

void img_proc::thread_tmp_10_fu_803_p1() {
    tmp_10_fu_803_p1 = esl_zext<64,32>(tmp_9_cast_fu_799_p1.read());
}

void img_proc::thread_tmp_11_cast_fu_813_p1() {
    tmp_11_cast_fu_813_p1 = esl_sext<32,22>(tmp_11_fu_808_p2.read());
}

void img_proc::thread_tmp_11_fu_808_p2() {
    tmp_11_fu_808_p2 = (base_idx_reg_1163.read() | ap_const_lv22_3);
}

void img_proc::thread_tmp_12_fu_817_p1() {
    tmp_12_fu_817_p1 = esl_zext<64,32>(tmp_11_cast_fu_813_p1.read());
}

void img_proc::thread_tmp_13_cast_fu_827_p1() {
    tmp_13_cast_fu_827_p1 = esl_sext<32,22>(tmp_13_fu_822_p2.read());
}

void img_proc::thread_tmp_13_fu_822_p2() {
    tmp_13_fu_822_p2 = (!ap_const_lv22_320.is_01() || !base_idx_reg_1163.read().is_01())? sc_lv<22>(): (sc_biguint<22>(ap_const_lv22_320) + sc_biguint<22>(base_idx_reg_1163.read()));
}

void img_proc::thread_tmp_14_fu_831_p1() {
    tmp_14_fu_831_p1 = esl_zext<64,32>(tmp_13_cast_fu_827_p1.read());
}

void img_proc::thread_tmp_15_cast_fu_841_p1() {
    tmp_15_cast_fu_841_p1 = esl_sext<32,22>(tmp_15_fu_836_p2.read());
}

void img_proc::thread_tmp_15_fu_836_p2() {
    tmp_15_fu_836_p2 = (!ap_const_lv22_321.is_01() || !base_idx_reg_1163.read().is_01())? sc_lv<22>(): (sc_biguint<22>(ap_const_lv22_321) + sc_biguint<22>(base_idx_reg_1163.read()));
}

void img_proc::thread_tmp_16_fu_845_p1() {
    tmp_16_fu_845_p1 = esl_zext<64,32>(tmp_15_cast_fu_841_p1.read());
}

void img_proc::thread_tmp_17_cast_fu_855_p1() {
    tmp_17_cast_fu_855_p1 = esl_sext<32,22>(tmp_17_fu_850_p2.read());
}

void img_proc::thread_tmp_17_fu_850_p2() {
    tmp_17_fu_850_p2 = (!ap_const_lv22_322.is_01() || !base_idx_reg_1163.read().is_01())? sc_lv<22>(): (sc_biguint<22>(ap_const_lv22_322) + sc_biguint<22>(base_idx_reg_1163.read()));
}

void img_proc::thread_tmp_18_fu_859_p1() {
    tmp_18_fu_859_p1 = esl_zext<64,32>(tmp_17_cast_fu_855_p1.read());
}

void img_proc::thread_tmp_19_cast_fu_869_p1() {
    tmp_19_cast_fu_869_p1 = esl_sext<32,22>(tmp_19_fu_864_p2.read());
}

void img_proc::thread_tmp_19_fu_864_p2() {
    tmp_19_fu_864_p2 = (!ap_const_lv22_323.is_01() || !base_idx_reg_1163.read().is_01())? sc_lv<22>(): (sc_biguint<22>(ap_const_lv22_323) + sc_biguint<22>(base_idx_reg_1163.read()));
}

void img_proc::thread_tmp_20_fu_873_p1() {
    tmp_20_fu_873_p1 = esl_zext<64,32>(tmp_19_cast_fu_869_p1.read());
}

void img_proc::thread_tmp_21_cast_fu_883_p1() {
    tmp_21_cast_fu_883_p1 = esl_sext<32,22>(tmp_21_fu_878_p2.read());
}

void img_proc::thread_tmp_21_fu_878_p2() {
    tmp_21_fu_878_p2 = (!ap_const_lv22_640.is_01() || !base_idx_reg_1163.read().is_01())? sc_lv<22>(): (sc_biguint<22>(ap_const_lv22_640) + sc_biguint<22>(base_idx_reg_1163.read()));
}

void img_proc::thread_tmp_22_fu_887_p1() {
    tmp_22_fu_887_p1 = esl_zext<64,32>(tmp_21_cast_fu_883_p1.read());
}

void img_proc::thread_tmp_23_cast_fu_897_p1() {
    tmp_23_cast_fu_897_p1 = esl_sext<32,22>(tmp_23_fu_892_p2.read());
}

void img_proc::thread_tmp_23_fu_892_p2() {
    tmp_23_fu_892_p2 = (!ap_const_lv22_641.is_01() || !base_idx_reg_1163.read().is_01())? sc_lv<22>(): (sc_biguint<22>(ap_const_lv22_641) + sc_biguint<22>(base_idx_reg_1163.read()));
}

void img_proc::thread_tmp_24_fu_901_p1() {
    tmp_24_fu_901_p1 = esl_zext<64,32>(tmp_23_cast_fu_897_p1.read());
}

void img_proc::thread_tmp_25_cast_fu_911_p1() {
    tmp_25_cast_fu_911_p1 = esl_sext<32,22>(tmp_25_fu_906_p2.read());
}

void img_proc::thread_tmp_25_fu_906_p2() {
    tmp_25_fu_906_p2 = (!ap_const_lv22_642.is_01() || !base_idx_reg_1163.read().is_01())? sc_lv<22>(): (sc_biguint<22>(ap_const_lv22_642) + sc_biguint<22>(base_idx_reg_1163.read()));
}

void img_proc::thread_tmp_26_fu_915_p1() {
    tmp_26_fu_915_p1 = esl_zext<64,32>(tmp_25_cast_fu_911_p1.read());
}

void img_proc::thread_tmp_27_cast_fu_925_p1() {
    tmp_27_cast_fu_925_p1 = esl_sext<32,22>(tmp_27_fu_920_p2.read());
}

void img_proc::thread_tmp_27_fu_920_p2() {
    tmp_27_fu_920_p2 = (!ap_const_lv22_643.is_01() || !base_idx_reg_1163.read().is_01())? sc_lv<22>(): (sc_biguint<22>(ap_const_lv22_643) + sc_biguint<22>(base_idx_reg_1163.read()));
}

void img_proc::thread_tmp_28_fu_929_p1() {
    tmp_28_fu_929_p1 = esl_zext<64,32>(tmp_27_cast_fu_925_p1.read());
}

void img_proc::thread_tmp_29_cast_fu_939_p1() {
    tmp_29_cast_fu_939_p1 = esl_sext<32,22>(tmp_29_fu_934_p2.read());
}

void img_proc::thread_tmp_29_fu_934_p2() {
    tmp_29_fu_934_p2 = (!ap_const_lv22_960.is_01() || !base_idx_reg_1163.read().is_01())? sc_lv<22>(): (sc_biguint<22>(ap_const_lv22_960) + sc_biguint<22>(base_idx_reg_1163.read()));
}

void img_proc::thread_tmp_2_cast_fu_725_p1() {
    tmp_2_cast_fu_725_p1 = esl_zext<17,16>(tmp_50_reg_671.read());
}

void img_proc::thread_tmp_30_fu_943_p1() {
    tmp_30_fu_943_p1 = esl_zext<64,32>(tmp_29_cast_fu_939_p1.read());
}

void img_proc::thread_tmp_31_cast_fu_953_p1() {
    tmp_31_cast_fu_953_p1 = esl_sext<32,22>(tmp_31_fu_948_p2.read());
}

void img_proc::thread_tmp_31_fu_948_p2() {
    tmp_31_fu_948_p2 = (!ap_const_lv22_961.is_01() || !base_idx_reg_1163.read().is_01())? sc_lv<22>(): (sc_biguint<22>(ap_const_lv22_961) + sc_biguint<22>(base_idx_reg_1163.read()));
}

void img_proc::thread_tmp_32_fu_957_p1() {
    tmp_32_fu_957_p1 = esl_zext<64,32>(tmp_31_cast_fu_953_p1.read());
}

void img_proc::thread_tmp_33_cast_fu_967_p1() {
    tmp_33_cast_fu_967_p1 = esl_sext<32,22>(tmp_33_fu_962_p2.read());
}

void img_proc::thread_tmp_33_fu_962_p2() {
    tmp_33_fu_962_p2 = (!ap_const_lv22_962.is_01() || !base_idx_reg_1163.read().is_01())? sc_lv<22>(): (sc_biguint<22>(ap_const_lv22_962) + sc_biguint<22>(base_idx_reg_1163.read()));
}

void img_proc::thread_tmp_34_fu_971_p1() {
    tmp_34_fu_971_p1 = esl_zext<64,32>(tmp_33_cast_fu_967_p1.read());
}

void img_proc::thread_tmp_35_cast_fu_981_p1() {
    tmp_35_cast_fu_981_p1 = esl_sext<32,22>(tmp_35_fu_976_p2.read());
}

void img_proc::thread_tmp_35_fu_976_p2() {
    tmp_35_fu_976_p2 = (!ap_const_lv22_963.is_01() || !base_idx_reg_1163.read().is_01())? sc_lv<22>(): (sc_biguint<22>(ap_const_lv22_963) + sc_biguint<22>(base_idx_reg_1163.read()));
}

void img_proc::thread_tmp_36_fu_985_p1() {
    tmp_36_fu_985_p1 = esl_zext<64,32>(tmp_35_cast_fu_981_p1.read());
}

void img_proc::thread_tmp_37_fu_789_p1() {
    tmp_37_fu_789_p1 = esl_zext<64,16>(mark_idx_reg_660.read());
}

void img_proc::thread_tmp_38_fu_735_p3() {
    tmp_38_fu_735_p3 = esl_concat<17,4>(tmp_s_fu_729_p2.read(), ap_const_lv4_0);
}

void img_proc::thread_tmp_49_fu_711_p2() {
    tmp_49_fu_711_p2 = (!next_urem_fu_705_p2.read().is_01() || !ap_const_lv16_C8.is_01())? sc_lv<1>(): (sc_biguint<16>(next_urem_fu_705_p2.read()) < sc_biguint<16>(ap_const_lv16_C8));
}

void img_proc::thread_tmp_4_cast_fu_743_p1() {
    tmp_4_cast_fu_743_p1 = esl_sext<22,21>(tmp_38_fu_735_p3.read());
}

void img_proc::thread_tmp_51_fu_747_p1() {
    tmp_51_fu_747_p1 = tmp_50_reg_671.read().range(8-1, 0);
}

void img_proc::thread_tmp_5_cast_cast_fu_759_p1() {
    tmp_5_cast_cast_fu_759_p1 = esl_zext<22,10>(tmp_5_fu_751_p3.read());
}

void img_proc::thread_tmp_5_fu_751_p3() {
    tmp_5_fu_751_p3 = esl_concat<8,2>(tmp_51_fu_747_p1.read(), ap_const_lv2_0);
}

void img_proc::thread_tmp_6_fu_773_p1() {
    tmp_6_fu_773_p1 = esl_zext<64,32>(base_idx_cast_fu_769_p1.read());
}

void img_proc::thread_tmp_7_fu_778_p2() {
    tmp_7_fu_778_p2 = (base_idx_cast_fu_769_p1.read() | ap_const_lv32_1);
}

void img_proc::thread_tmp_8_fu_784_p1() {
    tmp_8_fu_784_p1 = esl_zext<64,32>(tmp_7_fu_778_p2.read());
}

void img_proc::thread_tmp_9_cast_fu_799_p1() {
    tmp_9_cast_fu_799_p1 = esl_sext<32,22>(tmp_9_fu_794_p2.read());
}

void img_proc::thread_tmp_9_fu_794_p2() {
    tmp_9_fu_794_p2 = (base_idx_reg_1163.read() | ap_const_lv22_2);
}

void img_proc::thread_tmp_fu_693_p2() {
    tmp_fu_693_p2 = (!mark_idx_reg_660.read().is_01() || !ap_const_lv16_9C40.is_01())? sc_lv<1>(): sc_lv<1>(mark_idx_reg_660.read() == ap_const_lv16_9C40);
}

void img_proc::thread_tmp_s_fu_729_p2() {
    tmp_s_fu_729_p2 = (!mark_idx_cast_fu_689_p1.read().is_01() || !tmp_2_cast_fu_725_p1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(mark_idx_cast_fu_689_p1.read()) - sc_biguint<17>(tmp_2_cast_fu_725_p1.read()));
}

void img_proc::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_fu_693_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(grp_add_watermark_fu_682_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<21>) ("XXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void img_proc::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"img_address0\" :  \"" << img_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"img_ce0\" :  \"" << img_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"img_q0\" :  \"" << img_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"img_address1\" :  \"" << img_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"img_ce1\" :  \"" << img_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"img_q1\" :  \"" << img_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mark_address0\" :  \"" << mark_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mark_ce0\" :  \"" << mark_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mark_q0\" :  \"" << mark_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_address0\" :  \"" << out_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_ce0\" :  \"" << out_r_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_we0\" :  \"" << out_r_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_d0\" :  \"" << out_r_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_address1\" :  \"" << out_r_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_ce1\" :  \"" << out_r_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_we1\" :  \"" << out_r_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_d1\" :  \"" << out_r_d1.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

