// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "add_watermark.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const bool add_watermark::ap_const_boolean_1 = true;
const bool add_watermark::ap_const_boolean_0 = false;
const sc_lv<8> add_watermark::ap_const_lv8_0 = "00000000";
const sc_lv<4> add_watermark::ap_const_lv4_0 = "0000";
const sc_lv<2> add_watermark::ap_const_lv2_0 = "00";
const sc_lv<20> add_watermark::ap_const_lv20_A = "1010";
const sc_lv<20> add_watermark::ap_const_lv20_19 = "11001";
const sc_logic add_watermark::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic add_watermark::ap_const_logic_0 = sc_dt::Log_0;

add_watermark::add_watermark(sc_module_name name) : sc_module(name), mVcdFile(0) {
    call_ret5_integer_idct_fu_160 = new integer_idct("call_ret5_integer_idct_fu_160");
    call_ret5_integer_idct_fu_160->ap_ready(call_ret5_integer_idct_fu_160_ap_ready);
    call_ret5_integer_idct_fu_160->src_0_0_V_read(buf_temp_qft_0_0_V_fu_890_p2);
    call_ret5_integer_idct_fu_160->src_0_1_V_read(call_ret5_integer_idct_fu_160_src_0_1_V_read);
    call_ret5_integer_idct_fu_160->src_0_2_V_read(buf_temp_qft_0_2_V_fu_897_p2);
    call_ret5_integer_idct_fu_160->src_0_3_V_read(call_ret5_integer_idct_fu_160_src_0_3_V_read);
    call_ret5_integer_idct_fu_160->src_1_0_V_read(call_ret5_integer_idct_fu_160_src_1_0_V_read);
    call_ret5_integer_idct_fu_160->src_1_1_V_read(call_ret5_integer_idct_fu_160_src_1_1_V_read);
    call_ret5_integer_idct_fu_160->src_1_2_V_read(call_ret5_integer_idct_fu_160_src_1_2_V_read);
    call_ret5_integer_idct_fu_160->src_1_3_V_read(call_ret5_integer_idct_fu_160_src_1_3_V_read);
    call_ret5_integer_idct_fu_160->src_2_0_V_read(buf_temp_qft_2_0_V_fu_904_p2);
    call_ret5_integer_idct_fu_160->src_2_1_V_read(call_ret5_integer_idct_fu_160_src_2_1_V_read);
    call_ret5_integer_idct_fu_160->src_2_2_V_read(buf_temp_qft_2_2_V_fu_911_p2);
    call_ret5_integer_idct_fu_160->src_2_3_V_read(call_ret5_integer_idct_fu_160_src_2_3_V_read);
    call_ret5_integer_idct_fu_160->src_3_0_V_read(call_ret5_integer_idct_fu_160_src_3_0_V_read);
    call_ret5_integer_idct_fu_160->src_3_1_V_read(call_ret5_integer_idct_fu_160_src_3_1_V_read);
    call_ret5_integer_idct_fu_160->src_3_2_V_read(call_ret5_integer_idct_fu_160_src_3_2_V_read);
    call_ret5_integer_idct_fu_160->src_3_3_V_read(call_ret5_integer_idct_fu_160_src_3_3_V_read);
    call_ret5_integer_idct_fu_160->ap_return_0(call_ret5_integer_idct_fu_160_ap_return_0);
    call_ret5_integer_idct_fu_160->ap_return_1(call_ret5_integer_idct_fu_160_ap_return_1);
    call_ret5_integer_idct_fu_160->ap_return_2(call_ret5_integer_idct_fu_160_ap_return_2);
    call_ret5_integer_idct_fu_160->ap_return_3(call_ret5_integer_idct_fu_160_ap_return_3);
    call_ret5_integer_idct_fu_160->ap_return_4(call_ret5_integer_idct_fu_160_ap_return_4);
    call_ret5_integer_idct_fu_160->ap_return_5(call_ret5_integer_idct_fu_160_ap_return_5);
    call_ret5_integer_idct_fu_160->ap_return_6(call_ret5_integer_idct_fu_160_ap_return_6);
    call_ret5_integer_idct_fu_160->ap_return_7(call_ret5_integer_idct_fu_160_ap_return_7);
    call_ret5_integer_idct_fu_160->ap_return_8(call_ret5_integer_idct_fu_160_ap_return_8);
    call_ret5_integer_idct_fu_160->ap_return_9(call_ret5_integer_idct_fu_160_ap_return_9);
    call_ret5_integer_idct_fu_160->ap_return_10(call_ret5_integer_idct_fu_160_ap_return_10);
    call_ret5_integer_idct_fu_160->ap_return_11(call_ret5_integer_idct_fu_160_ap_return_11);
    call_ret5_integer_idct_fu_160->ap_return_12(call_ret5_integer_idct_fu_160_ap_return_12);
    call_ret5_integer_idct_fu_160->ap_return_13(call_ret5_integer_idct_fu_160_ap_return_13);
    call_ret5_integer_idct_fu_160->ap_return_14(call_ret5_integer_idct_fu_160_ap_return_14);
    call_ret5_integer_idct_fu_160->ap_return_15(call_ret5_integer_idct_fu_160_ap_return_15);
    call_ret2_i_dct_step_fu_180 = new dct_step("call_ret2_i_dct_step_fu_180");
    call_ret2_i_dct_step_fu_180->ap_ready(call_ret2_i_dct_step_fu_180_ap_ready);
    call_ret2_i_dct_step_fu_180->src_0_0_read(call_ret3_read_data_fu_220_ap_return_0);
    call_ret2_i_dct_step_fu_180->src_0_1_read(call_ret3_read_data_fu_220_ap_return_1);
    call_ret2_i_dct_step_fu_180->src_0_2_read(call_ret3_read_data_fu_220_ap_return_2);
    call_ret2_i_dct_step_fu_180->src_0_3_read(call_ret3_read_data_fu_220_ap_return_3);
    call_ret2_i_dct_step_fu_180->src_1_0_read(call_ret3_read_data_fu_220_ap_return_4);
    call_ret2_i_dct_step_fu_180->src_1_1_read(call_ret3_read_data_fu_220_ap_return_5);
    call_ret2_i_dct_step_fu_180->src_1_2_read(call_ret3_read_data_fu_220_ap_return_6);
    call_ret2_i_dct_step_fu_180->src_1_3_read(call_ret3_read_data_fu_220_ap_return_7);
    call_ret2_i_dct_step_fu_180->src_2_0_read(call_ret3_read_data_fu_220_ap_return_8);
    call_ret2_i_dct_step_fu_180->src_2_1_read(call_ret3_read_data_fu_220_ap_return_9);
    call_ret2_i_dct_step_fu_180->src_2_2_read(call_ret3_read_data_fu_220_ap_return_10);
    call_ret2_i_dct_step_fu_180->src_2_3_read(call_ret3_read_data_fu_220_ap_return_11);
    call_ret2_i_dct_step_fu_180->src_3_0_read(call_ret3_read_data_fu_220_ap_return_12);
    call_ret2_i_dct_step_fu_180->src_3_1_read(call_ret3_read_data_fu_220_ap_return_13);
    call_ret2_i_dct_step_fu_180->src_3_2_read(call_ret3_read_data_fu_220_ap_return_14);
    call_ret2_i_dct_step_fu_180->src_3_3_read(call_ret3_read_data_fu_220_ap_return_15);
    call_ret2_i_dct_step_fu_180->ap_return_0(call_ret2_i_dct_step_fu_180_ap_return_0);
    call_ret2_i_dct_step_fu_180->ap_return_1(call_ret2_i_dct_step_fu_180_ap_return_1);
    call_ret2_i_dct_step_fu_180->ap_return_2(call_ret2_i_dct_step_fu_180_ap_return_2);
    call_ret2_i_dct_step_fu_180->ap_return_3(call_ret2_i_dct_step_fu_180_ap_return_3);
    call_ret2_i_dct_step_fu_180->ap_return_4(call_ret2_i_dct_step_fu_180_ap_return_4);
    call_ret2_i_dct_step_fu_180->ap_return_5(call_ret2_i_dct_step_fu_180_ap_return_5);
    call_ret2_i_dct_step_fu_180->ap_return_6(call_ret2_i_dct_step_fu_180_ap_return_6);
    call_ret2_i_dct_step_fu_180->ap_return_7(call_ret2_i_dct_step_fu_180_ap_return_7);
    call_ret2_i_dct_step_fu_180->ap_return_8(call_ret2_i_dct_step_fu_180_ap_return_8);
    call_ret2_i_dct_step_fu_180->ap_return_9(call_ret2_i_dct_step_fu_180_ap_return_9);
    call_ret2_i_dct_step_fu_180->ap_return_10(call_ret2_i_dct_step_fu_180_ap_return_10);
    call_ret2_i_dct_step_fu_180->ap_return_11(call_ret2_i_dct_step_fu_180_ap_return_11);
    call_ret2_i_dct_step_fu_180->ap_return_12(call_ret2_i_dct_step_fu_180_ap_return_12);
    call_ret2_i_dct_step_fu_180->ap_return_13(call_ret2_i_dct_step_fu_180_ap_return_13);
    call_ret2_i_dct_step_fu_180->ap_return_14(call_ret2_i_dct_step_fu_180_ap_return_14);
    call_ret2_i_dct_step_fu_180->ap_return_15(call_ret2_i_dct_step_fu_180_ap_return_15);
    call_ret_i_dct_step_fu_200 = new dct_step("call_ret_i_dct_step_fu_200");
    call_ret_i_dct_step_fu_200->ap_ready(call_ret_i_dct_step_fu_200_ap_ready);
    call_ret_i_dct_step_fu_200->src_0_0_read(temp_0_0_reg_918);
    call_ret_i_dct_step_fu_200->src_0_1_read(temp_0_1_reg_923);
    call_ret_i_dct_step_fu_200->src_0_2_read(temp_0_2_reg_928);
    call_ret_i_dct_step_fu_200->src_0_3_read(temp_0_3_reg_933);
    call_ret_i_dct_step_fu_200->src_1_0_read(temp_1_0_reg_938);
    call_ret_i_dct_step_fu_200->src_1_1_read(temp_1_1_reg_943);
    call_ret_i_dct_step_fu_200->src_1_2_read(temp_1_2_reg_948);
    call_ret_i_dct_step_fu_200->src_1_3_read(temp_1_3_reg_953);
    call_ret_i_dct_step_fu_200->src_2_0_read(temp_2_0_reg_958);
    call_ret_i_dct_step_fu_200->src_2_1_read(temp_2_1_reg_963);
    call_ret_i_dct_step_fu_200->src_2_2_read(temp_2_2_reg_968);
    call_ret_i_dct_step_fu_200->src_2_3_read(temp_2_3_reg_973);
    call_ret_i_dct_step_fu_200->src_3_0_read(temp_3_0_reg_978);
    call_ret_i_dct_step_fu_200->src_3_1_read(temp_3_1_reg_983);
    call_ret_i_dct_step_fu_200->src_3_2_read(temp_3_2_reg_988);
    call_ret_i_dct_step_fu_200->src_3_3_read(temp_3_3_reg_993);
    call_ret_i_dct_step_fu_200->ap_return_0(call_ret_i_dct_step_fu_200_ap_return_0);
    call_ret_i_dct_step_fu_200->ap_return_1(call_ret_i_dct_step_fu_200_ap_return_1);
    call_ret_i_dct_step_fu_200->ap_return_2(call_ret_i_dct_step_fu_200_ap_return_2);
    call_ret_i_dct_step_fu_200->ap_return_3(call_ret_i_dct_step_fu_200_ap_return_3);
    call_ret_i_dct_step_fu_200->ap_return_4(call_ret_i_dct_step_fu_200_ap_return_4);
    call_ret_i_dct_step_fu_200->ap_return_5(call_ret_i_dct_step_fu_200_ap_return_5);
    call_ret_i_dct_step_fu_200->ap_return_6(call_ret_i_dct_step_fu_200_ap_return_6);
    call_ret_i_dct_step_fu_200->ap_return_7(call_ret_i_dct_step_fu_200_ap_return_7);
    call_ret_i_dct_step_fu_200->ap_return_8(call_ret_i_dct_step_fu_200_ap_return_8);
    call_ret_i_dct_step_fu_200->ap_return_9(call_ret_i_dct_step_fu_200_ap_return_9);
    call_ret_i_dct_step_fu_200->ap_return_10(call_ret_i_dct_step_fu_200_ap_return_10);
    call_ret_i_dct_step_fu_200->ap_return_11(call_ret_i_dct_step_fu_200_ap_return_11);
    call_ret_i_dct_step_fu_200->ap_return_12(call_ret_i_dct_step_fu_200_ap_return_12);
    call_ret_i_dct_step_fu_200->ap_return_13(call_ret_i_dct_step_fu_200_ap_return_13);
    call_ret_i_dct_step_fu_200->ap_return_14(call_ret_i_dct_step_fu_200_ap_return_14);
    call_ret_i_dct_step_fu_200->ap_return_15(call_ret_i_dct_step_fu_200_ap_return_15);
    call_ret3_read_data_fu_220 = new read_data("call_ret3_read_data_fu_220");
    call_ret3_read_data_fu_220->ap_ready(call_ret3_read_data_fu_220_ap_ready);
    call_ret3_read_data_fu_220->input_0_read(indata_0_read);
    call_ret3_read_data_fu_220->input_1_read(indata_1_read);
    call_ret3_read_data_fu_220->input_2_read(indata_2_read);
    call_ret3_read_data_fu_220->input_3_read(indata_3_read);
    call_ret3_read_data_fu_220->input_4_read(indata_4_read);
    call_ret3_read_data_fu_220->input_5_read(indata_5_read);
    call_ret3_read_data_fu_220->input_6_read(indata_6_read);
    call_ret3_read_data_fu_220->input_7_read(indata_7_read);
    call_ret3_read_data_fu_220->input_8_read(indata_8_read);
    call_ret3_read_data_fu_220->input_9_read(indata_9_read);
    call_ret3_read_data_fu_220->input_10_read(indata_10_read);
    call_ret3_read_data_fu_220->input_11_read(indata_11_read);
    call_ret3_read_data_fu_220->input_12_read(indata_12_read);
    call_ret3_read_data_fu_220->input_13_read(indata_13_read);
    call_ret3_read_data_fu_220->input_14_read(indata_14_read);
    call_ret3_read_data_fu_220->input_15_read(indata_15_read);
    call_ret3_read_data_fu_220->ap_return_0(call_ret3_read_data_fu_220_ap_return_0);
    call_ret3_read_data_fu_220->ap_return_1(call_ret3_read_data_fu_220_ap_return_1);
    call_ret3_read_data_fu_220->ap_return_2(call_ret3_read_data_fu_220_ap_return_2);
    call_ret3_read_data_fu_220->ap_return_3(call_ret3_read_data_fu_220_ap_return_3);
    call_ret3_read_data_fu_220->ap_return_4(call_ret3_read_data_fu_220_ap_return_4);
    call_ret3_read_data_fu_220->ap_return_5(call_ret3_read_data_fu_220_ap_return_5);
    call_ret3_read_data_fu_220->ap_return_6(call_ret3_read_data_fu_220_ap_return_6);
    call_ret3_read_data_fu_220->ap_return_7(call_ret3_read_data_fu_220_ap_return_7);
    call_ret3_read_data_fu_220->ap_return_8(call_ret3_read_data_fu_220_ap_return_8);
    call_ret3_read_data_fu_220->ap_return_9(call_ret3_read_data_fu_220_ap_return_9);
    call_ret3_read_data_fu_220->ap_return_10(call_ret3_read_data_fu_220_ap_return_10);
    call_ret3_read_data_fu_220->ap_return_11(call_ret3_read_data_fu_220_ap_return_11);
    call_ret3_read_data_fu_220->ap_return_12(call_ret3_read_data_fu_220_ap_return_12);
    call_ret3_read_data_fu_220->ap_return_13(call_ret3_read_data_fu_220_ap_return_13);
    call_ret3_read_data_fu_220->ap_return_14(call_ret3_read_data_fu_220_ap_return_14);
    call_ret3_read_data_fu_220->ap_return_15(call_ret3_read_data_fu_220_ap_return_15);
    call_ret_write_data_fu_256 = new write_data("call_ret_write_data_fu_256");
    call_ret_write_data_fu_256->ap_ready(call_ret_write_data_fu_256_ap_ready);
    call_ret_write_data_fu_256->buf_0_0_read(call_ret5_integer_idct_fu_160_ap_return_0);
    call_ret_write_data_fu_256->buf_0_1_read(call_ret5_integer_idct_fu_160_ap_return_1);
    call_ret_write_data_fu_256->buf_0_2_read(call_ret5_integer_idct_fu_160_ap_return_2);
    call_ret_write_data_fu_256->buf_0_3_read(call_ret5_integer_idct_fu_160_ap_return_3);
    call_ret_write_data_fu_256->buf_1_0_read(call_ret5_integer_idct_fu_160_ap_return_4);
    call_ret_write_data_fu_256->buf_1_1_read(call_ret5_integer_idct_fu_160_ap_return_5);
    call_ret_write_data_fu_256->buf_1_2_read(call_ret5_integer_idct_fu_160_ap_return_6);
    call_ret_write_data_fu_256->buf_1_3_read(call_ret5_integer_idct_fu_160_ap_return_7);
    call_ret_write_data_fu_256->buf_2_0_read(call_ret5_integer_idct_fu_160_ap_return_8);
    call_ret_write_data_fu_256->buf_2_1_read(call_ret5_integer_idct_fu_160_ap_return_9);
    call_ret_write_data_fu_256->buf_2_2_read(call_ret5_integer_idct_fu_160_ap_return_10);
    call_ret_write_data_fu_256->buf_2_3_read(call_ret5_integer_idct_fu_160_ap_return_11);
    call_ret_write_data_fu_256->buf_3_0_read(call_ret5_integer_idct_fu_160_ap_return_12);
    call_ret_write_data_fu_256->buf_3_1_read(call_ret5_integer_idct_fu_160_ap_return_13);
    call_ret_write_data_fu_256->buf_3_2_read(call_ret5_integer_idct_fu_160_ap_return_14);
    call_ret_write_data_fu_256->buf_3_3_read(call_ret5_integer_idct_fu_160_ap_return_15);
    call_ret_write_data_fu_256->ap_return_0(call_ret_write_data_fu_256_ap_return_0);
    call_ret_write_data_fu_256->ap_return_1(call_ret_write_data_fu_256_ap_return_1);
    call_ret_write_data_fu_256->ap_return_2(call_ret_write_data_fu_256_ap_return_2);
    call_ret_write_data_fu_256->ap_return_3(call_ret_write_data_fu_256_ap_return_3);
    call_ret_write_data_fu_256->ap_return_4(call_ret_write_data_fu_256_ap_return_4);
    call_ret_write_data_fu_256->ap_return_5(call_ret_write_data_fu_256_ap_return_5);
    call_ret_write_data_fu_256->ap_return_6(call_ret_write_data_fu_256_ap_return_6);
    call_ret_write_data_fu_256->ap_return_7(call_ret_write_data_fu_256_ap_return_7);
    call_ret_write_data_fu_256->ap_return_8(call_ret_write_data_fu_256_ap_return_8);
    call_ret_write_data_fu_256->ap_return_9(call_ret_write_data_fu_256_ap_return_9);
    call_ret_write_data_fu_256->ap_return_10(call_ret_write_data_fu_256_ap_return_10);
    call_ret_write_data_fu_256->ap_return_11(call_ret_write_data_fu_256_ap_return_11);
    call_ret_write_data_fu_256->ap_return_12(call_ret_write_data_fu_256_ap_return_12);
    call_ret_write_data_fu_256->ap_return_13(call_ret_write_data_fu_256_ap_return_13);
    call_ret_write_data_fu_256->ap_return_14(call_ret_write_data_fu_256_ap_return_14);
    call_ret_write_data_fu_256->ap_return_15(call_ret_write_data_fu_256_ap_return_15);
    img_proc_mul_mul_bkb_U81 = new img_proc_mul_mul_bkb<1,1,16,6,20>("img_proc_mul_mul_bkb_U81");
    img_proc_mul_mul_bkb_U81->din0(call_ret_i_dct_step_fu_200_ap_return_0);
    img_proc_mul_mul_bkb_U81->din1(buf_temp_qft_0_0_V_fu_890_p1);
    img_proc_mul_mul_bkb_U81->dout(buf_temp_qft_0_0_V_fu_890_p2);
    img_proc_mul_mul_bkb_U82 = new img_proc_mul_mul_bkb<1,1,16,6,20>("img_proc_mul_mul_bkb_U82");
    img_proc_mul_mul_bkb_U82->din0(call_ret_i_dct_step_fu_200_ap_return_2);
    img_proc_mul_mul_bkb_U82->din1(buf_temp_qft_0_2_V_fu_897_p1);
    img_proc_mul_mul_bkb_U82->dout(buf_temp_qft_0_2_V_fu_897_p2);
    img_proc_mul_mul_bkb_U83 = new img_proc_mul_mul_bkb<1,1,16,6,20>("img_proc_mul_mul_bkb_U83");
    img_proc_mul_mul_bkb_U83->din0(call_ret_i_dct_step_fu_200_ap_return_8);
    img_proc_mul_mul_bkb_U83->din1(buf_temp_qft_2_0_V_fu_904_p1);
    img_proc_mul_mul_bkb_U83->dout(buf_temp_qft_2_0_V_fu_904_p2);
    img_proc_mul_mul_bkb_U84 = new img_proc_mul_mul_bkb<1,1,16,6,20>("img_proc_mul_mul_bkb_U84");
    img_proc_mul_mul_bkb_U84->din0(call_ret_i_dct_step_fu_200_ap_return_10);
    img_proc_mul_mul_bkb_U84->din1(buf_temp_qft_2_2_V_fu_911_p1);
    img_proc_mul_mul_bkb_U84->dout(buf_temp_qft_2_2_V_fu_911_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( call_ret_write_data_fu_256_ap_return_0 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( call_ret_write_data_fu_256_ap_return_1 );

    SC_METHOD(thread_ap_return_10);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( call_ret_write_data_fu_256_ap_return_10 );

    SC_METHOD(thread_ap_return_11);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( call_ret_write_data_fu_256_ap_return_11 );

    SC_METHOD(thread_ap_return_12);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( call_ret_write_data_fu_256_ap_return_12 );

    SC_METHOD(thread_ap_return_13);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( call_ret_write_data_fu_256_ap_return_13 );

    SC_METHOD(thread_ap_return_14);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( call_ret_write_data_fu_256_ap_return_14 );

    SC_METHOD(thread_ap_return_15);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( call_ret_write_data_fu_256_ap_return_15 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( call_ret_write_data_fu_256_ap_return_2 );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( call_ret_write_data_fu_256_ap_return_3 );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( call_ret_write_data_fu_256_ap_return_4 );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( call_ret_write_data_fu_256_ap_return_5 );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( call_ret_write_data_fu_256_ap_return_6 );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( call_ret_write_data_fu_256_ap_return_7 );

    SC_METHOD(thread_ap_return_8);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( call_ret_write_data_fu_256_ap_return_8 );

    SC_METHOD(thread_ap_return_9);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( call_ret_write_data_fu_256_ap_return_9 );

    SC_METHOD(thread_buf_temp_qft_0_0_V_fu_890_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_buf_temp_qft_0_2_V_fu_897_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_buf_temp_qft_0_3_V_1_fu_754_p2);
    sensitive << ( buf_temp_qft_0_3_V_fu_545_p2 );

    SC_METHOD(thread_buf_temp_qft_0_3_V_fu_545_p2);
    sensitive << ( p_shl3_i_fu_525_p3 );
    sensitive << ( p_shl4_i_cast_fu_541_p1 );

    SC_METHOD(thread_buf_temp_qft_1_2_V_1_fu_766_p2);
    sensitive << ( buf_temp_qft_1_2_V_fu_607_p2 );

    SC_METHOD(thread_buf_temp_qft_1_2_V_fu_607_p2);
    sensitive << ( p_shl7_i_fu_587_p3 );
    sensitive << ( p_shl8_i_cast_fu_603_p1 );

    SC_METHOD(thread_buf_temp_qft_2_0_V_fu_904_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_buf_temp_qft_2_1_V_1_fu_760_p2);
    sensitive << ( buf_temp_qft_2_1_V_fu_646_p2 );

    SC_METHOD(thread_buf_temp_qft_2_1_V_fu_646_p2);
    sensitive << ( p_shl9_i_fu_626_p3 );
    sensitive << ( p_shl10_i_cast_fu_642_p1 );

    SC_METHOD(thread_buf_temp_qft_2_2_V_fu_911_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_buf_temp_qft_3_0_V_1_fu_772_p2);
    sensitive << ( buf_temp_qft_3_0_V_fu_703_p2 );

    SC_METHOD(thread_buf_temp_qft_3_0_V_fu_703_p2);
    sensitive << ( p_shl14_i_fu_683_p3 );
    sensitive << ( p_shl15_i_cast_fu_699_p1 );

    SC_METHOD(thread_call_ret5_integer_idct_fu_160_src_0_1_V_read);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( p_shl1_i_fu_494_p3 );
    sensitive << ( p_shl2_i_cast_fu_510_p1 );

    SC_METHOD(thread_call_ret5_integer_idct_fu_160_src_0_3_V_read);
    sensitive << ( tmp_reg_998 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( buf_temp_qft_0_3_V_fu_545_p2 );
    sensitive << ( buf_temp_qft_0_3_V_1_fu_754_p2 );

    SC_METHOD(thread_call_ret5_integer_idct_fu_160_src_1_0_V_read);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( p_shl5_i_fu_551_p3 );
    sensitive << ( p_shl6_i_cast_fu_567_p1 );

    SC_METHOD(thread_call_ret5_integer_idct_fu_160_src_1_1_V_read);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_5 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_call_ret5_integer_idct_fu_160_src_1_2_V_read);
    sensitive << ( tmp_reg_998 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( buf_temp_qft_1_2_V_fu_607_p2 );
    sensitive << ( buf_temp_qft_1_2_V_1_fu_766_p2 );

    SC_METHOD(thread_call_ret5_integer_idct_fu_160_src_1_3_V_read);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_7 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_call_ret5_integer_idct_fu_160_src_2_1_V_read);
    sensitive << ( tmp_reg_998 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( buf_temp_qft_2_1_V_fu_646_p2 );
    sensitive << ( buf_temp_qft_2_1_V_1_fu_760_p2 );

    SC_METHOD(thread_call_ret5_integer_idct_fu_160_src_2_3_V_read);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( p_shl11_i_fu_656_p3 );
    sensitive << ( p_shl12_i_cast_fu_672_p1 );

    SC_METHOD(thread_call_ret5_integer_idct_fu_160_src_3_0_V_read);
    sensitive << ( tmp_reg_998 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( buf_temp_qft_3_0_V_fu_703_p2 );
    sensitive << ( buf_temp_qft_3_0_V_1_fu_772_p2 );

    SC_METHOD(thread_call_ret5_integer_idct_fu_160_src_3_1_V_read);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_13 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_call_ret5_integer_idct_fu_160_src_3_2_V_read);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( p_shl_i_fu_718_p3 );
    sensitive << ( p_shl13_i_cast_fu_734_p1 );

    SC_METHOD(thread_call_ret5_integer_idct_fu_160_src_3_3_V_read);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_15 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_p_shl10_i_cast_fu_642_p1);
    sensitive << ( p_shl10_i_fu_634_p3 );

    SC_METHOD(thread_p_shl10_i_fu_634_p3);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_9 );

    SC_METHOD(thread_p_shl11_i_fu_656_p3);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_11 );

    SC_METHOD(thread_p_shl12_i_cast_fu_672_p1);
    sensitive << ( p_shl12_i_fu_664_p3 );

    SC_METHOD(thread_p_shl12_i_fu_664_p3);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_11 );

    SC_METHOD(thread_p_shl13_i_cast_fu_734_p1);
    sensitive << ( p_shl13_i_fu_726_p3 );

    SC_METHOD(thread_p_shl13_i_fu_726_p3);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_14 );

    SC_METHOD(thread_p_shl14_i_fu_683_p3);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_12 );

    SC_METHOD(thread_p_shl15_i_cast_fu_699_p1);
    sensitive << ( p_shl15_i_fu_691_p3 );

    SC_METHOD(thread_p_shl15_i_fu_691_p3);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_12 );

    SC_METHOD(thread_p_shl1_i_fu_494_p3);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_1 );

    SC_METHOD(thread_p_shl2_i_cast_fu_510_p1);
    sensitive << ( p_shl2_i_fu_502_p3 );

    SC_METHOD(thread_p_shl2_i_fu_502_p3);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_1 );

    SC_METHOD(thread_p_shl3_i_fu_525_p3);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_3 );

    SC_METHOD(thread_p_shl4_i_cast_fu_541_p1);
    sensitive << ( p_shl4_i_fu_533_p3 );

    SC_METHOD(thread_p_shl4_i_fu_533_p3);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_3 );

    SC_METHOD(thread_p_shl5_i_fu_551_p3);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_4 );

    SC_METHOD(thread_p_shl6_i_cast_fu_567_p1);
    sensitive << ( p_shl6_i_fu_559_p3 );

    SC_METHOD(thread_p_shl6_i_fu_559_p3);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_4 );

    SC_METHOD(thread_p_shl7_i_fu_587_p3);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_6 );

    SC_METHOD(thread_p_shl8_i_cast_fu_603_p1);
    sensitive << ( p_shl8_i_fu_595_p3 );

    SC_METHOD(thread_p_shl8_i_fu_595_p3);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_6 );

    SC_METHOD(thread_p_shl9_i_fu_626_p3);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_9 );

    SC_METHOD(thread_p_shl_i_fu_718_p3);
    sensitive << ( call_ret_i_dct_step_fu_200_ap_return_14 );

    SC_METHOD(thread_tmp_fu_420_p2);
    sensitive << ( mark );
    sensitive << ( ap_block_pp0_stage0_11001 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "add_watermark_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, indata_0_read, "(port)indata_0_read");
    sc_trace(mVcdFile, indata_1_read, "(port)indata_1_read");
    sc_trace(mVcdFile, indata_2_read, "(port)indata_2_read");
    sc_trace(mVcdFile, indata_3_read, "(port)indata_3_read");
    sc_trace(mVcdFile, indata_4_read, "(port)indata_4_read");
    sc_trace(mVcdFile, indata_5_read, "(port)indata_5_read");
    sc_trace(mVcdFile, indata_6_read, "(port)indata_6_read");
    sc_trace(mVcdFile, indata_7_read, "(port)indata_7_read");
    sc_trace(mVcdFile, indata_8_read, "(port)indata_8_read");
    sc_trace(mVcdFile, indata_9_read, "(port)indata_9_read");
    sc_trace(mVcdFile, indata_10_read, "(port)indata_10_read");
    sc_trace(mVcdFile, indata_11_read, "(port)indata_11_read");
    sc_trace(mVcdFile, indata_12_read, "(port)indata_12_read");
    sc_trace(mVcdFile, indata_13_read, "(port)indata_13_read");
    sc_trace(mVcdFile, indata_14_read, "(port)indata_14_read");
    sc_trace(mVcdFile, indata_15_read, "(port)indata_15_read");
    sc_trace(mVcdFile, mark, "(port)mark");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_return_8, "(port)ap_return_8");
    sc_trace(mVcdFile, ap_return_9, "(port)ap_return_9");
    sc_trace(mVcdFile, ap_return_10, "(port)ap_return_10");
    sc_trace(mVcdFile, ap_return_11, "(port)ap_return_11");
    sc_trace(mVcdFile, ap_return_12, "(port)ap_return_12");
    sc_trace(mVcdFile, ap_return_13, "(port)ap_return_13");
    sc_trace(mVcdFile, ap_return_14, "(port)ap_return_14");
    sc_trace(mVcdFile, ap_return_15, "(port)ap_return_15");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, temp_0_0_reg_918, "temp_0_0_reg_918");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, temp_0_1_reg_923, "temp_0_1_reg_923");
    sc_trace(mVcdFile, temp_0_2_reg_928, "temp_0_2_reg_928");
    sc_trace(mVcdFile, temp_0_3_reg_933, "temp_0_3_reg_933");
    sc_trace(mVcdFile, temp_1_0_reg_938, "temp_1_0_reg_938");
    sc_trace(mVcdFile, temp_1_1_reg_943, "temp_1_1_reg_943");
    sc_trace(mVcdFile, temp_1_2_reg_948, "temp_1_2_reg_948");
    sc_trace(mVcdFile, temp_1_3_reg_953, "temp_1_3_reg_953");
    sc_trace(mVcdFile, temp_2_0_reg_958, "temp_2_0_reg_958");
    sc_trace(mVcdFile, temp_2_1_reg_963, "temp_2_1_reg_963");
    sc_trace(mVcdFile, temp_2_2_reg_968, "temp_2_2_reg_968");
    sc_trace(mVcdFile, temp_2_3_reg_973, "temp_2_3_reg_973");
    sc_trace(mVcdFile, temp_3_0_reg_978, "temp_3_0_reg_978");
    sc_trace(mVcdFile, temp_3_1_reg_983, "temp_3_1_reg_983");
    sc_trace(mVcdFile, temp_3_2_reg_988, "temp_3_2_reg_988");
    sc_trace(mVcdFile, temp_3_3_reg_993, "temp_3_3_reg_993");
    sc_trace(mVcdFile, tmp_fu_420_p2, "tmp_fu_420_p2");
    sc_trace(mVcdFile, tmp_reg_998, "tmp_reg_998");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_ap_ready, "call_ret5_integer_idct_fu_160_ap_ready");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_src_0_1_V_read, "call_ret5_integer_idct_fu_160_src_0_1_V_read");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_src_0_3_V_read, "call_ret5_integer_idct_fu_160_src_0_3_V_read");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_src_1_0_V_read, "call_ret5_integer_idct_fu_160_src_1_0_V_read");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_src_1_1_V_read, "call_ret5_integer_idct_fu_160_src_1_1_V_read");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_src_1_2_V_read, "call_ret5_integer_idct_fu_160_src_1_2_V_read");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_src_1_3_V_read, "call_ret5_integer_idct_fu_160_src_1_3_V_read");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_src_2_1_V_read, "call_ret5_integer_idct_fu_160_src_2_1_V_read");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_src_2_3_V_read, "call_ret5_integer_idct_fu_160_src_2_3_V_read");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_src_3_0_V_read, "call_ret5_integer_idct_fu_160_src_3_0_V_read");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_src_3_1_V_read, "call_ret5_integer_idct_fu_160_src_3_1_V_read");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_src_3_2_V_read, "call_ret5_integer_idct_fu_160_src_3_2_V_read");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_src_3_3_V_read, "call_ret5_integer_idct_fu_160_src_3_3_V_read");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_ap_return_0, "call_ret5_integer_idct_fu_160_ap_return_0");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_ap_return_1, "call_ret5_integer_idct_fu_160_ap_return_1");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_ap_return_2, "call_ret5_integer_idct_fu_160_ap_return_2");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_ap_return_3, "call_ret5_integer_idct_fu_160_ap_return_3");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_ap_return_4, "call_ret5_integer_idct_fu_160_ap_return_4");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_ap_return_5, "call_ret5_integer_idct_fu_160_ap_return_5");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_ap_return_6, "call_ret5_integer_idct_fu_160_ap_return_6");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_ap_return_7, "call_ret5_integer_idct_fu_160_ap_return_7");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_ap_return_8, "call_ret5_integer_idct_fu_160_ap_return_8");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_ap_return_9, "call_ret5_integer_idct_fu_160_ap_return_9");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_ap_return_10, "call_ret5_integer_idct_fu_160_ap_return_10");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_ap_return_11, "call_ret5_integer_idct_fu_160_ap_return_11");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_ap_return_12, "call_ret5_integer_idct_fu_160_ap_return_12");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_ap_return_13, "call_ret5_integer_idct_fu_160_ap_return_13");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_ap_return_14, "call_ret5_integer_idct_fu_160_ap_return_14");
    sc_trace(mVcdFile, call_ret5_integer_idct_fu_160_ap_return_15, "call_ret5_integer_idct_fu_160_ap_return_15");
    sc_trace(mVcdFile, call_ret2_i_dct_step_fu_180_ap_ready, "call_ret2_i_dct_step_fu_180_ap_ready");
    sc_trace(mVcdFile, call_ret2_i_dct_step_fu_180_ap_return_0, "call_ret2_i_dct_step_fu_180_ap_return_0");
    sc_trace(mVcdFile, call_ret2_i_dct_step_fu_180_ap_return_1, "call_ret2_i_dct_step_fu_180_ap_return_1");
    sc_trace(mVcdFile, call_ret2_i_dct_step_fu_180_ap_return_2, "call_ret2_i_dct_step_fu_180_ap_return_2");
    sc_trace(mVcdFile, call_ret2_i_dct_step_fu_180_ap_return_3, "call_ret2_i_dct_step_fu_180_ap_return_3");
    sc_trace(mVcdFile, call_ret2_i_dct_step_fu_180_ap_return_4, "call_ret2_i_dct_step_fu_180_ap_return_4");
    sc_trace(mVcdFile, call_ret2_i_dct_step_fu_180_ap_return_5, "call_ret2_i_dct_step_fu_180_ap_return_5");
    sc_trace(mVcdFile, call_ret2_i_dct_step_fu_180_ap_return_6, "call_ret2_i_dct_step_fu_180_ap_return_6");
    sc_trace(mVcdFile, call_ret2_i_dct_step_fu_180_ap_return_7, "call_ret2_i_dct_step_fu_180_ap_return_7");
    sc_trace(mVcdFile, call_ret2_i_dct_step_fu_180_ap_return_8, "call_ret2_i_dct_step_fu_180_ap_return_8");
    sc_trace(mVcdFile, call_ret2_i_dct_step_fu_180_ap_return_9, "call_ret2_i_dct_step_fu_180_ap_return_9");
    sc_trace(mVcdFile, call_ret2_i_dct_step_fu_180_ap_return_10, "call_ret2_i_dct_step_fu_180_ap_return_10");
    sc_trace(mVcdFile, call_ret2_i_dct_step_fu_180_ap_return_11, "call_ret2_i_dct_step_fu_180_ap_return_11");
    sc_trace(mVcdFile, call_ret2_i_dct_step_fu_180_ap_return_12, "call_ret2_i_dct_step_fu_180_ap_return_12");
    sc_trace(mVcdFile, call_ret2_i_dct_step_fu_180_ap_return_13, "call_ret2_i_dct_step_fu_180_ap_return_13");
    sc_trace(mVcdFile, call_ret2_i_dct_step_fu_180_ap_return_14, "call_ret2_i_dct_step_fu_180_ap_return_14");
    sc_trace(mVcdFile, call_ret2_i_dct_step_fu_180_ap_return_15, "call_ret2_i_dct_step_fu_180_ap_return_15");
    sc_trace(mVcdFile, call_ret_i_dct_step_fu_200_ap_ready, "call_ret_i_dct_step_fu_200_ap_ready");
    sc_trace(mVcdFile, call_ret_i_dct_step_fu_200_ap_return_0, "call_ret_i_dct_step_fu_200_ap_return_0");
    sc_trace(mVcdFile, call_ret_i_dct_step_fu_200_ap_return_1, "call_ret_i_dct_step_fu_200_ap_return_1");
    sc_trace(mVcdFile, call_ret_i_dct_step_fu_200_ap_return_2, "call_ret_i_dct_step_fu_200_ap_return_2");
    sc_trace(mVcdFile, call_ret_i_dct_step_fu_200_ap_return_3, "call_ret_i_dct_step_fu_200_ap_return_3");
    sc_trace(mVcdFile, call_ret_i_dct_step_fu_200_ap_return_4, "call_ret_i_dct_step_fu_200_ap_return_4");
    sc_trace(mVcdFile, call_ret_i_dct_step_fu_200_ap_return_5, "call_ret_i_dct_step_fu_200_ap_return_5");
    sc_trace(mVcdFile, call_ret_i_dct_step_fu_200_ap_return_6, "call_ret_i_dct_step_fu_200_ap_return_6");
    sc_trace(mVcdFile, call_ret_i_dct_step_fu_200_ap_return_7, "call_ret_i_dct_step_fu_200_ap_return_7");
    sc_trace(mVcdFile, call_ret_i_dct_step_fu_200_ap_return_8, "call_ret_i_dct_step_fu_200_ap_return_8");
    sc_trace(mVcdFile, call_ret_i_dct_step_fu_200_ap_return_9, "call_ret_i_dct_step_fu_200_ap_return_9");
    sc_trace(mVcdFile, call_ret_i_dct_step_fu_200_ap_return_10, "call_ret_i_dct_step_fu_200_ap_return_10");
    sc_trace(mVcdFile, call_ret_i_dct_step_fu_200_ap_return_11, "call_ret_i_dct_step_fu_200_ap_return_11");
    sc_trace(mVcdFile, call_ret_i_dct_step_fu_200_ap_return_12, "call_ret_i_dct_step_fu_200_ap_return_12");
    sc_trace(mVcdFile, call_ret_i_dct_step_fu_200_ap_return_13, "call_ret_i_dct_step_fu_200_ap_return_13");
    sc_trace(mVcdFile, call_ret_i_dct_step_fu_200_ap_return_14, "call_ret_i_dct_step_fu_200_ap_return_14");
    sc_trace(mVcdFile, call_ret_i_dct_step_fu_200_ap_return_15, "call_ret_i_dct_step_fu_200_ap_return_15");
    sc_trace(mVcdFile, call_ret3_read_data_fu_220_ap_ready, "call_ret3_read_data_fu_220_ap_ready");
    sc_trace(mVcdFile, call_ret3_read_data_fu_220_ap_return_0, "call_ret3_read_data_fu_220_ap_return_0");
    sc_trace(mVcdFile, call_ret3_read_data_fu_220_ap_return_1, "call_ret3_read_data_fu_220_ap_return_1");
    sc_trace(mVcdFile, call_ret3_read_data_fu_220_ap_return_2, "call_ret3_read_data_fu_220_ap_return_2");
    sc_trace(mVcdFile, call_ret3_read_data_fu_220_ap_return_3, "call_ret3_read_data_fu_220_ap_return_3");
    sc_trace(mVcdFile, call_ret3_read_data_fu_220_ap_return_4, "call_ret3_read_data_fu_220_ap_return_4");
    sc_trace(mVcdFile, call_ret3_read_data_fu_220_ap_return_5, "call_ret3_read_data_fu_220_ap_return_5");
    sc_trace(mVcdFile, call_ret3_read_data_fu_220_ap_return_6, "call_ret3_read_data_fu_220_ap_return_6");
    sc_trace(mVcdFile, call_ret3_read_data_fu_220_ap_return_7, "call_ret3_read_data_fu_220_ap_return_7");
    sc_trace(mVcdFile, call_ret3_read_data_fu_220_ap_return_8, "call_ret3_read_data_fu_220_ap_return_8");
    sc_trace(mVcdFile, call_ret3_read_data_fu_220_ap_return_9, "call_ret3_read_data_fu_220_ap_return_9");
    sc_trace(mVcdFile, call_ret3_read_data_fu_220_ap_return_10, "call_ret3_read_data_fu_220_ap_return_10");
    sc_trace(mVcdFile, call_ret3_read_data_fu_220_ap_return_11, "call_ret3_read_data_fu_220_ap_return_11");
    sc_trace(mVcdFile, call_ret3_read_data_fu_220_ap_return_12, "call_ret3_read_data_fu_220_ap_return_12");
    sc_trace(mVcdFile, call_ret3_read_data_fu_220_ap_return_13, "call_ret3_read_data_fu_220_ap_return_13");
    sc_trace(mVcdFile, call_ret3_read_data_fu_220_ap_return_14, "call_ret3_read_data_fu_220_ap_return_14");
    sc_trace(mVcdFile, call_ret3_read_data_fu_220_ap_return_15, "call_ret3_read_data_fu_220_ap_return_15");
    sc_trace(mVcdFile, call_ret_write_data_fu_256_ap_ready, "call_ret_write_data_fu_256_ap_ready");
    sc_trace(mVcdFile, call_ret_write_data_fu_256_ap_return_0, "call_ret_write_data_fu_256_ap_return_0");
    sc_trace(mVcdFile, call_ret_write_data_fu_256_ap_return_1, "call_ret_write_data_fu_256_ap_return_1");
    sc_trace(mVcdFile, call_ret_write_data_fu_256_ap_return_2, "call_ret_write_data_fu_256_ap_return_2");
    sc_trace(mVcdFile, call_ret_write_data_fu_256_ap_return_3, "call_ret_write_data_fu_256_ap_return_3");
    sc_trace(mVcdFile, call_ret_write_data_fu_256_ap_return_4, "call_ret_write_data_fu_256_ap_return_4");
    sc_trace(mVcdFile, call_ret_write_data_fu_256_ap_return_5, "call_ret_write_data_fu_256_ap_return_5");
    sc_trace(mVcdFile, call_ret_write_data_fu_256_ap_return_6, "call_ret_write_data_fu_256_ap_return_6");
    sc_trace(mVcdFile, call_ret_write_data_fu_256_ap_return_7, "call_ret_write_data_fu_256_ap_return_7");
    sc_trace(mVcdFile, call_ret_write_data_fu_256_ap_return_8, "call_ret_write_data_fu_256_ap_return_8");
    sc_trace(mVcdFile, call_ret_write_data_fu_256_ap_return_9, "call_ret_write_data_fu_256_ap_return_9");
    sc_trace(mVcdFile, call_ret_write_data_fu_256_ap_return_10, "call_ret_write_data_fu_256_ap_return_10");
    sc_trace(mVcdFile, call_ret_write_data_fu_256_ap_return_11, "call_ret_write_data_fu_256_ap_return_11");
    sc_trace(mVcdFile, call_ret_write_data_fu_256_ap_return_12, "call_ret_write_data_fu_256_ap_return_12");
    sc_trace(mVcdFile, call_ret_write_data_fu_256_ap_return_13, "call_ret_write_data_fu_256_ap_return_13");
    sc_trace(mVcdFile, call_ret_write_data_fu_256_ap_return_14, "call_ret_write_data_fu_256_ap_return_14");
    sc_trace(mVcdFile, call_ret_write_data_fu_256_ap_return_15, "call_ret_write_data_fu_256_ap_return_15");
    sc_trace(mVcdFile, buf_temp_qft_0_0_V_fu_890_p2, "buf_temp_qft_0_0_V_fu_890_p2");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, buf_temp_qft_0_2_V_fu_897_p2, "buf_temp_qft_0_2_V_fu_897_p2");
    sc_trace(mVcdFile, buf_temp_qft_2_0_V_fu_904_p2, "buf_temp_qft_2_0_V_fu_904_p2");
    sc_trace(mVcdFile, buf_temp_qft_2_2_V_fu_911_p2, "buf_temp_qft_2_2_V_fu_911_p2");
    sc_trace(mVcdFile, p_shl2_i_fu_502_p3, "p_shl2_i_fu_502_p3");
    sc_trace(mVcdFile, p_shl1_i_fu_494_p3, "p_shl1_i_fu_494_p3");
    sc_trace(mVcdFile, p_shl2_i_cast_fu_510_p1, "p_shl2_i_cast_fu_510_p1");
    sc_trace(mVcdFile, p_shl4_i_fu_533_p3, "p_shl4_i_fu_533_p3");
    sc_trace(mVcdFile, p_shl3_i_fu_525_p3, "p_shl3_i_fu_525_p3");
    sc_trace(mVcdFile, p_shl4_i_cast_fu_541_p1, "p_shl4_i_cast_fu_541_p1");
    sc_trace(mVcdFile, p_shl6_i_fu_559_p3, "p_shl6_i_fu_559_p3");
    sc_trace(mVcdFile, p_shl5_i_fu_551_p3, "p_shl5_i_fu_551_p3");
    sc_trace(mVcdFile, p_shl6_i_cast_fu_567_p1, "p_shl6_i_cast_fu_567_p1");
    sc_trace(mVcdFile, p_shl8_i_fu_595_p3, "p_shl8_i_fu_595_p3");
    sc_trace(mVcdFile, p_shl7_i_fu_587_p3, "p_shl7_i_fu_587_p3");
    sc_trace(mVcdFile, p_shl8_i_cast_fu_603_p1, "p_shl8_i_cast_fu_603_p1");
    sc_trace(mVcdFile, p_shl10_i_fu_634_p3, "p_shl10_i_fu_634_p3");
    sc_trace(mVcdFile, p_shl9_i_fu_626_p3, "p_shl9_i_fu_626_p3");
    sc_trace(mVcdFile, p_shl10_i_cast_fu_642_p1, "p_shl10_i_cast_fu_642_p1");
    sc_trace(mVcdFile, p_shl12_i_fu_664_p3, "p_shl12_i_fu_664_p3");
    sc_trace(mVcdFile, p_shl11_i_fu_656_p3, "p_shl11_i_fu_656_p3");
    sc_trace(mVcdFile, p_shl12_i_cast_fu_672_p1, "p_shl12_i_cast_fu_672_p1");
    sc_trace(mVcdFile, p_shl15_i_fu_691_p3, "p_shl15_i_fu_691_p3");
    sc_trace(mVcdFile, p_shl14_i_fu_683_p3, "p_shl14_i_fu_683_p3");
    sc_trace(mVcdFile, p_shl15_i_cast_fu_699_p1, "p_shl15_i_cast_fu_699_p1");
    sc_trace(mVcdFile, p_shl13_i_fu_726_p3, "p_shl13_i_fu_726_p3");
    sc_trace(mVcdFile, p_shl_i_fu_718_p3, "p_shl_i_fu_718_p3");
    sc_trace(mVcdFile, p_shl13_i_cast_fu_734_p1, "p_shl13_i_cast_fu_734_p1");
    sc_trace(mVcdFile, buf_temp_qft_0_3_V_fu_545_p2, "buf_temp_qft_0_3_V_fu_545_p2");
    sc_trace(mVcdFile, buf_temp_qft_2_1_V_fu_646_p2, "buf_temp_qft_2_1_V_fu_646_p2");
    sc_trace(mVcdFile, buf_temp_qft_1_2_V_fu_607_p2, "buf_temp_qft_1_2_V_fu_607_p2");
    sc_trace(mVcdFile, buf_temp_qft_3_0_V_fu_703_p2, "buf_temp_qft_3_0_V_fu_703_p2");
    sc_trace(mVcdFile, buf_temp_qft_3_0_V_1_fu_772_p2, "buf_temp_qft_3_0_V_1_fu_772_p2");
    sc_trace(mVcdFile, buf_temp_qft_2_1_V_1_fu_760_p2, "buf_temp_qft_2_1_V_1_fu_760_p2");
    sc_trace(mVcdFile, buf_temp_qft_1_2_V_1_fu_766_p2, "buf_temp_qft_1_2_V_1_fu_766_p2");
    sc_trace(mVcdFile, buf_temp_qft_0_3_V_1_fu_754_p2, "buf_temp_qft_0_3_V_1_fu_754_p2");
    sc_trace(mVcdFile, buf_temp_qft_0_0_V_fu_890_p1, "buf_temp_qft_0_0_V_fu_890_p1");
    sc_trace(mVcdFile, buf_temp_qft_0_2_V_fu_897_p1, "buf_temp_qft_0_2_V_fu_897_p1");
    sc_trace(mVcdFile, buf_temp_qft_2_0_V_fu_904_p1, "buf_temp_qft_2_0_V_fu_904_p1");
    sc_trace(mVcdFile, buf_temp_qft_2_2_V_fu_911_p1, "buf_temp_qft_2_2_V_fu_911_p1");
#endif

    }
}

add_watermark::~add_watermark() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete call_ret5_integer_idct_fu_160;
    delete call_ret2_i_dct_step_fu_180;
    delete call_ret_i_dct_step_fu_200;
    delete call_ret3_read_data_fu_220;
    delete call_ret_write_data_fu_256;
    delete img_proc_mul_mul_bkb_U81;
    delete img_proc_mul_mul_bkb_U82;
    delete img_proc_mul_mul_bkb_U83;
    delete img_proc_mul_mul_bkb_U84;
}

void add_watermark::thread_ap_clk_no_reset_() {
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        temp_0_0_reg_918 = call_ret2_i_dct_step_fu_180_ap_return_0.read();
        temp_0_1_reg_923 = call_ret2_i_dct_step_fu_180_ap_return_1.read();
        temp_0_2_reg_928 = call_ret2_i_dct_step_fu_180_ap_return_2.read();
        temp_0_3_reg_933 = call_ret2_i_dct_step_fu_180_ap_return_3.read();
        temp_1_0_reg_938 = call_ret2_i_dct_step_fu_180_ap_return_4.read();
        temp_1_1_reg_943 = call_ret2_i_dct_step_fu_180_ap_return_5.read();
        temp_1_2_reg_948 = call_ret2_i_dct_step_fu_180_ap_return_6.read();
        temp_1_3_reg_953 = call_ret2_i_dct_step_fu_180_ap_return_7.read();
        temp_2_0_reg_958 = call_ret2_i_dct_step_fu_180_ap_return_8.read();
        temp_2_1_reg_963 = call_ret2_i_dct_step_fu_180_ap_return_9.read();
        temp_2_2_reg_968 = call_ret2_i_dct_step_fu_180_ap_return_10.read();
        temp_2_3_reg_973 = call_ret2_i_dct_step_fu_180_ap_return_11.read();
        temp_3_0_reg_978 = call_ret2_i_dct_step_fu_180_ap_return_12.read();
        temp_3_1_reg_983 = call_ret2_i_dct_step_fu_180_ap_return_13.read();
        temp_3_2_reg_988 = call_ret2_i_dct_step_fu_180_ap_return_14.read();
        temp_3_3_reg_993 = call_ret2_i_dct_step_fu_180_ap_return_15.read();
        tmp_reg_998 = tmp_fu_420_p2.read();
    }
}

void add_watermark::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void add_watermark::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void add_watermark::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void add_watermark::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void add_watermark::thread_ap_return_0() {
    ap_return_0 = call_ret_write_data_fu_256_ap_return_0.read();
}

void add_watermark::thread_ap_return_1() {
    ap_return_1 = call_ret_write_data_fu_256_ap_return_1.read();
}

void add_watermark::thread_ap_return_10() {
    ap_return_10 = call_ret_write_data_fu_256_ap_return_10.read();
}

void add_watermark::thread_ap_return_11() {
    ap_return_11 = call_ret_write_data_fu_256_ap_return_11.read();
}

void add_watermark::thread_ap_return_12() {
    ap_return_12 = call_ret_write_data_fu_256_ap_return_12.read();
}

void add_watermark::thread_ap_return_13() {
    ap_return_13 = call_ret_write_data_fu_256_ap_return_13.read();
}

void add_watermark::thread_ap_return_14() {
    ap_return_14 = call_ret_write_data_fu_256_ap_return_14.read();
}

void add_watermark::thread_ap_return_15() {
    ap_return_15 = call_ret_write_data_fu_256_ap_return_15.read();
}

void add_watermark::thread_ap_return_2() {
    ap_return_2 = call_ret_write_data_fu_256_ap_return_2.read();
}

void add_watermark::thread_ap_return_3() {
    ap_return_3 = call_ret_write_data_fu_256_ap_return_3.read();
}

void add_watermark::thread_ap_return_4() {
    ap_return_4 = call_ret_write_data_fu_256_ap_return_4.read();
}

void add_watermark::thread_ap_return_5() {
    ap_return_5 = call_ret_write_data_fu_256_ap_return_5.read();
}

void add_watermark::thread_ap_return_6() {
    ap_return_6 = call_ret_write_data_fu_256_ap_return_6.read();
}

void add_watermark::thread_ap_return_7() {
    ap_return_7 = call_ret_write_data_fu_256_ap_return_7.read();
}

void add_watermark::thread_ap_return_8() {
    ap_return_8 = call_ret_write_data_fu_256_ap_return_8.read();
}

void add_watermark::thread_ap_return_9() {
    ap_return_9 = call_ret_write_data_fu_256_ap_return_9.read();
}

void add_watermark::thread_buf_temp_qft_0_0_V_fu_890_p1() {
    buf_temp_qft_0_0_V_fu_890_p1 =  (sc_lv<6>) (ap_const_lv20_19);
}

void add_watermark::thread_buf_temp_qft_0_2_V_fu_897_p1() {
    buf_temp_qft_0_2_V_fu_897_p1 =  (sc_lv<6>) (ap_const_lv20_19);
}

void add_watermark::thread_buf_temp_qft_0_3_V_1_fu_754_p2() {
    buf_temp_qft_0_3_V_1_fu_754_p2 = (!buf_temp_qft_0_3_V_fu_545_p2.read().is_01() || !ap_const_lv20_A.is_01())? sc_lv<20>(): (sc_biguint<20>(buf_temp_qft_0_3_V_fu_545_p2.read()) + sc_biguint<20>(ap_const_lv20_A));
}

void add_watermark::thread_buf_temp_qft_0_3_V_fu_545_p2() {
    buf_temp_qft_0_3_V_fu_545_p2 = (!p_shl3_i_fu_525_p3.read().is_01() || !p_shl4_i_cast_fu_541_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(p_shl3_i_fu_525_p3.read()) + sc_bigint<20>(p_shl4_i_cast_fu_541_p1.read()));
}

void add_watermark::thread_buf_temp_qft_1_2_V_1_fu_766_p2() {
    buf_temp_qft_1_2_V_1_fu_766_p2 = (!buf_temp_qft_1_2_V_fu_607_p2.read().is_01() || !ap_const_lv20_A.is_01())? sc_lv<20>(): (sc_biguint<20>(buf_temp_qft_1_2_V_fu_607_p2.read()) + sc_biguint<20>(ap_const_lv20_A));
}

void add_watermark::thread_buf_temp_qft_1_2_V_fu_607_p2() {
    buf_temp_qft_1_2_V_fu_607_p2 = (!p_shl7_i_fu_587_p3.read().is_01() || !p_shl8_i_cast_fu_603_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(p_shl7_i_fu_587_p3.read()) + sc_bigint<20>(p_shl8_i_cast_fu_603_p1.read()));
}

void add_watermark::thread_buf_temp_qft_2_0_V_fu_904_p1() {
    buf_temp_qft_2_0_V_fu_904_p1 =  (sc_lv<6>) (ap_const_lv20_19);
}

void add_watermark::thread_buf_temp_qft_2_1_V_1_fu_760_p2() {
    buf_temp_qft_2_1_V_1_fu_760_p2 = (!buf_temp_qft_2_1_V_fu_646_p2.read().is_01() || !ap_const_lv20_A.is_01())? sc_lv<20>(): (sc_biguint<20>(buf_temp_qft_2_1_V_fu_646_p2.read()) + sc_biguint<20>(ap_const_lv20_A));
}

void add_watermark::thread_buf_temp_qft_2_1_V_fu_646_p2() {
    buf_temp_qft_2_1_V_fu_646_p2 = (!p_shl9_i_fu_626_p3.read().is_01() || !p_shl10_i_cast_fu_642_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(p_shl9_i_fu_626_p3.read()) + sc_bigint<20>(p_shl10_i_cast_fu_642_p1.read()));
}

void add_watermark::thread_buf_temp_qft_2_2_V_fu_911_p1() {
    buf_temp_qft_2_2_V_fu_911_p1 =  (sc_lv<6>) (ap_const_lv20_19);
}

void add_watermark::thread_buf_temp_qft_3_0_V_1_fu_772_p2() {
    buf_temp_qft_3_0_V_1_fu_772_p2 = (!buf_temp_qft_3_0_V_fu_703_p2.read().is_01() || !ap_const_lv20_A.is_01())? sc_lv<20>(): (sc_biguint<20>(buf_temp_qft_3_0_V_fu_703_p2.read()) + sc_biguint<20>(ap_const_lv20_A));
}

void add_watermark::thread_buf_temp_qft_3_0_V_fu_703_p2() {
    buf_temp_qft_3_0_V_fu_703_p2 = (!p_shl14_i_fu_683_p3.read().is_01() || !p_shl15_i_cast_fu_699_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(p_shl14_i_fu_683_p3.read()) + sc_bigint<20>(p_shl15_i_cast_fu_699_p1.read()));
}

void add_watermark::thread_call_ret5_integer_idct_fu_160_src_0_1_V_read() {
    call_ret5_integer_idct_fu_160_src_0_1_V_read = (!p_shl1_i_fu_494_p3.read().is_01() || !p_shl2_i_cast_fu_510_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(p_shl1_i_fu_494_p3.read()) + sc_bigint<20>(p_shl2_i_cast_fu_510_p1.read()));
}

void add_watermark::thread_call_ret5_integer_idct_fu_160_src_0_3_V_read() {
    call_ret5_integer_idct_fu_160_src_0_3_V_read = (!tmp_reg_998.read()[0].is_01())? sc_lv<20>(): ((tmp_reg_998.read()[0].to_bool())? buf_temp_qft_0_3_V_1_fu_754_p2.read(): buf_temp_qft_0_3_V_fu_545_p2.read());
}

void add_watermark::thread_call_ret5_integer_idct_fu_160_src_1_0_V_read() {
    call_ret5_integer_idct_fu_160_src_1_0_V_read = (!p_shl5_i_fu_551_p3.read().is_01() || !p_shl6_i_cast_fu_567_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(p_shl5_i_fu_551_p3.read()) + sc_bigint<20>(p_shl6_i_cast_fu_567_p1.read()));
}

void add_watermark::thread_call_ret5_integer_idct_fu_160_src_1_1_V_read() {
    call_ret5_integer_idct_fu_160_src_1_1_V_read = esl_concat<16,4>(call_ret_i_dct_step_fu_200_ap_return_5.read(), ap_const_lv4_0);
}

void add_watermark::thread_call_ret5_integer_idct_fu_160_src_1_2_V_read() {
    call_ret5_integer_idct_fu_160_src_1_2_V_read = (!tmp_reg_998.read()[0].is_01())? sc_lv<20>(): ((tmp_reg_998.read()[0].to_bool())? buf_temp_qft_1_2_V_fu_607_p2.read(): buf_temp_qft_1_2_V_1_fu_766_p2.read());
}

void add_watermark::thread_call_ret5_integer_idct_fu_160_src_1_3_V_read() {
    call_ret5_integer_idct_fu_160_src_1_3_V_read = esl_concat<16,4>(call_ret_i_dct_step_fu_200_ap_return_7.read(), ap_const_lv4_0);
}

void add_watermark::thread_call_ret5_integer_idct_fu_160_src_2_1_V_read() {
    call_ret5_integer_idct_fu_160_src_2_1_V_read = (!tmp_reg_998.read()[0].is_01())? sc_lv<20>(): ((tmp_reg_998.read()[0].to_bool())? buf_temp_qft_2_1_V_1_fu_760_p2.read(): buf_temp_qft_2_1_V_fu_646_p2.read());
}

void add_watermark::thread_call_ret5_integer_idct_fu_160_src_2_3_V_read() {
    call_ret5_integer_idct_fu_160_src_2_3_V_read = (!p_shl11_i_fu_656_p3.read().is_01() || !p_shl12_i_cast_fu_672_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(p_shl11_i_fu_656_p3.read()) + sc_bigint<20>(p_shl12_i_cast_fu_672_p1.read()));
}

void add_watermark::thread_call_ret5_integer_idct_fu_160_src_3_0_V_read() {
    call_ret5_integer_idct_fu_160_src_3_0_V_read = (!tmp_reg_998.read()[0].is_01())? sc_lv<20>(): ((tmp_reg_998.read()[0].to_bool())? buf_temp_qft_3_0_V_fu_703_p2.read(): buf_temp_qft_3_0_V_1_fu_772_p2.read());
}

void add_watermark::thread_call_ret5_integer_idct_fu_160_src_3_1_V_read() {
    call_ret5_integer_idct_fu_160_src_3_1_V_read = esl_concat<16,4>(call_ret_i_dct_step_fu_200_ap_return_13.read(), ap_const_lv4_0);
}

void add_watermark::thread_call_ret5_integer_idct_fu_160_src_3_2_V_read() {
    call_ret5_integer_idct_fu_160_src_3_2_V_read = (!p_shl_i_fu_718_p3.read().is_01() || !p_shl13_i_cast_fu_734_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(p_shl_i_fu_718_p3.read()) + sc_bigint<20>(p_shl13_i_cast_fu_734_p1.read()));
}

void add_watermark::thread_call_ret5_integer_idct_fu_160_src_3_3_V_read() {
    call_ret5_integer_idct_fu_160_src_3_3_V_read = esl_concat<16,4>(call_ret_i_dct_step_fu_200_ap_return_15.read(), ap_const_lv4_0);
}

void add_watermark::thread_p_shl10_i_cast_fu_642_p1() {
    p_shl10_i_cast_fu_642_p1 = esl_sext<20,18>(p_shl10_i_fu_634_p3.read());
}

void add_watermark::thread_p_shl10_i_fu_634_p3() {
    p_shl10_i_fu_634_p3 = esl_concat<16,2>(call_ret_i_dct_step_fu_200_ap_return_9.read(), ap_const_lv2_0);
}

void add_watermark::thread_p_shl11_i_fu_656_p3() {
    p_shl11_i_fu_656_p3 = esl_concat<16,4>(call_ret_i_dct_step_fu_200_ap_return_11.read(), ap_const_lv4_0);
}

void add_watermark::thread_p_shl12_i_cast_fu_672_p1() {
    p_shl12_i_cast_fu_672_p1 = esl_sext<20,18>(p_shl12_i_fu_664_p3.read());
}

void add_watermark::thread_p_shl12_i_fu_664_p3() {
    p_shl12_i_fu_664_p3 = esl_concat<16,2>(call_ret_i_dct_step_fu_200_ap_return_11.read(), ap_const_lv2_0);
}

void add_watermark::thread_p_shl13_i_cast_fu_734_p1() {
    p_shl13_i_cast_fu_734_p1 = esl_sext<20,18>(p_shl13_i_fu_726_p3.read());
}

void add_watermark::thread_p_shl13_i_fu_726_p3() {
    p_shl13_i_fu_726_p3 = esl_concat<16,2>(call_ret_i_dct_step_fu_200_ap_return_14.read(), ap_const_lv2_0);
}

void add_watermark::thread_p_shl14_i_fu_683_p3() {
    p_shl14_i_fu_683_p3 = esl_concat<16,4>(call_ret_i_dct_step_fu_200_ap_return_12.read(), ap_const_lv4_0);
}

void add_watermark::thread_p_shl15_i_cast_fu_699_p1() {
    p_shl15_i_cast_fu_699_p1 = esl_sext<20,18>(p_shl15_i_fu_691_p3.read());
}

void add_watermark::thread_p_shl15_i_fu_691_p3() {
    p_shl15_i_fu_691_p3 = esl_concat<16,2>(call_ret_i_dct_step_fu_200_ap_return_12.read(), ap_const_lv2_0);
}

void add_watermark::thread_p_shl1_i_fu_494_p3() {
    p_shl1_i_fu_494_p3 = esl_concat<16,4>(call_ret_i_dct_step_fu_200_ap_return_1.read(), ap_const_lv4_0);
}

void add_watermark::thread_p_shl2_i_cast_fu_510_p1() {
    p_shl2_i_cast_fu_510_p1 = esl_sext<20,18>(p_shl2_i_fu_502_p3.read());
}

void add_watermark::thread_p_shl2_i_fu_502_p3() {
    p_shl2_i_fu_502_p3 = esl_concat<16,2>(call_ret_i_dct_step_fu_200_ap_return_1.read(), ap_const_lv2_0);
}

void add_watermark::thread_p_shl3_i_fu_525_p3() {
    p_shl3_i_fu_525_p3 = esl_concat<16,4>(call_ret_i_dct_step_fu_200_ap_return_3.read(), ap_const_lv4_0);
}

void add_watermark::thread_p_shl4_i_cast_fu_541_p1() {
    p_shl4_i_cast_fu_541_p1 = esl_sext<20,18>(p_shl4_i_fu_533_p3.read());
}

void add_watermark::thread_p_shl4_i_fu_533_p3() {
    p_shl4_i_fu_533_p3 = esl_concat<16,2>(call_ret_i_dct_step_fu_200_ap_return_3.read(), ap_const_lv2_0);
}

void add_watermark::thread_p_shl5_i_fu_551_p3() {
    p_shl5_i_fu_551_p3 = esl_concat<16,4>(call_ret_i_dct_step_fu_200_ap_return_4.read(), ap_const_lv4_0);
}

void add_watermark::thread_p_shl6_i_cast_fu_567_p1() {
    p_shl6_i_cast_fu_567_p1 = esl_sext<20,18>(p_shl6_i_fu_559_p3.read());
}

void add_watermark::thread_p_shl6_i_fu_559_p3() {
    p_shl6_i_fu_559_p3 = esl_concat<16,2>(call_ret_i_dct_step_fu_200_ap_return_4.read(), ap_const_lv2_0);
}

void add_watermark::thread_p_shl7_i_fu_587_p3() {
    p_shl7_i_fu_587_p3 = esl_concat<16,4>(call_ret_i_dct_step_fu_200_ap_return_6.read(), ap_const_lv4_0);
}

void add_watermark::thread_p_shl8_i_cast_fu_603_p1() {
    p_shl8_i_cast_fu_603_p1 = esl_sext<20,18>(p_shl8_i_fu_595_p3.read());
}

void add_watermark::thread_p_shl8_i_fu_595_p3() {
    p_shl8_i_fu_595_p3 = esl_concat<16,2>(call_ret_i_dct_step_fu_200_ap_return_6.read(), ap_const_lv2_0);
}

void add_watermark::thread_p_shl9_i_fu_626_p3() {
    p_shl9_i_fu_626_p3 = esl_concat<16,4>(call_ret_i_dct_step_fu_200_ap_return_9.read(), ap_const_lv4_0);
}

void add_watermark::thread_p_shl_i_fu_718_p3() {
    p_shl_i_fu_718_p3 = esl_concat<16,4>(call_ret_i_dct_step_fu_200_ap_return_14.read(), ap_const_lv4_0);
}

void add_watermark::thread_tmp_fu_420_p2() {
    tmp_fu_420_p2 = (!mark.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(mark.read() == ap_const_lv8_0);
}

}

