-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity integer_idct is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    src_0_0_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
    src_0_1_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
    src_0_2_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
    src_0_3_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
    src_1_0_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
    src_1_1_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
    src_1_2_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
    src_1_3_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
    src_2_0_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
    src_2_1_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
    src_2_2_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
    src_2_3_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
    src_3_0_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
    src_3_1_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
    src_3_2_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
    src_3_3_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
    out_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_r_ce0 : OUT STD_LOGIC;
    out_r_we0 : OUT STD_LOGIC;
    out_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_r_ce1 : OUT STD_LOGIC;
    out_r_we1 : OUT STD_LOGIC;
    out_r_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of integer_idct is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv64_8 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv64_9 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001001";
    constant ap_const_lv64_A : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv64_B : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001011";
    constant ap_const_lv64_C : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv64_D : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001101";
    constant ap_const_lv64_E : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv64_F : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001111";
    constant ap_const_lv19_400 : STD_LOGIC_VECTOR (18 downto 0) := "0000000010000000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv21_1000 : STD_LOGIC_VECTOR (20 downto 0) := "000000001000000000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv21_8000 : STD_LOGIC_VECTOR (20 downto 0) := "000001000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal tmp_11_0_2_fu_751_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_0_2_reg_1693 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_0_3_fu_823_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_0_3_reg_1698 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_1_fu_895_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_1_reg_1703 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_1_1_fu_967_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_1_1_reg_1708 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_1_2_fu_1039_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_1_2_reg_1713 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_1_3_fu_1111_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_1_3_reg_1718 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_2_fu_1183_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_2_reg_1723 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_2_1_fu_1255_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_2_1_reg_1728 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_2_2_fu_1327_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_2_2_reg_1733 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_2_3_fu_1399_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_2_3_reg_1738 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_3_fu_1471_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_3_reg_1743 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_3_1_fu_1543_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_3_1_reg_1748 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_3_2_fu_1615_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_3_2_reg_1753 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_3_3_fu_1687_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_3_3_reg_1758 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret1_idct_step_fu_339_ap_ready : STD_LOGIC;
    signal call_ret1_idct_step_fu_339_ap_return_0 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret1_idct_step_fu_339_ap_return_1 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret1_idct_step_fu_339_ap_return_2 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret1_idct_step_fu_339_ap_return_3 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret1_idct_step_fu_339_ap_return_4 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret1_idct_step_fu_339_ap_return_5 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret1_idct_step_fu_339_ap_return_6 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret1_idct_step_fu_339_ap_return_7 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret1_idct_step_fu_339_ap_return_8 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret1_idct_step_fu_339_ap_return_9 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret1_idct_step_fu_339_ap_return_10 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret1_idct_step_fu_339_ap_return_11 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret1_idct_step_fu_339_ap_return_12 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret1_idct_step_fu_339_ap_return_13 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret1_idct_step_fu_339_ap_return_14 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret1_idct_step_fu_339_ap_return_15 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret_idct_step_fu_375_ap_ready : STD_LOGIC;
    signal call_ret_idct_step_fu_375_ap_return_0 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret_idct_step_fu_375_ap_return_1 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret_idct_step_fu_375_ap_return_2 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret_idct_step_fu_375_ap_return_3 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret_idct_step_fu_375_ap_return_4 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret_idct_step_fu_375_ap_return_5 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret_idct_step_fu_375_ap_return_6 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret_idct_step_fu_375_ap_return_7 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret_idct_step_fu_375_ap_return_8 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret_idct_step_fu_375_ap_return_9 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret_idct_step_fu_375_ap_return_10 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret_idct_step_fu_375_ap_return_11 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret_idct_step_fu_375_ap_return_12 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret_idct_step_fu_375_ap_return_13 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret_idct_step_fu_375_ap_return_14 : STD_LOGIC_VECTOR (19 downto 0);
    signal call_ret_idct_step_fu_375_ap_return_15 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal tmp_s_fu_605_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_0_1_fu_678_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_33_fu_539_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_fu_543_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal lhs_V_cast_fu_559_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_1_fu_563_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_2_fu_579_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_4_fu_585_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal phitmp_fu_569_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_595_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal phitmp1_fu_549_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_599_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_34_fu_612_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_0_1_fu_616_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal lhs_V_0_1_cast_fu_632_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_1_0_1_fu_636_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_2_0_1_fu_652_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_9_fu_658_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal phitmp_0_1_fu_642_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_668_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal phitmp1_0_1_fu_622_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp1_fu_672_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_35_fu_685_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_0_2_fu_689_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal lhs_V_0_2_cast_fu_705_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_1_0_2_fu_709_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_2_0_2_fu_725_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_2_fu_731_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal phitmp_0_2_fu_715_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_741_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal phitmp1_0_2_fu_695_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp2_fu_745_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_36_fu_757_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_0_3_fu_761_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal lhs_V_0_3_cast_fu_777_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_1_0_3_fu_781_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_2_0_3_fu_797_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_6_fu_803_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal phitmp_0_3_fu_787_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_813_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal phitmp1_0_3_fu_767_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp3_fu_817_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_37_fu_829_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_s_fu_833_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal lhs_V_1_cast_fu_849_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_1_1_fu_853_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_2_1_fu_869_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_8_fu_875_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal phitmp_1_fu_859_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_10_fu_885_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal phitmp1_1_fu_839_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp4_fu_889_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_38_fu_901_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_13_1_fu_905_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal lhs_V_1_1_cast_fu_921_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_1_1_1_fu_925_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_2_1_1_fu_941_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_11_fu_947_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal phitmp_1_1_fu_931_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_12_fu_957_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal phitmp1_1_1_fu_911_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp5_fu_961_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_39_fu_973_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_13_2_fu_977_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal lhs_V_1_2_cast_fu_993_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_1_1_2_fu_997_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_2_1_2_fu_1013_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_13_fu_1019_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal phitmp_1_2_fu_1003_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_14_fu_1029_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal phitmp1_1_2_fu_983_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp6_fu_1033_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_40_fu_1045_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_13_3_fu_1049_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal lhs_V_1_3_cast_fu_1065_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_1_1_3_fu_1069_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_2_1_3_fu_1085_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_15_fu_1091_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal phitmp_1_3_fu_1075_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_16_fu_1101_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal phitmp1_1_3_fu_1055_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp7_fu_1105_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_41_fu_1117_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_4_fu_1121_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal lhs_V_2_cast_fu_1137_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_1_2_fu_1141_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_2_2_fu_1157_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_17_fu_1163_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal phitmp_2_fu_1147_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_18_fu_1173_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal phitmp1_2_fu_1127_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp8_fu_1177_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_42_fu_1189_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_24_1_fu_1193_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal lhs_V_2_1_cast_fu_1209_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_1_2_1_fu_1213_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_2_2_1_fu_1229_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_19_fu_1235_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal phitmp_2_1_fu_1219_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_20_fu_1245_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal phitmp1_2_1_fu_1199_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp9_fu_1249_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_43_fu_1261_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_24_2_fu_1265_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal lhs_V_2_2_cast_fu_1281_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_1_2_2_fu_1285_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_2_2_2_fu_1301_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_21_fu_1307_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal phitmp_2_2_fu_1291_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_22_fu_1317_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal phitmp1_2_2_fu_1271_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp10_fu_1321_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_44_fu_1333_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_24_3_fu_1337_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal lhs_V_2_3_cast_fu_1353_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_1_2_3_fu_1357_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_2_2_3_fu_1373_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_23_fu_1379_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal phitmp_2_3_fu_1363_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_24_fu_1389_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal phitmp1_2_3_fu_1343_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp11_fu_1393_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_45_fu_1405_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_3_fu_1409_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal lhs_V_3_cast_fu_1425_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_1_3_fu_1429_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_2_3_fu_1445_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_25_fu_1451_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal phitmp_3_fu_1435_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_26_fu_1461_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal phitmp1_3_fu_1415_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp12_fu_1465_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_46_fu_1477_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_3_1_fu_1481_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal lhs_V_3_1_cast_fu_1497_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_1_3_1_fu_1501_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_2_3_1_fu_1517_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_27_fu_1523_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal phitmp_3_1_fu_1507_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_28_fu_1533_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal phitmp1_3_1_fu_1487_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp13_fu_1537_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_47_fu_1549_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_3_2_fu_1553_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal lhs_V_3_2_cast_fu_1569_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_1_3_2_fu_1573_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_2_3_2_fu_1589_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_29_fu_1595_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal phitmp_3_2_fu_1579_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_30_fu_1605_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal phitmp1_3_2_fu_1559_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp14_fu_1609_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_48_fu_1621_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_3_3_fu_1625_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal lhs_V_3_3_cast_fu_1641_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_1_3_3_fu_1645_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_2_3_3_fu_1661_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_31_fu_1667_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal phitmp_3_3_fu_1651_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_32_fu_1677_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal phitmp1_3_3_fu_1631_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp15_fu_1681_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);

    component idct_step IS
    port (
        ap_ready : OUT STD_LOGIC;
        isrc_0_0_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
        isrc_0_1_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
        isrc_0_2_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
        isrc_0_3_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
        isrc_1_0_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
        isrc_1_1_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
        isrc_1_2_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
        isrc_1_3_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
        isrc_2_0_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
        isrc_2_1_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
        isrc_2_2_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
        isrc_2_3_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
        isrc_3_0_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
        isrc_3_1_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
        isrc_3_2_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
        isrc_3_3_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (19 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (19 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (19 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (19 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (19 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (19 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (19 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (19 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (19 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (19 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (19 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (19 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (19 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (19 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (19 downto 0) );
    end component;



begin
    call_ret1_idct_step_fu_339 : component idct_step
    port map (
        ap_ready => call_ret1_idct_step_fu_339_ap_ready,
        isrc_0_0_V_read => src_0_0_V_read,
        isrc_0_1_V_read => src_0_1_V_read,
        isrc_0_2_V_read => src_0_2_V_read,
        isrc_0_3_V_read => src_0_3_V_read,
        isrc_1_0_V_read => src_1_0_V_read,
        isrc_1_1_V_read => src_1_1_V_read,
        isrc_1_2_V_read => src_1_2_V_read,
        isrc_1_3_V_read => src_1_3_V_read,
        isrc_2_0_V_read => src_2_0_V_read,
        isrc_2_1_V_read => src_2_1_V_read,
        isrc_2_2_V_read => src_2_2_V_read,
        isrc_2_3_V_read => src_2_3_V_read,
        isrc_3_0_V_read => src_3_0_V_read,
        isrc_3_1_V_read => src_3_1_V_read,
        isrc_3_2_V_read => src_3_2_V_read,
        isrc_3_3_V_read => src_3_3_V_read,
        ap_return_0 => call_ret1_idct_step_fu_339_ap_return_0,
        ap_return_1 => call_ret1_idct_step_fu_339_ap_return_1,
        ap_return_2 => call_ret1_idct_step_fu_339_ap_return_2,
        ap_return_3 => call_ret1_idct_step_fu_339_ap_return_3,
        ap_return_4 => call_ret1_idct_step_fu_339_ap_return_4,
        ap_return_5 => call_ret1_idct_step_fu_339_ap_return_5,
        ap_return_6 => call_ret1_idct_step_fu_339_ap_return_6,
        ap_return_7 => call_ret1_idct_step_fu_339_ap_return_7,
        ap_return_8 => call_ret1_idct_step_fu_339_ap_return_8,
        ap_return_9 => call_ret1_idct_step_fu_339_ap_return_9,
        ap_return_10 => call_ret1_idct_step_fu_339_ap_return_10,
        ap_return_11 => call_ret1_idct_step_fu_339_ap_return_11,
        ap_return_12 => call_ret1_idct_step_fu_339_ap_return_12,
        ap_return_13 => call_ret1_idct_step_fu_339_ap_return_13,
        ap_return_14 => call_ret1_idct_step_fu_339_ap_return_14,
        ap_return_15 => call_ret1_idct_step_fu_339_ap_return_15);

    call_ret_idct_step_fu_375 : component idct_step
    port map (
        ap_ready => call_ret_idct_step_fu_375_ap_ready,
        isrc_0_0_V_read => call_ret1_idct_step_fu_339_ap_return_0,
        isrc_0_1_V_read => call_ret1_idct_step_fu_339_ap_return_1,
        isrc_0_2_V_read => call_ret1_idct_step_fu_339_ap_return_2,
        isrc_0_3_V_read => call_ret1_idct_step_fu_339_ap_return_3,
        isrc_1_0_V_read => call_ret1_idct_step_fu_339_ap_return_4,
        isrc_1_1_V_read => call_ret1_idct_step_fu_339_ap_return_5,
        isrc_1_2_V_read => call_ret1_idct_step_fu_339_ap_return_6,
        isrc_1_3_V_read => call_ret1_idct_step_fu_339_ap_return_7,
        isrc_2_0_V_read => call_ret1_idct_step_fu_339_ap_return_8,
        isrc_2_1_V_read => call_ret1_idct_step_fu_339_ap_return_9,
        isrc_2_2_V_read => call_ret1_idct_step_fu_339_ap_return_10,
        isrc_2_3_V_read => call_ret1_idct_step_fu_339_ap_return_11,
        isrc_3_0_V_read => call_ret1_idct_step_fu_339_ap_return_12,
        isrc_3_1_V_read => call_ret1_idct_step_fu_339_ap_return_13,
        isrc_3_2_V_read => call_ret1_idct_step_fu_339_ap_return_14,
        isrc_3_3_V_read => call_ret1_idct_step_fu_339_ap_return_15,
        ap_return_0 => call_ret_idct_step_fu_375_ap_return_0,
        ap_return_1 => call_ret_idct_step_fu_375_ap_return_1,
        ap_return_2 => call_ret_idct_step_fu_375_ap_return_2,
        ap_return_3 => call_ret_idct_step_fu_375_ap_return_3,
        ap_return_4 => call_ret_idct_step_fu_375_ap_return_4,
        ap_return_5 => call_ret_idct_step_fu_375_ap_return_5,
        ap_return_6 => call_ret_idct_step_fu_375_ap_return_6,
        ap_return_7 => call_ret_idct_step_fu_375_ap_return_7,
        ap_return_8 => call_ret_idct_step_fu_375_ap_return_8,
        ap_return_9 => call_ret_idct_step_fu_375_ap_return_9,
        ap_return_10 => call_ret_idct_step_fu_375_ap_return_10,
        ap_return_11 => call_ret_idct_step_fu_375_ap_return_11,
        ap_return_12 => call_ret_idct_step_fu_375_ap_return_12,
        ap_return_13 => call_ret_idct_step_fu_375_ap_return_13,
        ap_return_14 => call_ret_idct_step_fu_375_ap_return_14,
        ap_return_15 => call_ret_idct_step_fu_375_ap_return_15);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                tmp_11_0_2_reg_1693 <= tmp_11_0_2_fu_751_p2;
                tmp_11_0_3_reg_1698 <= tmp_11_0_3_fu_823_p2;
                tmp_11_1_1_reg_1708 <= tmp_11_1_1_fu_967_p2;
                tmp_11_1_2_reg_1713 <= tmp_11_1_2_fu_1039_p2;
                tmp_11_1_3_reg_1718 <= tmp_11_1_3_fu_1111_p2;
                tmp_11_1_reg_1703 <= tmp_11_1_fu_895_p2;
                tmp_11_2_1_reg_1728 <= tmp_11_2_1_fu_1255_p2;
                tmp_11_2_2_reg_1733 <= tmp_11_2_2_fu_1327_p2;
                tmp_11_2_3_reg_1738 <= tmp_11_2_3_fu_1399_p2;
                tmp_11_2_reg_1723 <= tmp_11_2_fu_1183_p2;
                tmp_11_3_1_reg_1748 <= tmp_11_3_1_fu_1543_p2;
                tmp_11_3_2_reg_1753 <= tmp_11_3_2_fu_1615_p2;
                tmp_11_3_3_reg_1758 <= tmp_11_3_3_fu_1687_p2;
                tmp_11_3_reg_1743 <= tmp_11_3_fu_1471_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

        lhs_V_0_1_cast_fu_632_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(call_ret_idct_step_fu_375_ap_return_4),21));

        lhs_V_0_2_cast_fu_705_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(call_ret_idct_step_fu_375_ap_return_8),21));

        lhs_V_0_3_cast_fu_777_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(call_ret_idct_step_fu_375_ap_return_12),21));

        lhs_V_1_1_cast_fu_921_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(call_ret_idct_step_fu_375_ap_return_5),21));

        lhs_V_1_2_cast_fu_993_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(call_ret_idct_step_fu_375_ap_return_9),21));

        lhs_V_1_3_cast_fu_1065_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(call_ret_idct_step_fu_375_ap_return_13),21));

        lhs_V_1_cast_fu_849_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(call_ret_idct_step_fu_375_ap_return_1),21));

        lhs_V_2_1_cast_fu_1209_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(call_ret_idct_step_fu_375_ap_return_6),21));

        lhs_V_2_2_cast_fu_1281_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(call_ret_idct_step_fu_375_ap_return_10),21));

        lhs_V_2_3_cast_fu_1353_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(call_ret_idct_step_fu_375_ap_return_14),21));

        lhs_V_2_cast_fu_1137_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(call_ret_idct_step_fu_375_ap_return_2),21));

        lhs_V_3_1_cast_fu_1497_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(call_ret_idct_step_fu_375_ap_return_7),21));

        lhs_V_3_2_cast_fu_1569_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(call_ret_idct_step_fu_375_ap_return_11),21));

        lhs_V_3_3_cast_fu_1641_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(call_ret_idct_step_fu_375_ap_return_15),21));

        lhs_V_3_cast_fu_1425_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(call_ret_idct_step_fu_375_ap_return_3),21));

        lhs_V_cast_fu_559_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(call_ret_idct_step_fu_375_ap_return_0),21));


    out_r_address0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            out_r_address0 <= ap_const_lv64_E(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_r_address0 <= ap_const_lv64_C(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            out_r_address0 <= ap_const_lv64_A(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            out_r_address0 <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_r_address0 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            out_r_address0 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            out_r_address0 <= ap_const_lv64_2(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            out_r_address0 <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            out_r_address0 <= "XXXX";
        end if; 
    end process;


    out_r_address1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            out_r_address1 <= ap_const_lv64_F(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_r_address1 <= ap_const_lv64_D(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            out_r_address1 <= ap_const_lv64_B(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            out_r_address1 <= ap_const_lv64_9(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_r_address1 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            out_r_address1 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            out_r_address1 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            out_r_address1 <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            out_r_address1 <= "XXXX";
        end if; 
    end process;


    out_r_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            out_r_ce0 <= ap_const_logic_1;
        else 
            out_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    out_r_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            out_r_ce1 <= ap_const_logic_1;
        else 
            out_r_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    out_r_d0_assign_proc : process(ap_CS_fsm_state1, tmp_11_0_2_reg_1693, tmp_11_1_reg_1703, tmp_11_1_2_reg_1713, tmp_11_2_reg_1723, tmp_11_2_2_reg_1733, tmp_11_3_reg_1743, tmp_11_3_2_reg_1753, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, tmp_s_fu_605_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            out_r_d0 <= tmp_11_3_2_reg_1753;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_r_d0 <= tmp_11_3_reg_1743;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            out_r_d0 <= tmp_11_2_2_reg_1733;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            out_r_d0 <= tmp_11_2_reg_1723;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_r_d0 <= tmp_11_1_2_reg_1713;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            out_r_d0 <= tmp_11_1_reg_1703;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            out_r_d0 <= tmp_11_0_2_reg_1693;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            out_r_d0 <= tmp_s_fu_605_p2;
        else 
            out_r_d0 <= "XXXXXXXX";
        end if; 
    end process;


    out_r_d1_assign_proc : process(ap_CS_fsm_state1, tmp_11_0_3_reg_1698, tmp_11_1_1_reg_1708, tmp_11_1_3_reg_1718, tmp_11_2_1_reg_1728, tmp_11_2_3_reg_1738, tmp_11_3_1_reg_1748, tmp_11_3_3_reg_1758, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, tmp_11_0_1_fu_678_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            out_r_d1 <= tmp_11_3_3_reg_1758;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_r_d1 <= tmp_11_3_1_reg_1748;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            out_r_d1 <= tmp_11_2_3_reg_1738;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            out_r_d1 <= tmp_11_2_1_reg_1728;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_r_d1 <= tmp_11_1_3_reg_1718;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            out_r_d1 <= tmp_11_1_1_reg_1708;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            out_r_d1 <= tmp_11_0_3_reg_1698;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            out_r_d1 <= tmp_11_0_1_fu_678_p2;
        else 
            out_r_d1 <= "XXXXXXXX";
        end if; 
    end process;


    out_r_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            out_r_we0 <= ap_const_logic_1;
        else 
            out_r_we0 <= ap_const_logic_0;
        end if; 
    end process;


    out_r_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            out_r_we1 <= ap_const_logic_1;
        else 
            out_r_we1 <= ap_const_logic_0;
        end if; 
    end process;

    phitmp1_0_1_fu_622_p4 <= r_V_0_1_fu_616_p2(18 downto 11);
    phitmp1_0_2_fu_695_p4 <= r_V_0_2_fu_689_p2(18 downto 11);
    phitmp1_0_3_fu_767_p4 <= r_V_0_3_fu_761_p2(18 downto 11);
    phitmp1_1_1_fu_911_p4 <= r_V_13_1_fu_905_p2(18 downto 11);
    phitmp1_1_2_fu_983_p4 <= r_V_13_2_fu_977_p2(18 downto 11);
    phitmp1_1_3_fu_1055_p4 <= r_V_13_3_fu_1049_p2(18 downto 11);
    phitmp1_1_fu_839_p4 <= r_V_s_fu_833_p2(18 downto 11);
    phitmp1_2_1_fu_1199_p4 <= r_V_24_1_fu_1193_p2(18 downto 11);
    phitmp1_2_2_fu_1271_p4 <= r_V_24_2_fu_1265_p2(18 downto 11);
    phitmp1_2_3_fu_1343_p4 <= r_V_24_3_fu_1337_p2(18 downto 11);
    phitmp1_2_fu_1127_p4 <= r_V_4_fu_1121_p2(18 downto 11);
    phitmp1_3_1_fu_1487_p4 <= r_V_3_1_fu_1481_p2(18 downto 11);
    phitmp1_3_2_fu_1559_p4 <= r_V_3_2_fu_1553_p2(18 downto 11);
    phitmp1_3_3_fu_1631_p4 <= r_V_3_3_fu_1625_p2(18 downto 11);
    phitmp1_3_fu_1415_p4 <= r_V_3_fu_1409_p2(18 downto 11);
    phitmp1_fu_549_p4 <= r_V_fu_543_p2(18 downto 11);
    phitmp_0_1_fu_642_p4 <= r_V_1_0_1_fu_636_p2(20 downto 13);
    phitmp_0_2_fu_715_p4 <= r_V_1_0_2_fu_709_p2(20 downto 13);
    phitmp_0_3_fu_787_p4 <= r_V_1_0_3_fu_781_p2(20 downto 13);
    phitmp_1_1_fu_931_p4 <= r_V_1_1_1_fu_925_p2(20 downto 13);
    phitmp_1_2_fu_1003_p4 <= r_V_1_1_2_fu_997_p2(20 downto 13);
    phitmp_1_3_fu_1075_p4 <= r_V_1_1_3_fu_1069_p2(20 downto 13);
    phitmp_1_fu_859_p4 <= r_V_1_1_fu_853_p2(20 downto 13);
    phitmp_2_1_fu_1219_p4 <= r_V_1_2_1_fu_1213_p2(20 downto 13);
    phitmp_2_2_fu_1291_p4 <= r_V_1_2_2_fu_1285_p2(20 downto 13);
    phitmp_2_3_fu_1363_p4 <= r_V_1_2_3_fu_1357_p2(20 downto 13);
    phitmp_2_fu_1147_p4 <= r_V_1_2_fu_1141_p2(20 downto 13);
    phitmp_3_1_fu_1507_p4 <= r_V_1_3_1_fu_1501_p2(20 downto 13);
    phitmp_3_2_fu_1579_p4 <= r_V_1_3_2_fu_1573_p2(20 downto 13);
    phitmp_3_3_fu_1651_p4 <= r_V_1_3_3_fu_1645_p2(20 downto 13);
    phitmp_3_fu_1435_p4 <= r_V_1_3_fu_1429_p2(20 downto 13);
    phitmp_fu_569_p4 <= r_V_1_fu_563_p2(20 downto 13);
    r_V_0_1_fu_616_p2 <= std_logic_vector(unsigned(ap_const_lv19_400) + unsigned(tmp_34_fu_612_p1));
    r_V_0_2_fu_689_p2 <= std_logic_vector(unsigned(ap_const_lv19_400) + unsigned(tmp_35_fu_685_p1));
    r_V_0_3_fu_761_p2 <= std_logic_vector(unsigned(ap_const_lv19_400) + unsigned(tmp_36_fu_757_p1));
    r_V_13_1_fu_905_p2 <= std_logic_vector(unsigned(ap_const_lv19_400) + unsigned(tmp_38_fu_901_p1));
    r_V_13_2_fu_977_p2 <= std_logic_vector(unsigned(ap_const_lv19_400) + unsigned(tmp_39_fu_973_p1));
    r_V_13_3_fu_1049_p2 <= std_logic_vector(unsigned(ap_const_lv19_400) + unsigned(tmp_40_fu_1045_p1));
    r_V_1_0_1_fu_636_p2 <= std_logic_vector(unsigned(ap_const_lv21_1000) + unsigned(lhs_V_0_1_cast_fu_632_p1));
    r_V_1_0_2_fu_709_p2 <= std_logic_vector(unsigned(ap_const_lv21_1000) + unsigned(lhs_V_0_2_cast_fu_705_p1));
    r_V_1_0_3_fu_781_p2 <= std_logic_vector(unsigned(ap_const_lv21_1000) + unsigned(lhs_V_0_3_cast_fu_777_p1));
    r_V_1_1_1_fu_925_p2 <= std_logic_vector(unsigned(ap_const_lv21_1000) + unsigned(lhs_V_1_1_cast_fu_921_p1));
    r_V_1_1_2_fu_997_p2 <= std_logic_vector(unsigned(ap_const_lv21_1000) + unsigned(lhs_V_1_2_cast_fu_993_p1));
    r_V_1_1_3_fu_1069_p2 <= std_logic_vector(unsigned(ap_const_lv21_1000) + unsigned(lhs_V_1_3_cast_fu_1065_p1));
    r_V_1_1_fu_853_p2 <= std_logic_vector(unsigned(ap_const_lv21_1000) + unsigned(lhs_V_1_cast_fu_849_p1));
    r_V_1_2_1_fu_1213_p2 <= std_logic_vector(unsigned(ap_const_lv21_1000) + unsigned(lhs_V_2_1_cast_fu_1209_p1));
    r_V_1_2_2_fu_1285_p2 <= std_logic_vector(unsigned(ap_const_lv21_1000) + unsigned(lhs_V_2_2_cast_fu_1281_p1));
    r_V_1_2_3_fu_1357_p2 <= std_logic_vector(unsigned(ap_const_lv21_1000) + unsigned(lhs_V_2_3_cast_fu_1353_p1));
    r_V_1_2_fu_1141_p2 <= std_logic_vector(unsigned(ap_const_lv21_1000) + unsigned(lhs_V_2_cast_fu_1137_p1));
    r_V_1_3_1_fu_1501_p2 <= std_logic_vector(unsigned(ap_const_lv21_1000) + unsigned(lhs_V_3_1_cast_fu_1497_p1));
    r_V_1_3_2_fu_1573_p2 <= std_logic_vector(unsigned(ap_const_lv21_1000) + unsigned(lhs_V_3_2_cast_fu_1569_p1));
    r_V_1_3_3_fu_1645_p2 <= std_logic_vector(unsigned(ap_const_lv21_1000) + unsigned(lhs_V_3_3_cast_fu_1641_p1));
    r_V_1_3_fu_1429_p2 <= std_logic_vector(unsigned(ap_const_lv21_1000) + unsigned(lhs_V_3_cast_fu_1425_p1));
    r_V_1_fu_563_p2 <= std_logic_vector(unsigned(ap_const_lv21_1000) + unsigned(lhs_V_cast_fu_559_p1));
    r_V_24_1_fu_1193_p2 <= std_logic_vector(unsigned(ap_const_lv19_400) + unsigned(tmp_42_fu_1189_p1));
    r_V_24_2_fu_1265_p2 <= std_logic_vector(unsigned(ap_const_lv19_400) + unsigned(tmp_43_fu_1261_p1));
    r_V_24_3_fu_1337_p2 <= std_logic_vector(unsigned(ap_const_lv19_400) + unsigned(tmp_44_fu_1333_p1));
    r_V_2_0_1_fu_652_p2 <= std_logic_vector(unsigned(ap_const_lv21_8000) + unsigned(lhs_V_0_1_cast_fu_632_p1));
    r_V_2_0_2_fu_725_p2 <= std_logic_vector(unsigned(ap_const_lv21_8000) + unsigned(lhs_V_0_2_cast_fu_705_p1));
    r_V_2_0_3_fu_797_p2 <= std_logic_vector(unsigned(ap_const_lv21_8000) + unsigned(lhs_V_0_3_cast_fu_777_p1));
    r_V_2_1_1_fu_941_p2 <= std_logic_vector(unsigned(ap_const_lv21_8000) + unsigned(lhs_V_1_1_cast_fu_921_p1));
    r_V_2_1_2_fu_1013_p2 <= std_logic_vector(unsigned(ap_const_lv21_8000) + unsigned(lhs_V_1_2_cast_fu_993_p1));
    r_V_2_1_3_fu_1085_p2 <= std_logic_vector(unsigned(ap_const_lv21_8000) + unsigned(lhs_V_1_3_cast_fu_1065_p1));
    r_V_2_1_fu_869_p2 <= std_logic_vector(unsigned(ap_const_lv21_8000) + unsigned(lhs_V_1_cast_fu_849_p1));
    r_V_2_2_1_fu_1229_p2 <= std_logic_vector(unsigned(ap_const_lv21_8000) + unsigned(lhs_V_2_1_cast_fu_1209_p1));
    r_V_2_2_2_fu_1301_p2 <= std_logic_vector(unsigned(ap_const_lv21_8000) + unsigned(lhs_V_2_2_cast_fu_1281_p1));
    r_V_2_2_3_fu_1373_p2 <= std_logic_vector(unsigned(ap_const_lv21_8000) + unsigned(lhs_V_2_3_cast_fu_1353_p1));
    r_V_2_2_fu_1157_p2 <= std_logic_vector(unsigned(ap_const_lv21_8000) + unsigned(lhs_V_2_cast_fu_1137_p1));
    r_V_2_3_1_fu_1517_p2 <= std_logic_vector(unsigned(ap_const_lv21_8000) + unsigned(lhs_V_3_1_cast_fu_1497_p1));
    r_V_2_3_2_fu_1589_p2 <= std_logic_vector(unsigned(ap_const_lv21_8000) + unsigned(lhs_V_3_2_cast_fu_1569_p1));
    r_V_2_3_3_fu_1661_p2 <= std_logic_vector(unsigned(ap_const_lv21_8000) + unsigned(lhs_V_3_3_cast_fu_1641_p1));
    r_V_2_3_fu_1445_p2 <= std_logic_vector(unsigned(ap_const_lv21_8000) + unsigned(lhs_V_3_cast_fu_1425_p1));
    r_V_2_fu_579_p2 <= std_logic_vector(unsigned(ap_const_lv21_8000) + unsigned(lhs_V_cast_fu_559_p1));
    r_V_3_1_fu_1481_p2 <= std_logic_vector(unsigned(ap_const_lv19_400) + unsigned(tmp_46_fu_1477_p1));
    r_V_3_2_fu_1553_p2 <= std_logic_vector(unsigned(ap_const_lv19_400) + unsigned(tmp_47_fu_1549_p1));
    r_V_3_3_fu_1625_p2 <= std_logic_vector(unsigned(ap_const_lv19_400) + unsigned(tmp_48_fu_1621_p1));
    r_V_3_fu_1409_p2 <= std_logic_vector(unsigned(ap_const_lv19_400) + unsigned(tmp_45_fu_1405_p1));
    r_V_4_fu_1121_p2 <= std_logic_vector(unsigned(ap_const_lv19_400) + unsigned(tmp_41_fu_1117_p1));
    r_V_fu_543_p2 <= std_logic_vector(unsigned(ap_const_lv19_400) + unsigned(tmp_33_fu_539_p1));
    r_V_s_fu_833_p2 <= std_logic_vector(unsigned(ap_const_lv19_400) + unsigned(tmp_37_fu_829_p1));
    tmp10_fu_1321_p2 <= std_logic_vector(unsigned(phitmp_2_2_fu_1291_p4) + unsigned(tmp_22_fu_1317_p1));
    tmp11_fu_1393_p2 <= std_logic_vector(unsigned(phitmp_2_3_fu_1363_p4) + unsigned(tmp_24_fu_1389_p1));
    tmp12_fu_1465_p2 <= std_logic_vector(unsigned(phitmp_3_fu_1435_p4) + unsigned(tmp_26_fu_1461_p1));
    tmp13_fu_1537_p2 <= std_logic_vector(unsigned(phitmp_3_1_fu_1507_p4) + unsigned(tmp_28_fu_1533_p1));
    tmp14_fu_1609_p2 <= std_logic_vector(unsigned(phitmp_3_2_fu_1579_p4) + unsigned(tmp_30_fu_1605_p1));
    tmp15_fu_1681_p2 <= std_logic_vector(unsigned(phitmp_3_3_fu_1651_p4) + unsigned(tmp_32_fu_1677_p1));
    tmp1_fu_672_p2 <= std_logic_vector(unsigned(phitmp_0_1_fu_642_p4) + unsigned(tmp_1_fu_668_p1));
    tmp2_fu_745_p2 <= std_logic_vector(unsigned(phitmp_0_2_fu_715_p4) + unsigned(tmp_3_fu_741_p1));
    tmp3_fu_817_p2 <= std_logic_vector(unsigned(phitmp_0_3_fu_787_p4) + unsigned(tmp_7_fu_813_p1));
    tmp4_fu_889_p2 <= std_logic_vector(unsigned(phitmp_1_fu_859_p4) + unsigned(tmp_10_fu_885_p1));
    tmp5_fu_961_p2 <= std_logic_vector(unsigned(phitmp_1_1_fu_931_p4) + unsigned(tmp_12_fu_957_p1));
    tmp6_fu_1033_p2 <= std_logic_vector(unsigned(phitmp_1_2_fu_1003_p4) + unsigned(tmp_14_fu_1029_p1));
    tmp7_fu_1105_p2 <= std_logic_vector(unsigned(phitmp_1_3_fu_1075_p4) + unsigned(tmp_16_fu_1101_p1));
    tmp8_fu_1177_p2 <= std_logic_vector(unsigned(phitmp_2_fu_1147_p4) + unsigned(tmp_18_fu_1173_p1));
    tmp9_fu_1249_p2 <= std_logic_vector(unsigned(phitmp_2_1_fu_1219_p4) + unsigned(tmp_20_fu_1245_p1));
        tmp_10_fu_885_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_8_fu_875_p4),8));

    tmp_11_0_1_fu_678_p2 <= std_logic_vector(unsigned(phitmp1_0_1_fu_622_p4) + unsigned(tmp1_fu_672_p2));
    tmp_11_0_2_fu_751_p2 <= std_logic_vector(unsigned(phitmp1_0_2_fu_695_p4) + unsigned(tmp2_fu_745_p2));
    tmp_11_0_3_fu_823_p2 <= std_logic_vector(unsigned(phitmp1_0_3_fu_767_p4) + unsigned(tmp3_fu_817_p2));
    tmp_11_1_1_fu_967_p2 <= std_logic_vector(unsigned(phitmp1_1_1_fu_911_p4) + unsigned(tmp5_fu_961_p2));
    tmp_11_1_2_fu_1039_p2 <= std_logic_vector(unsigned(phitmp1_1_2_fu_983_p4) + unsigned(tmp6_fu_1033_p2));
    tmp_11_1_3_fu_1111_p2 <= std_logic_vector(unsigned(phitmp1_1_3_fu_1055_p4) + unsigned(tmp7_fu_1105_p2));
    tmp_11_1_fu_895_p2 <= std_logic_vector(unsigned(phitmp1_1_fu_839_p4) + unsigned(tmp4_fu_889_p2));
    tmp_11_2_1_fu_1255_p2 <= std_logic_vector(unsigned(phitmp1_2_1_fu_1199_p4) + unsigned(tmp9_fu_1249_p2));
    tmp_11_2_2_fu_1327_p2 <= std_logic_vector(unsigned(phitmp1_2_2_fu_1271_p4) + unsigned(tmp10_fu_1321_p2));
    tmp_11_2_3_fu_1399_p2 <= std_logic_vector(unsigned(phitmp1_2_3_fu_1343_p4) + unsigned(tmp11_fu_1393_p2));
    tmp_11_2_fu_1183_p2 <= std_logic_vector(unsigned(phitmp1_2_fu_1127_p4) + unsigned(tmp8_fu_1177_p2));
    tmp_11_3_1_fu_1543_p2 <= std_logic_vector(unsigned(phitmp1_3_1_fu_1487_p4) + unsigned(tmp13_fu_1537_p2));
    tmp_11_3_2_fu_1615_p2 <= std_logic_vector(unsigned(phitmp1_3_2_fu_1559_p4) + unsigned(tmp14_fu_1609_p2));
    tmp_11_3_3_fu_1687_p2 <= std_logic_vector(unsigned(phitmp1_3_3_fu_1631_p4) + unsigned(tmp15_fu_1681_p2));
    tmp_11_3_fu_1471_p2 <= std_logic_vector(unsigned(phitmp1_3_fu_1415_p4) + unsigned(tmp12_fu_1465_p2));
    tmp_11_fu_947_p4 <= r_V_2_1_1_fu_941_p2(20 downto 16);
        tmp_12_fu_957_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_11_fu_947_p4),8));

    tmp_13_fu_1019_p4 <= r_V_2_1_2_fu_1013_p2(20 downto 16);
        tmp_14_fu_1029_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_13_fu_1019_p4),8));

    tmp_15_fu_1091_p4 <= r_V_2_1_3_fu_1085_p2(20 downto 16);
        tmp_16_fu_1101_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_15_fu_1091_p4),8));

    tmp_17_fu_1163_p4 <= r_V_2_2_fu_1157_p2(20 downto 16);
        tmp_18_fu_1173_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_17_fu_1163_p4),8));

    tmp_19_fu_1235_p4 <= r_V_2_2_1_fu_1229_p2(20 downto 16);
        tmp_1_fu_668_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_9_fu_658_p4),8));

        tmp_20_fu_1245_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_19_fu_1235_p4),8));

    tmp_21_fu_1307_p4 <= r_V_2_2_2_fu_1301_p2(20 downto 16);
        tmp_22_fu_1317_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_21_fu_1307_p4),8));

    tmp_23_fu_1379_p4 <= r_V_2_2_3_fu_1373_p2(20 downto 16);
        tmp_24_fu_1389_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_23_fu_1379_p4),8));

    tmp_25_fu_1451_p4 <= r_V_2_3_fu_1445_p2(20 downto 16);
        tmp_26_fu_1461_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_25_fu_1451_p4),8));

    tmp_27_fu_1523_p4 <= r_V_2_3_1_fu_1517_p2(20 downto 16);
        tmp_28_fu_1533_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_27_fu_1523_p4),8));

    tmp_29_fu_1595_p4 <= r_V_2_3_2_fu_1589_p2(20 downto 16);
    tmp_2_fu_731_p4 <= r_V_2_0_2_fu_725_p2(20 downto 16);
        tmp_30_fu_1605_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_29_fu_1595_p4),8));

    tmp_31_fu_1667_p4 <= r_V_2_3_3_fu_1661_p2(20 downto 16);
        tmp_32_fu_1677_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_31_fu_1667_p4),8));

    tmp_33_fu_539_p1 <= call_ret_idct_step_fu_375_ap_return_0(19 - 1 downto 0);
    tmp_34_fu_612_p1 <= call_ret_idct_step_fu_375_ap_return_4(19 - 1 downto 0);
    tmp_35_fu_685_p1 <= call_ret_idct_step_fu_375_ap_return_8(19 - 1 downto 0);
    tmp_36_fu_757_p1 <= call_ret_idct_step_fu_375_ap_return_12(19 - 1 downto 0);
    tmp_37_fu_829_p1 <= call_ret_idct_step_fu_375_ap_return_1(19 - 1 downto 0);
    tmp_38_fu_901_p1 <= call_ret_idct_step_fu_375_ap_return_5(19 - 1 downto 0);
    tmp_39_fu_973_p1 <= call_ret_idct_step_fu_375_ap_return_9(19 - 1 downto 0);
        tmp_3_fu_741_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_731_p4),8));

    tmp_40_fu_1045_p1 <= call_ret_idct_step_fu_375_ap_return_13(19 - 1 downto 0);
    tmp_41_fu_1117_p1 <= call_ret_idct_step_fu_375_ap_return_2(19 - 1 downto 0);
    tmp_42_fu_1189_p1 <= call_ret_idct_step_fu_375_ap_return_6(19 - 1 downto 0);
    tmp_43_fu_1261_p1 <= call_ret_idct_step_fu_375_ap_return_10(19 - 1 downto 0);
    tmp_44_fu_1333_p1 <= call_ret_idct_step_fu_375_ap_return_14(19 - 1 downto 0);
    tmp_45_fu_1405_p1 <= call_ret_idct_step_fu_375_ap_return_3(19 - 1 downto 0);
    tmp_46_fu_1477_p1 <= call_ret_idct_step_fu_375_ap_return_7(19 - 1 downto 0);
    tmp_47_fu_1549_p1 <= call_ret_idct_step_fu_375_ap_return_11(19 - 1 downto 0);
    tmp_48_fu_1621_p1 <= call_ret_idct_step_fu_375_ap_return_15(19 - 1 downto 0);
    tmp_4_fu_585_p4 <= r_V_2_fu_579_p2(20 downto 16);
        tmp_5_fu_595_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_4_fu_585_p4),8));

    tmp_6_fu_803_p4 <= r_V_2_0_3_fu_797_p2(20 downto 16);
        tmp_7_fu_813_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_6_fu_803_p4),8));

    tmp_8_fu_875_p4 <= r_V_2_1_fu_869_p2(20 downto 16);
    tmp_9_fu_658_p4 <= r_V_2_0_1_fu_652_p2(20 downto 16);
    tmp_fu_599_p2 <= std_logic_vector(unsigned(phitmp_fu_569_p4) + unsigned(tmp_5_fu_595_p1));
    tmp_s_fu_605_p2 <= std_logic_vector(unsigned(phitmp1_fu_549_p4) + unsigned(tmp_fu_599_p2));
end behav;
