// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dct_step (
        ap_ready,
        src_0_0_read,
        src_0_1_read,
        src_0_2_read,
        src_0_3_read,
        src_1_0_read,
        src_1_1_read,
        src_1_2_read,
        src_1_3_read,
        src_2_0_read,
        src_2_1_read,
        src_2_2_read,
        src_2_3_read,
        src_3_0_read,
        src_3_1_read,
        src_3_2_read,
        src_3_3_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);


output   ap_ready;
input  [15:0] src_0_0_read;
input  [15:0] src_0_1_read;
input  [15:0] src_0_2_read;
input  [15:0] src_0_3_read;
input  [15:0] src_1_0_read;
input  [15:0] src_1_1_read;
input  [15:0] src_1_2_read;
input  [15:0] src_1_3_read;
input  [15:0] src_2_0_read;
input  [15:0] src_2_1_read;
input  [15:0] src_2_2_read;
input  [15:0] src_2_3_read;
input  [15:0] src_3_0_read;
input  [15:0] src_3_1_read;
input  [15:0] src_3_2_read;
input  [15:0] src_3_3_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;

wire   [15:0] tmp2_fu_140_p2;
wire   [15:0] tmp1_fu_134_p2;
wire   [15:0] tmp4_fu_158_p2;
wire   [15:0] tmp3_fu_152_p2;
wire   [15:0] tmp6_fu_176_p2;
wire   [15:0] tmp5_fu_170_p2;
wire   [15:0] tmp8_fu_194_p2;
wire   [15:0] tmp7_fu_188_p2;
wire   [15:0] tmp_fu_206_p2;
wire   [15:0] tmp_28_fu_218_p2;
wire   [15:0] tmp_29_fu_224_p2;
wire   [15:0] tmp_75_fu_212_p2;
wire   [15:0] tmp_76_fu_236_p2;
wire   [15:0] tmp_s_fu_248_p2;
wire   [15:0] tmp_32_fu_254_p2;
wire   [15:0] tmp_77_fu_242_p2;
wire   [15:0] tmp_78_fu_266_p2;
wire   [15:0] tmp_33_fu_278_p2;
wire   [15:0] tmp_34_fu_284_p2;
wire   [15:0] tmp_79_fu_272_p2;
wire   [15:0] tmp_80_fu_296_p2;
wire   [15:0] tmp_35_fu_308_p2;
wire   [15:0] tmp_36_fu_314_p2;
wire   [15:0] tmp_81_fu_302_p2;
wire   [15:0] tmp_37_fu_326_p2;
wire   [15:0] tmp_38_fu_332_p2;
wire   [15:0] tmp_39_fu_344_p2;
wire   [15:0] tmp_40_fu_350_p2;
wire   [15:0] tmp_41_fu_362_p2;
wire   [15:0] tmp_42_fu_368_p2;
wire   [15:0] tmp_43_fu_380_p2;
wire   [15:0] tmp_44_fu_386_p2;
wire   [15:0] tmp_82_fu_398_p2;
wire   [15:0] tmp_45_fu_410_p2;
wire   [15:0] tmp_83_fu_404_p2;
wire   [15:0] tmp_46_fu_416_p2;
wire   [15:0] tmp_84_fu_428_p2;
wire   [15:0] tmp_47_fu_440_p2;
wire   [15:0] tmp_85_fu_434_p2;
wire   [15:0] tmp_48_fu_446_p2;
wire   [15:0] tmp_86_fu_458_p2;
wire   [15:0] tmp_49_fu_470_p2;
wire   [15:0] tmp_87_fu_464_p2;
wire   [15:0] tmp_50_fu_476_p2;
wire   [15:0] tmp_88_fu_488_p2;
wire   [15:0] tmp_51_fu_500_p2;
wire   [15:0] tmp_89_fu_494_p2;
wire   [15:0] tmp_52_fu_506_p2;
wire   [15:0] dst_0_0_write_assi_fu_146_p2;
wire   [15:0] dst_0_1_write_assi_fu_230_p2;
wire   [15:0] dst_0_2_write_assi_fu_338_p2;
wire   [15:0] dst_0_3_write_assi_fu_422_p2;
wire   [15:0] dst_1_0_write_assi_fu_164_p2;
wire   [15:0] dst_1_1_write_assi_fu_260_p2;
wire   [15:0] dst_1_2_write_assi_fu_356_p2;
wire   [15:0] dst_1_3_write_assi_fu_452_p2;
wire   [15:0] dst_2_0_write_assi_fu_182_p2;
wire   [15:0] dst_2_1_write_assi_fu_290_p2;
wire   [15:0] dst_2_2_write_assi_fu_374_p2;
wire   [15:0] dst_2_3_write_assi_fu_482_p2;
wire   [15:0] dst_3_0_write_assi_fu_200_p2;
wire   [15:0] dst_3_1_write_assi_fu_320_p2;
wire   [15:0] dst_3_2_write_assi_fu_392_p2;
wire   [15:0] dst_3_3_write_assi_fu_512_p2;

assign ap_ready = 1'b1;

assign ap_return_0 = dst_0_0_write_assi_fu_146_p2;

assign ap_return_1 = dst_0_1_write_assi_fu_230_p2;

assign ap_return_10 = dst_2_2_write_assi_fu_374_p2;

assign ap_return_11 = dst_2_3_write_assi_fu_482_p2;

assign ap_return_12 = dst_3_0_write_assi_fu_200_p2;

assign ap_return_13 = dst_3_1_write_assi_fu_320_p2;

assign ap_return_14 = dst_3_2_write_assi_fu_392_p2;

assign ap_return_15 = dst_3_3_write_assi_fu_512_p2;

assign ap_return_2 = dst_0_2_write_assi_fu_338_p2;

assign ap_return_3 = dst_0_3_write_assi_fu_422_p2;

assign ap_return_4 = dst_1_0_write_assi_fu_164_p2;

assign ap_return_5 = dst_1_1_write_assi_fu_260_p2;

assign ap_return_6 = dst_1_2_write_assi_fu_356_p2;

assign ap_return_7 = dst_1_3_write_assi_fu_452_p2;

assign ap_return_8 = dst_2_0_write_assi_fu_182_p2;

assign ap_return_9 = dst_2_1_write_assi_fu_290_p2;

assign dst_0_0_write_assi_fu_146_p2 = (tmp2_fu_140_p2 + tmp1_fu_134_p2);

assign dst_0_1_write_assi_fu_230_p2 = (tmp_29_fu_224_p2 - tmp_75_fu_212_p2);

assign dst_0_2_write_assi_fu_338_p2 = (src_3_0_read + tmp_38_fu_332_p2);

assign dst_0_3_write_assi_fu_422_p2 = (tmp_46_fu_416_p2 - src_3_0_read);

assign dst_1_0_write_assi_fu_164_p2 = (tmp4_fu_158_p2 + tmp3_fu_152_p2);

assign dst_1_1_write_assi_fu_260_p2 = (tmp_32_fu_254_p2 - tmp_77_fu_242_p2);

assign dst_1_2_write_assi_fu_356_p2 = (src_3_1_read + tmp_40_fu_350_p2);

assign dst_1_3_write_assi_fu_452_p2 = (tmp_48_fu_446_p2 - src_3_1_read);

assign dst_2_0_write_assi_fu_182_p2 = (tmp6_fu_176_p2 + tmp5_fu_170_p2);

assign dst_2_1_write_assi_fu_290_p2 = (tmp_34_fu_284_p2 - tmp_79_fu_272_p2);

assign dst_2_2_write_assi_fu_374_p2 = (src_3_2_read + tmp_42_fu_368_p2);

assign dst_2_3_write_assi_fu_482_p2 = (tmp_50_fu_476_p2 - src_3_2_read);

assign dst_3_0_write_assi_fu_200_p2 = (tmp8_fu_194_p2 + tmp7_fu_188_p2);

assign dst_3_1_write_assi_fu_320_p2 = (tmp_36_fu_314_p2 - tmp_81_fu_302_p2);

assign dst_3_2_write_assi_fu_392_p2 = (src_3_3_read + tmp_44_fu_386_p2);

assign dst_3_3_write_assi_fu_512_p2 = (tmp_52_fu_506_p2 - src_3_3_read);

assign tmp1_fu_134_p2 = (src_1_0_read + src_0_0_read);

assign tmp2_fu_140_p2 = (src_2_0_read + src_3_0_read);

assign tmp3_fu_152_p2 = (src_1_1_read + src_0_1_read);

assign tmp4_fu_158_p2 = (src_2_1_read + src_3_1_read);

assign tmp5_fu_170_p2 = (src_1_2_read + src_0_2_read);

assign tmp6_fu_176_p2 = (src_2_2_read + src_3_2_read);

assign tmp7_fu_188_p2 = (src_1_3_read + src_0_3_read);

assign tmp8_fu_194_p2 = (src_2_3_read + src_3_3_read);

assign tmp_28_fu_218_p2 = (src_1_0_read + tmp_fu_206_p2);

assign tmp_29_fu_224_p2 = (tmp_28_fu_218_p2 - src_2_0_read);

assign tmp_32_fu_254_p2 = (tmp_s_fu_248_p2 - src_2_1_read);

assign tmp_33_fu_278_p2 = (src_1_2_read + tmp_78_fu_266_p2);

assign tmp_34_fu_284_p2 = (tmp_33_fu_278_p2 - src_2_2_read);

assign tmp_35_fu_308_p2 = (src_1_3_read + tmp_80_fu_296_p2);

assign tmp_36_fu_314_p2 = (tmp_35_fu_308_p2 - src_2_3_read);

assign tmp_37_fu_326_p2 = (src_0_0_read - src_1_0_read);

assign tmp_38_fu_332_p2 = (tmp_37_fu_326_p2 - src_2_0_read);

assign tmp_39_fu_344_p2 = (src_0_1_read - src_1_1_read);

assign tmp_40_fu_350_p2 = (tmp_39_fu_344_p2 - src_2_1_read);

assign tmp_41_fu_362_p2 = (src_0_2_read - src_1_2_read);

assign tmp_42_fu_368_p2 = (tmp_41_fu_362_p2 - src_2_2_read);

assign tmp_43_fu_380_p2 = (src_0_3_read - src_1_3_read);

assign tmp_44_fu_386_p2 = (tmp_43_fu_380_p2 - src_2_3_read);

assign tmp_45_fu_410_p2 = (src_0_0_read - tmp_82_fu_398_p2);

assign tmp_46_fu_416_p2 = (tmp_45_fu_410_p2 + tmp_83_fu_404_p2);

assign tmp_47_fu_440_p2 = (src_0_1_read - tmp_84_fu_428_p2);

assign tmp_48_fu_446_p2 = (tmp_47_fu_440_p2 + tmp_85_fu_434_p2);

assign tmp_49_fu_470_p2 = (src_0_2_read - tmp_86_fu_458_p2);

assign tmp_50_fu_476_p2 = (tmp_49_fu_470_p2 + tmp_87_fu_464_p2);

assign tmp_51_fu_500_p2 = (src_0_3_read - tmp_88_fu_488_p2);

assign tmp_52_fu_506_p2 = (tmp_51_fu_500_p2 + tmp_89_fu_494_p2);

assign tmp_75_fu_212_p2 = src_3_0_read << 16'd1;

assign tmp_76_fu_236_p2 = src_0_1_read << 16'd1;

assign tmp_77_fu_242_p2 = src_3_1_read << 16'd1;

assign tmp_78_fu_266_p2 = src_0_2_read << 16'd1;

assign tmp_79_fu_272_p2 = src_3_2_read << 16'd1;

assign tmp_80_fu_296_p2 = src_0_3_read << 16'd1;

assign tmp_81_fu_302_p2 = src_3_3_read << 16'd1;

assign tmp_82_fu_398_p2 = src_1_0_read << 16'd1;

assign tmp_83_fu_404_p2 = src_2_0_read << 16'd1;

assign tmp_84_fu_428_p2 = src_1_1_read << 16'd1;

assign tmp_85_fu_434_p2 = src_2_1_read << 16'd1;

assign tmp_86_fu_458_p2 = src_1_2_read << 16'd1;

assign tmp_87_fu_464_p2 = src_2_2_read << 16'd1;

assign tmp_88_fu_488_p2 = src_1_3_read << 16'd1;

assign tmp_89_fu_494_p2 = src_2_3_read << 16'd1;

assign tmp_fu_206_p2 = src_0_0_read << 16'd1;

assign tmp_s_fu_248_p2 = (src_1_1_read + tmp_76_fu_236_p2);

endmodule //dct_step
